redcanaryco/atomic-red-team

Mac/Defense_Evasion/Clear_Command_History.md, Mac/Defense_Evasion/Gatekeeper_Bypass.md
- Clear Command History
- Gatekeeper Bypass
=> Submitting two new Mac techniques

ARTifacts/Chain_Reactions/README.md
=> Chain Reactions

ARTifacts/Chain_Reactions/chain_reaction_01.bat, ARTifacts/Chain_Reactions/chain_reaction_02.bat, Linux/Discovery/Account_Discovery.md, Linux/Persistence/Cron_Job.md, Windows/Discovery/File_and_Directory_Discovery.md, Windows/Discovery/Security_Software_Discovery.md, Windows/Discovery/System_Network_Configuration_Discovery.md, Windows/Execution/PowerShell.md
+ Added two chain reactions
+ Added new items to Execution/Powershell
+ Linux Account Discovery
+ Modified few others with new updates for profit.
=> Chain Reactions + Linux + Updates

Windows/Execution/PowerShell.md
Updated References For PowerShell
=> Updated Mimikatz References

Windows/Collection/Input_Capture.md
Per https://github.com/redcanaryco/atomic-red-team/issues/22, fixing payload link location.
=> Input Capture - Payload Reference fix

Windows/Payloads/AtomicService.cs, Windows/Persistence/Service_Installation.md
Added Basic Service Binary Code to Create and Start a Service
=> Service Binary Code

Windows/Payloads/AppCompatShims/README.md
=> Protoss dev

Linux/Defense_Evasion/Clear_Command_History.md
Couple of other bash_history techniques
=> Defense evasion/clear_history

ARTifacts/Chain_Reactions/chain_reaction_Reactor.bat
Completion of the Reactor Chain Reaction
=> Final Reactor

ARTifacts/Detection/Reactor_detection.md
=> Reactor - Detection - Collection

Windows/Persistence/Scheduled_Task.md
Couple of additional inputs for testing remote task creation
=> Add_remote_task

ARTifacts/Chain_Reactions/chain_reaction_Cyclotron.bat, ARTifacts/Detection/Argonaut_detection.md, ARTifacts/Detection/Cyclotron_detection.md
Adding a few detections for some Chain Reactions.
=> ARTifacts - Detections

Linux/Exfiltration/Exfiltration_Over_Alternative_Protocol.md
Added a test to show exfil of data using a Python HTTP server one-liner
=> Added test to exfil data over HTTP

Windows/Execution/CMSTP.md, Windows/Payloads/CMSTP.inf, Windows/Payloads/CMSTP.sct, Windows/Persistence/Image_File_Execution_Options_Injection.md, Windows/Persistence/Registry_Run_Keys_Start_Folder.md
Added technique for CMSTP T1191 and for Image File Execution Injection T1183. Added another technique to Registry run keys T1060. 
Have not updated the Readme.md matrix page. I could not sort it out.
=> Created T1191 and T1183, added technique to T1060

Windows/Atomic_Red_Team.json, Windows/Privilege_Escalation/Process_Injection.md
Updated Navigator for Windows
also fixed a name on Process Injection
=> Updated ATT&CK Navigator

Windows/Execution/Windows_Management_Instrumentation.md, Windows/Payloads/squiblytwo/minimalist.xsl
Added SquiblyTwo wmic and minimalist payload
=> Squiblytwo

Windows/Persistence/Windows_Management_Instrumentation_Event_Subscription.md
Just updating the syntax on the $filtertoconsumerargs
Found this while updating some of our threatfeeds in CbR
=> minor syntax update

atomics/T1046/T1046.yaml, atomics/T1087/T1087.yaml, atomics/T1089/T1089.yaml, atomics/T1099/T1099.yaml, atomics/T1105/T1105.yaml, atomics/T1113/T1113.yaml, atomics/T1115/T1115.yaml, atomics/T1123/T1123.yaml, atomics/T1130/T1130.yaml, atomics/T1136/T1136.yaml, atomics/T1139/T1139.yaml, atomics/T1146/T1146.yaml, atomics/T1148/T1148.yaml, atomics/T1158/T1158.yaml, atomics/T1176/t1176.yaml
Convert most of the completed yamlized files to spec-validating format
=> Convert to spec-based format

.circleci/config.yml
Adds a continuous integration build that will validate atomic YAMLs according to the spec.
=> Add circle ci build

atomics/T1002/T1002.yaml, atomics/T1003/T1003.yaml, atomics/T1110/T1110.yaml
=> correct syntax for validator

atomics/T1033/T1033.yml
=> T1033 commit to yaml life

atomics/T1085/T1085.md, atomics/T1085/T1085.sct, atomics/T1085/T1085.yaml
Fix Command LIne to Call .Exec();
Added Payload.
=> Fix deadlink cs

README.md
Really, just took off /philosophy from https://atomicredteam.io
=> changed url to avoid 404

atomics/T1087/T1087.yaml
Added a few local user account/group enumeration techniques for both PowerShell and command_prompt.
=> T1087 - Local User/Group Enumeration Windows

atomics/T1136/T1136.yaml
Added functionality for PowerShell and command_prompt for adding new users.
=> Add test for Creating Account in Windows

atomics/T1028/T1028.yaml
Expanded remote PowerShell functions.
=> Added InvokeCommand to T1028

atomics/T1077/T1077.yaml
Added PowerShell mapped drive technique.
=> T1077 Added PowerShell Technique

atomics/T1065/T1065.yaml
Adding T1065 for testing uncommonly used ports.
=> T1065 added

atomics/T1081/T1081.yaml
Let me know if I need to add anything else!
=> T1081 Added notes about additional modules being needed for Mimikatz etc

atomics/T1083/T1083.yaml
Added techniques for PowerShell as well as Linux.
=> T1083 Added additional file system enumeration

atomics/T1158/T1158.yaml
Added command_prompt & PowerShell ADS creation and enumeration.
=> Added ADS creation and enumeration

atomics/T1135/T1135.yaml
Added share enumeration for both command_prompt and PowerShell.
=> Added Windows share enumeration.

atomics/T1201/T1201.md, atomics/T1201/T1201.yaml
Adding test for T1201 to discover password policy settings on Linux systems.
=> Commit test T1201 Password Policy Discovery

atomics/T1169/T1169.yaml
Added techniques for SUDO usage.
=> Added SUDO enumeration

atomics/T1046/T1046.yaml
Added additional port scanning techniques for Linux/MacOS.
=> T1046 Port Scans

atomics/T1214/T1214.yaml
Added T1214 to enumerate for passwords in the Registry.
=> T1214 Registry Enumeration

atomics/T1062/T1062.yaml
Added Hyper-V PowerShell commands.
=> Added T1062

atomics/T1049/T1049.yaml
Added T1049 System Network Connections Discovery
=> Added T1049 System Network Connections Discovery

atomics/T1126/T1126.yaml
Add command prompt and PowerShell functionality for removing network shares.
=> Add T1126 removing network shares

atomics/T1132/T1132.yaml
Added technique to post Base64 Encoded data.
=> T1132 Base64 Encoded Data

atomics/T1086/Invoke-DownloadCradle.ps1, atomics/T1086/T1086.md, atomics/T1086/T1086.yaml, atomics/T1086/payloads/mshta.sct, atomics/T1086/payloads/test.ps1, atomics/T1086/payloads/test.sct, atomics/T1086/payloads/test.xml, atomics/T1086/payloads/test.xsl, atomics/index.md, atomics/windows-index.md
Modified @mgreen27 Invoke-DownloadCradle to match Atomic Red Team.
An item I did not modify/change/delete was the nslookup test in the ps1 script. 
Everything else was converted to run out of the Atomic Red Team repo.
=> T1086 Powershell Additions

atomics/T1031/T1031.yaml
Added a test for T1031.
Tested on Windows 7 and Windows 10.
=> T1031 modifying a service

execution-frameworks/ruby/go-atomic.rb
This is a mostly complete execution framework written in Ruby. I'm submitting this PR because I know others have considered contributing execution frameworks in other languages, and I think this provides a good example implementation.
=> Example ruby execution framework

atomics/T1069/T1069.yaml
Added PowerShell and command_prompt techniques for group enumeration.
=> Added Windows Group Enumeration

.github/issue_template.md, .github/pull_request_template.md
**Details**:
Create issue and pull request templates to help improve information and streamline the process of contributing to Atomic Red Team.
**Testing**:
None needed. This is a metadata change.
=> Create issue and pull request templates.

atomics/T1042/T1042.md, atomics/T1042/T1042.yaml, atomics/T1053/T1053.md, atomics/T1053/T1053.yaml, atomics/T1065/T1065.md, atomics/T1065/T1065.yaml, atomics/T1075/T1075.md, atomics/T1075/T1075.yaml, atomics/T1103/T1103.md, atomics/T1103/T1103.yaml, atomics/T1124/T1124.md, atomics/T1124/T1124.yaml, atomics/T1191/T1191.md, atomics/T1191/T1191.yaml
**Details:**
Fixed all the issues per #317
=> Technique fixing

atomics/T1170/T1170.md, atomics/T1170/T1170.yaml
**Details:**
Corrected the command line execution string to properly parse and execute.
=> Fixed T1170 execution command

atomics/T1028/T1028.md, atomics/T1028/T1028.yaml, atomics/T1033/T1033.md, atomics/T1033/T1033.yaml, atomics/T1055/T1055.yaml, atomics/T1063/T1063.md, atomics/T1063/T1063.yaml, atomics/T1074/T1074.md, atomics/T1074/T1074.yaml, atomics/T1086/T1086.md, atomics/T1086/T1086.yaml, atomics/T1124/T1124.md, atomics/T1124/T1124.yaml
=> Power shell executor.command properties

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam.ps1, execution-frameworks/Invoke-AtomicRedTeam/README.md
**Details:**
Added PowerShell Execution Tool.
Parses and Executes Each Technique with a described test
=> Invoke atomic red team

atomics/T1060/T1060.yaml
**Details:**
Based on Issue #328 I added the deletion of Registry keys at the end of the tests.
**Testing:**
I tested this on a Windows 10 x64 VM only.
#328
=> Adding removal of registry keys for T1060 based on issue #328

atomics/T1191/T1191.yaml
need to pass the /s so this test runs without user interaction
**Details:**
Super minor syntax update
=> Minor update to cmstp.exe syntax

atomics/T1033/T1033.yaml
**Details:**
Fixed Type in T1033.yaml
**Testing:**
Nope.
=> Added '---'

atomics/T1180/T1180.yaml
**Details:**
Test to create a persistent process using screensaver settings.
**Testing:**
Tested on Windows 7
=> T1180 Screensaver

atomics/T1088/T1088.yaml
**Details:**
Created UAC Event Viewer Bypass test for T1088
**Testing:**
Tested on Windows 7
=> T1088 Bypass User Account Control (EventVwr Bypass)

atomics/T1055/T1055.md, atomics/T1055/T1055.yaml, atomics/T1055/src/T1055.cpp
**Details:**
Added Source Code for DLL to Inject, Updated Test to use full DLL Path
**Testing:**
Windows 10 PowerShell x86, x64
https://github.com/redcanaryco/atomic-red-team/issues/368
=> T1055 update

atomics/index.yaml, docs/_layouts/default.html, docs/assets/css/style.scss, docs/assets/javascripts/roll-the-dice.js, docs/roll-the-dice.md
This PR adds a page under the microsite at "/roll-the-dice" that allows you to select a random test from the catalog. 
Inspired by [Tim Malcomvetter](https://medium.com/@malcomvetter/red-team-use-of-mitre-att-ck-f9ceac6b3be2) and [Tim McG](https://www.twitter.com/NotMedic) and created for the Atomic Red Team ATT&CKcon presentation.
=> initial commit of roll the dice implementation

atomics/T1099/T1099.md, atomics/T1099/T1099.yaml, atomics/index.yaml
fixed T1099 input args
Fix for issue #393
=> Fixed T1099

atomics/T1087/T1087.md, atomics/T1087/T1087.yaml, atomics/index.md, atomics/index.yaml, atomics/linux-index.md, atomics/macos-index.md, atomics/windows-index.md
**Details:**
No new atomic tests were added. One test was broken into two.
**Testing:**
No additional testing performed, as no new tests were created. 
N/A
=> Clean up T1087 for consistency, platform accuracy

atomics/T1086/T1086.md, atomics/T1086/T1086.yaml, atomics/index.yaml
**Details:**
Corrected test #6 
**Testing:**
https://github.com/redcanaryco/atomic-red-team/issues/374
=> fix-executor

atomics/T1222/T1222.yaml
**Details:**
Added numerous tests for file permission modification on Windows, Linux, macOS
**Testing:**
Tested on Windows 10, macOS Mojave, and Fedora 29
=> T1222 File Permission Modification

atomics/T1197/T1197.yaml
**Details:**
Added ART test for BITS persistence using bitsadmin.exe. Also improved existing tests using variables for execution framework.
**Testing:**
=> T1197 Added test for persistence via BITS, improved test variables

atomics/T1088/T1088.yaml
**Details:**
Added tests for Fodhelper.exe UAC bypass and PoSH code for Fodhelper/EventVwr UAC bypasses.
**Testing:**
Tested in Windows 10
=> T1088 Fodhelper UAC Bypass and PoSH tests

atomics/T1009/T1009.yaml
**Details:**
Reorg'd T1009 binary padding test with variable
**Testing:**
No additional testing
=> T1009 Binary Padding reorg with variables

atomics/T1004/T1004.yaml
**Details:**
Added tests to define registry values for Winlogon Helper DLLs. Payloads not included.
**Testing:**
=> T1004 Winlogon Helper DLLs

atomics/T1010/T1010.yaml, atomics/T1010/src/T1010.cs
**Details:**
Test to compile C# and execute it for listing main application windows for running processes.
**Testing:**
Tested in Windows 10
=> T1010 App Window Discovery with C#

atomics/T1107/T1107.yaml
**Details:**
Updated T1107 tests with variables for execution frameworks
**Testing:**
No additional testing
=> T1107 File Deletion reorg with variables

atomics/T1107/T1107.yaml
**Details:**
Fixed a typo reported in an issue
**Testing:**
#419
=> T1107 Fix wbadmin test

atomics/T1174/T1174.yaml
**Details:**
PowerShell test to install and register a password filter DLL. Payload not included :smile: 
**Testing:**
=> T1174 Password Filter DLL PoSH test

atomics/T1002/T1002.yaml
**Details:**
Broke test out into individual ones with variables for execution frameworks
**Testing:**
No additional tests
=> T1002 - Reorganize tests for better execution with framework

atomics/T1101/T1101.md
**Details:**
Adding new test for T1101 - Security Support Provider
**Testing:**
Tested Powershell commands on:
* PS version 2 on Windows 7
* PS version 5.1 on Windows 10
n/a
=> adding SSP mod simulation

atomics/T1003/T1003.md, atomics/T1003/T1003.yaml, atomics/index.yaml
**Details:**
Simple update to the default_url property to reflect the correct version for Windows.
=> Update t1003 url

docs/invoke-atomic-red-team.md, execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AllAtomicTests.ps1, execution-frameworks/Invoke-AtomicRedTeam/README.md
**Details:**
* Added a new atomicredteam.io page (not on menu bar for now) that introduces how to get started with Invoke-AtomicRedTeam.
* Added new script that is loaded upon installation of Invoke-AtomicRedTeam to assist with execution and generating of Atomic Tests.
* Modified Invoke-AtomicRedTeam Readme.md file with latest updates of script and how to get started. 
**Testing:**
Confirmed operational on Win10
NA
=> ART - Getting Started Made Easy

ARTifacts/Chain_Reactions/chain_reaction_DragonsTail.bat, ARTifacts/Chain_Reactions/chain_reaction_DragonsTail.ps1
Updated URLs to fix #437
**Details:**
Fixed URLs for chain reaction. 
**Testing:**
Confirmed operational on Win10.
#437
=> DragonsTail - URL update

atomics/T1022/T1022.md, atomics/T1022/T1022.yaml, atomics/index.md, atomics/index.yaml, atomics/linux-index.md, atomics/macos-index.md, atomics/windows-index.md
Update schema and tab completion.
Credit to @samuelmarticotteBELL
Thanks for the help!
**Details:**
Added 3 additional Atomic Tests that utilize winzip, winrar and 7zip.
**Testing:**
Confirmed testing on Server 2016.
PR #351
=> T1022 Updates

docs/invoke-atomic-red-team.md, execution-frameworks/Invoke-AtomicRedTeam/README.md, execution-frameworks/Invoke-AtomicRedTeam/install-atomicredteam.ps1
**Details:**
Fixing a few more issues identified in code all over.
=> Install fixes

atomics/T1074/T1074.yaml, atomics/T1141/T1141.yaml
**Details:**
Resolved additional Duplicate YAML keys.
=> [FIX] T1074, T1141 Duplicate YAML Keys

atomics/T1485/T1485.yaml, atomics/T1496/T1496.yaml
**Details:**
Added data destruction test for macOS/Linux, added test for CPU load simulation on macOS/Linux to replicate cryptojacking
**Testing:**
Tested on macOS & Fedora 29
=> Tests for Data Destruction and Resource Hijacking

atomics/T1168/T1168.md
**Details:**
The formatting for T1168 did not properly render the code for method 3. 
**Testing:**
Viewed in markdown previewer
N/A
=> updated code formatting

atomics/T1112/T1112.md, atomics/T1112/T1112.yaml, atomics/index.yaml
**Details:**
Had a broken bracket in the code. Fixed it.
**Testing:**
=> T1112 bracket fix

execution-frameworks/Invoke-AtomicRedTeam/install-atomicredteam.ps1
I reverted https://github.com/redcanaryco/atomic-red-team/issues/478 for the moment. @caseysmithrc and I will update the script to remove the `atomic-red-team-master` path. This will at least get you up and running today.
Issue #516
**Details:**
**Testing:**
=> Install Atomic - Fixed Paths

atomic_red_team/atomic_doc_template.md.erb
Generated markdown was jumbled without this extra line break
=> markdown fix

atomics/T1003/T1003.yaml
There was a missing double quote and the original quotes where the bendy/angled/fancy ones which can be problematic so I swapped them out for the standard/straight forward/basic double quotes.
=> double quote fixes

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1
Invoker can specify input parameters on the command line as a hash table to over-ride the defaults in the yaml file.
=> allow caller to specify non-default input parameters

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Private/Write-ExecutionLog.ps1
Z indicates UTC so it should be on the local time stamp
=> remove Z from Local timestamp

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1
**Details:**
Added $Is[OS] checks, call >id -u to determine linux/MacOS priv level
**Testing:**
Works in Linux, need to test MacOS
=> Added MacOS and Linux isElevated check [todo: test MacOS]

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Private/Write-ExecutionLog.ps1
the execution log was logging the moth for the minute field. oops, sorry
=> log minutes correctly

atomics/T1531/T1531.yaml
**Details:**
Added tests for account manipulation and removal.
**Testing:**
Tested on Windows Server 2012
=> T1531 Account Access Removal Tests

atomics/T1085/T1085.md, atomics/T1085/T1085.yaml, atomics/index.md, atomics/index.yaml, atomics/windows-index.md
**Details:**
Test for executing vbscript via rundll32.exe. Documented by Hexacorn- http://www.hexacorn.com/blog/2019/10/29/rundll32-with-a-vbscript-protocol/
**Testing:**
Tested in Windows 10
=> T1085 Rundll32 vbscript execution test

atomics/T1218/T1218.md, atomics/T1218/T1218.yaml, atomics/index.md, atomics/index.yaml, atomics/windows-index.md
**Details:**
Added additional proxied binary execution tests
**Testing:**
Have not tested personally, adapted from the MITRE ATT&CK page.
no associated issues
=> T1218 proxied binary execution tests

execution-frameworks/Invoke-AtomicRedTeam/README.md
**Details:**
Fixes the installation URL to use GH resources.
=> Fixed URL for Install-AtomicRedTeam

atomics/T1170/T1170.hta, atomics/T1170/T1170.md, atomics/T1170/T1170.yaml, atomics/index.md, atomics/index.yaml, atomics/windows-index.md
**Details:**
T1170 MSHTA remote hta execution. This technique is used by numerous attacks we've seen in the last year.
**Testing:**
Tested on Win10
=> T1170 remote hta

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1, execution-frameworks/Invoke-AtomicRedTeam/README.md, execution-frameworks/Invoke-AtomicRedTeam/install-atomicredteam.ps1, execution-frameworks/README.md
**Details:**
Added `Bash` and `SH` executor compatibility
Added OS detection while determining tests to run
Made small changes to error reporting and messaging
Updated Installer to work in other Operating Systems
**Testing:**
Ubuntu 18.04
Windows 10 Powershell Version 5
Windows 10 Powershell Core
Mac OSx Mojave
https://github.com/redcanaryco/atomic-red-team/issues/607
=> Multi platform invoke art

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1
check prereqs with -showdetails was executing the prereq command instead of showing the details
=> Fix show details bug

execution-frameworks/Invoke-AtomicRedTeam/README.md
**Details:**
remove redundant section
=> remove development section, Carrie's new instructions cover it

atomics/T1036/T1036.yaml
**Details:**
Detect LSM running from an incorrect directory and an incorrect service account
This works by copying cmd.exe to a file, naming it lsm.exe, then copying a file to the C:\ folder.
**Testing:**
Windows 10 VM
None
=> T1036 malicious process masquerade as lsm

atomics/T1489/T1489.yaml
Also changed the default process for test 3 to spoolsv.exe because this exists by default on all machines.
=> Added cleanup commands for test 1 & 2

atomics/T1077/T1077.md, atomics/T1077/T1077.yaml, atomics/index.md, atomics/index.yaml, atomics/windows-index.md
**Details:**
Test to use PsExec for transfer and execution of files across Windows Admin Shares. Used by different groups including the one that distributes Ryuk.
**Testing:**
Tested on Win10
=> T1077 PsExec Test

atomics/T1085/T1085.md, atomics/T1085/T1085.yaml, atomics/index.yaml
Fixed broken url for test 1. woops.
=> Broken URL

atomics/T1055/T1055.yaml
grab the pid of spoolsv as default if no other pid is specified
=> default pid set to spoolsv

atomics/T1002/T1002.yaml
**Details:**
Updated T1002
No longer requires test specific directories
added prereq and cleanup commands
restricted some of the atomics to run within 5-10min
**Testing:**
Tested on linux and windows, have not tested MacOS
thanks @bmorgan-code  
N/A
=> Updated T1002

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1
=> show executor and privilege requirement

atomics/T1088/T1088.yaml
=> T1088 - Added UAC Bypass using ComputerDefaults.exe and cleanup commands to powershell tests

atomics/T1504/T1504.yaml
Adds a start-process cmdlet to current user's powershell profile that points to calc.exe
Opens a powershell window which in turn spawns calc.
=> T1504 powershell profile

atomics/T1023/T1023.yaml
**Details:**
Create LNK file to cmd in startup folders
**Testing:**
Windows 10 VM
=> T1023 LNK file to launch CMD placed in startup folders

atomics/T1105/T1105.md, atomics/T1105/T1105.yaml, atomics/index.md, atomics/index.yaml, atomics/windows-index.md
**Details:**
Test to download a file with PowerShell
**Testing:**
Tested on Win2012r2
none
=> T1105 PowerShell download test

atomics/T1064/T1064.md, atomics/T1064/T1064.yaml, atomics/index.md, atomics/index.yaml, atomics/windows-index.md
**Details:**
Adding test for creating a batch script and executing it. We've seen similar activity with post-exploitation frameworks.
**Testing:**
Tested on Win2012R2
=> Added T1064 Scripting test for Windows

atomics/T1018/T1018.md, atomics/T1018/T1018.yaml, atomics/index.md, atomics/index.yaml, atomics/linux-index.md, atomics/macos-index.md, atomics/windows-index.md
**Details:**
Test to discover domain controllers with nltest /dclist:
**Testing:**
Tested on Win2012r2
=> T1018 Test for DC discovery with nltest

atomics/T1047/T1047.md, atomics/T1047/T1047.yaml, atomics/index.md, atomics/index.yaml, atomics/windows-index.md
**Details:**
Tests for wmic.exe creating local and remote processes.
**Testing:**
Tested in Win2012r2
=> T1047 - Wmic process create tests

atomics/T1057/T1057.md, atomics/T1057/T1057.yaml, atomics/index.md, atomics/index.yaml, atomics/windows-index.md
**Details:**
Test to discover processes via tasklist.
**Testing:**
Tested on Win2012r2
=> T1057 Process discovery via tasklist

atomics/T1122/T1122.md, atomics/T1122/T1122.yaml
Removed relative path to src folder, added PathToAtomicsFolder
=> T1122 - Update to use PathToAtomicsFolder

atomics/T1482/T1482.yaml
**Details:**
Use PowerShell to enumerate AD information
**Testing:**
windows 10 VM
=> T1482 query ad/domain info

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Private/Write-ExecutionLog.ps1
**Details:**
Added hostname resolution to Write-ExecutionLog.ps1
**Testing:**
Works on Windows and Linux, no reason it shouldn't work in MacOS 
N/A
=> Added Hostname to ExecutionLog

atomics/T1016/T1016.yaml
Identify network configuration information as seen by Trickbot and described here https://www.sneakymonkey.net/2019/10/29/trickbot-analysis-part-ii/
=> recon trickbot style

atomics/T1088/T1088.yaml
**Details:**
Added cleanup commands to all atomic tests that required it.
**Testing:**
Manually tested on windows 10 VM.
=> T1088- Added cleanup commands

atomics/T1193/T1193.yaml
**Details:**
Fix path to word document
**Testing:**
Windows 10
=> Fix Path To Word Document in Test

atomics/T1074/T1074.yaml
**Details:**
Test was written previously for T1022 (encryption) and then moved here; T1022 already has very similar tests, but it is useful here so just reworded test 3, specifically to zip and staging.
**Testing:**
Not applicable
No issues
=> Updated atomic test 3 for better alignment with T1074 (Staging)

atomics/T1003/T1003.yaml
@clr2of8 
Laken said you were working on some code that would solve some of the dependency issues, so I didn't try to install python, pypykatz etc in the commands.  I figured I'd revisit these tests when everything is figured out and add code for the dependencies.
=> pypykatz registry and LSASS tests

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Private/Invoke-ExecuteCommand.ps1
don't throw error when cleanup commands are null
=> check for null commands

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1
**Details:**
$TestName no longer exists. Changed to $Test.name
**Testing:**
=> Fixed ExecutionLog TestName field

atomics/T1004/T1004.yaml
**Details:**
Added cleanup commands to remove keys created during execution
**Testing:**
Win10 no major change to atomic
=> T1004 cleanup commands

atomics/T1007/T1007.yaml
**Details:**
Del output_file
**Testing:**
=> added cleanup_command

atomics/T1010/T1010.yaml
**Details:**
dependencies check for the existence of and retrieves T1010.cs from master branch of ART
cleanup_command removes the source code file and output file
**Testing:**
Win10
=> added dependencies and cleanup

atomics/T1087/T1087.md, atomics/T1087/T1087.yaml, atomics/index.md, atomics/index.yaml, atomics/linux-index.md, atomics/macos-index.md
**Details:**
`s/logger/logged/g`
**Testing:**
None. 
=> Fix typo in test name

atomics/T1003/T1003.yaml
@clr2of8 thanks for your help in getting this working
=> Pypykatz add dependency

atomics/T1105/T1105.yaml
**Details:**
changed executor name to powershell
changed local_path to destination_path to $env:TEMP
Added cleanup_command to remove file
**Testing:**
Windows10
N/A
=> T1105-Update 

atomics/T1002/T1002.yaml, atomics/T1004/T1004.yaml, atomics/T1007/T1007.yaml, atomics/T1010/T1010.yaml, atomics/T1023/T1023.yaml
**Details:**
Added fix for powershell/CMD error output from invokeing cleanup for t1002-t1023
**Testing:**
tested on local machine
=> remove errors from t1002-t1023

atomics/T1081/T1081.yaml, atomics/T1216/T1216.yaml
Typo in T1216 test 2 and T1081 test 3
=> Fixed typo 1216 1081

atomics/T1168/T1168.md, atomics/T1168/src/atomicredteam.plist
**Details:**
Before this change, the XML file in Atomic Test 3, step one was not properly rendered. Also step one was in bold text when it shouldn't have been.
**Testing:**
Just used the github preview.
none
=> Correct markdown formatting for test #3

atomics/T1204/T1204.yaml
**Details:**
replaced `:` with `is`
**Testing:**
NA
N/A
=> T1204 - fixed md file parsing issue

atomics/T1204/T1204.yaml
**Details:**
pipe/carriage return issue while creating md file.
=> T1204-markdown file fix take 2

atomics/T1204/T1204.yaml
**Details:**
added T1204-2 Maldoc choice flags command execution
Macro runs cmd.exe /c choice /C Y /N /D Y /T 3
**Testing:**
windows 10 office 16.0
=> T1204-2 Choice flags command execution

atomics/T1204/T1204.yaml
**Details:**
Malicious JavaScript executing CMD which spaws wscript.exe //e:jscript
**Testing:**
windows 10
=> T1024 ostap js version

atomics/T1060/T1060.yaml
fixed "PowerShell Registry RunOnce" cleanup command by adding extra input argument for reg key.
=> T1060 - Test 3 minor fix

atomics/T1028/T1028.yaml
**Details:**
t-1028_Update - fixed test 4 to use the intended args require sysinternal
**Testing:**
windows 10
=> t-1028_Update

atomics/T1003/T1003.yaml
**Details:**
Add test 2 prereqs for T1003 that performs Credential Dumping
**Testing:**
Tested on Windows 10 (10.0.14393)
None
=> Add test 2 prereqs for T1003 that performs Credential Dumping

atomics/T1121/T1121.yaml
**Details:**
T1121 test 2 cleanup command 
**Testing:**
windows 10
=> T1121-2_Update

atomics/T1083/T1083.yaml
Test names should be unique within a given OS
=> unique test names for OS

atomics/T1218/T1218.yaml
**Details:**
T1218-5_Updatefix - update URL for test 5 and added result action for test 4 and 5
**Testing:**
Windows 10
=> T1218-5_Updatefix

atomics/T1027/T1027.yaml, atomics/T1036/T1036.yaml, atomics/T1096/T1096.yaml, atomics/T1112/T1112.yaml, atomics/T1170/T1170.yaml, atomics/T1202/T1202.yaml
**Details:**
Completion descriptions and fixes
**Testing:**
Windows 10 VM
=> Add completion description and fixes 2nd batch

atomics/T1027/T1027.yaml, atomics/T1037/T1037.yaml, atomics/T1060/T1060.yaml, atomics/T1085/T1085.yaml, atomics/T1086/T1086.yaml, atomics/T1087/T1087.yaml, atomics/T1135/T1135.yaml, atomics/T1218/T1218.yaml
**Details:**
Add test success descriptions
**Testing:**
Windows 10 VM
=> Success Descriptions 3rd Batch

atomics/T1219/T1219.yaml
**Details:**
Update description with expected results when running the test
**Testing:**
windows 10
=> T1219_Update

atomics/T1055/T1055.yaml, atomics/T1218/T1218.yaml
**Details:**
Fix description, remove broken test
**Testing:**
Windows 10
=> Fix description, remove broken test

atomics/T1063/T1063.yaml
**Details:**
Added success indicator for tests  and fixed part of test1
**Testing:**
Invoke-AtomicTest T1063 -TestNumbers 1 up to 5 
N/A
=> updated success indicatior on tests and fixed part of test1

atomics/T1028/T1028.md, atomics/T1028/T1028.yaml, atomics/T1032/T1032.md, atomics/T1032/T1032.yaml
T1028 Test#2 should run with powershell.
T1032 Test1 missing quoters.
**Details:**
T1028 Test#2 run with cmd will get error.
**Testing:**
=> Fix T1028 T1032 tests issue.

atomics/T1208/T1208.yaml
**Details:**
changed the way to get to Invoke-kerberoast script and updated success indication.
**Testing:**
Invoke-AtomicTest t1208 -TestNumbers 1
=> T1208 documentation

atomics/T1220/T1220.yaml
**Details:**
T1220_Update with test 3 and 4 fix and description update on all test
**Testing:**
windows 10
=> T1220_Update

atomics/T1489/T1489.yaml
**Details:**
Update test descriptions with information about successful execution
**Testing:**
Windows 10 VM
=> T1489 Update Test Descriptions

atomics/T1490/T1490.yaml
**Details:**
Improved test descriptions. Some of these tests only work on windows server or windows 8
**Testing:**
Windows 10 VM
=> fix tests, update descriptions

atomics/T1119/T1119.yaml
**Details:**
Improve test descriptions and cleanup commands
**Testing:**
Windows 10 VM
=> T1119 Test Completion Description Updates w/ Other Fixes

atomics/T1124/T1124.yaml, atomics/T1136/T1136.yaml, atomics/T1138/T1138.yaml
**Details:**
Update descriptions to verify test executed correctly
**Testing:**
Windows 10 VM
=> Update Successful Completion Descriptions

atomics/T1037/T1037.yaml, atomics/T1069/T1069.yaml
**Details:**
Update descriptions with how to verify the test successfully completed
**Testing:**
Windows 10 VM
=> Update completion descriptions

atomics/T1121/T1121.yaml, atomics/T1158/T1158.yaml
**Details:**
T1121 and T1158 success description updates and fixes
**Testing:**
Windows 10 VM
=> T1121 and T1158 success description updates and fixes

atomics/T1099/T1099.yaml, atomics/T1117/T1117.yaml
**Details:**
Fix tests and add success descriptions. For T1099, all of the windows tests are very similar. I'd like some input on if these should be combined or separate. I left them separate that way each test only changes one thing so people can be certain they were detecting what they wanted, but open to opinions.
**Testing:**
windows 10 VM
=> T1099 description updates

atomics/T1074/T1074.yaml, atomics/T1083/T1083.yaml, atomics/T1084/T1084.yaml, atomics/T1085/T1085.yaml
**Details:**
Update success descriptions and other fixes
**Testing:**
Windows 10 VM
=> T1074, T1083, T1084, T1085 updates

atomics/T1502/T1502.yaml, atomics/T1504/T1504.yaml, atomics/T1518/T1518.yaml, atomics/T1529/T1529.yaml, atomics/T1531/T1531.yaml
**Details:**
Update successful execution descriptions and other fixes
**Testing:**
Windows 10 VM
=> T1502, T1504, T1518, T1529, T1531 updates

execution-frameworks/ruby/go-atomic.rb
`List all accounts` doesn't exist; replaced the test with an existing one.
**Details:**
The ruby script shows banner of a test that doesn't exist. Replaced the test with an existing one.
**Testing:**
Not necessary. Just replaced a string value.
None
=> Fix go-atomic.rb example method

atomics/T1502/T1502.yaml
Changed types from string to path.
=> Fix type (string -> path) in T1502

atomics/T1076/T1076.yaml
**Details:**
Update T1076 test 1 with args.
**Testing:**
windows 10
=> T1076_Update

atomics/T1095/T1095.yaml
Fix typo "powerShell" -> "powershell"
=> Fix: powerShell -> powershell

ARTifacts/Atomic_Friday/README.md
**Details:**
Adds a path to store Atomic Friday . . . things.
**Testing:**
N/A
N/A
=> Create Atomic Friday holding pen

ARTifacts/Atomic_Friday/Notes_05012020_InvokeAtomicRedTeam/Atomic-Friday.md, ARTifacts/Atomic_Friday/Notes_05012020_InvokeAtomicRedTeam/BuildAtomicTest_ps1, ARTifacts/Atomic_Friday/Notes_05012020_InvokeAtomicRedTeam/Getting Lateral.md
=> Atomic Friday Notes - 05012020

atomics/T1016/T1016.yaml, atomics/T1018/T1018.yaml, atomics/T1022/T1022.yaml, atomics/T1030/T1030.yaml, atomics/T1046/T1046.yaml, atomics/T1049/T1049.yaml, atomics/T1069/T1069.yaml, atomics/T1074/T1074.yaml, atomics/T1082/T1082.yaml, atomics/T1083/T1083.yaml, atomics/T1087/T1087.yaml, atomics/T1089/T1089.yaml, atomics/T1113/T1113.yaml, atomics/T1130/T1130.yaml, atomics/T1201/T1201.yaml, atomics/T1217/T1217.yaml
**Details:**
Added dependencies and fixed tests for linux and macOS for the following techniques: 
T1016, T1018, T1022, T1030, T1046, T1049, T1069, T1074, T1082, T1083, T1087, T1089, T1113, T1130, T1201, T1217.
**Testing:**
Tested in macOS an Ubuntu 19.10.
None
=> Added dependencies and fixed tests for linux and macOS

atomics/T1176/T1176.yaml
**Details:**
Added manual download, install, and cleanup for an Edge Chromium VPN extension.
**Testing:**
Have not found a way to automate, kept this manual like previous atomics for 1176.
=> Update T1176 with Edge Chromium Addon - VPN

atomics/T1217/T1217.yaml
**Details:**
Edited Chrome Bookmarks atomic to include Edge Chromium as it already does so. Also added one for FireFox bookmark database.
=> Edited & Updated T1217

atomics/T1027/T1027.yaml
**Details:**
Created test 4 "Execution from Compressed File" to mimic execution of compressed executable
**Testing:**
Windows 10
=> T1027 4 update

atomics/Indexes/Indexes-CSV/index.csv, atomics/Indexes/Indexes-CSV/windows-index.csv, atomics/Indexes/Indexes-Markdown/index.md, atomics/Indexes/Indexes-Markdown/windows-index.md, atomics/Indexes/index.yaml, atomics/T1003/T1003.md, atomics/T1003/T1003.yaml
**Details:**
The following test brings in recent MITRE ATTACK Eval T1003  - Collecting Chrome Passwords. 
[Step 6.A](https://github.com/mitre-attack/attack-arsenal/tree/66650cebd33b9a1e180f7b31261da1789cdceb66/adversary_emulation/APT29/Emulation_Plan/Day%201#6a), Test [ID](https://github.com/mitre-attack/attack-arsenal/blob/66650cebd33b9a1e180f7b31261da1789cdceb66/adversary_emulation/APT29/CALDERA_DIY/evals/data/abilities/credential-access/e7cab9bb-3e3a-4d93-99cc-3593c1dc8c6d.yml)
**Testing:**
Confirmed operational on Windows 10. 
=> T1003 pwcollector

atomics/T1055/T1055.yaml, atomics/T1105/T1105.yaml
**Details:**
Move test to T1105, which is Remote File Copy 
**Testing:**
Windows 10 VM
=> Move svchost writing a file to a UNC path to T1105

atomics/T1069/T1069.yaml
**Details:**
Download and run Find-LocalAdminAccess from PowerView.ps1 script.
**Testing:**
Windows 10 VM
=> T1069 - Find machines where user has local admin access (PowerView)

docs/index.md
**Details:**
Fixed the broken link at the bottom of the page " Ready to start testing? [Get started!](https://github.com/redcanaryco/atomic-red-team/blob/master/testing)"
**Testing:**
Not applicable
None
=> Fixing broken link

.gitignore, atomic_red_team/attack_api.rb
fix the auto-generated indexes and navigator layers to work with subtechniques
=> Gendocs fix

atomics/T1053.003/T1053.003.yaml, atomics/T1053.004/T1053.004.yaml
this is just to check the circle CI build docs process which is oddly failing after merge
=> spacing change

atomics/T1551.001/T1551.001.yaml
**Details:**
Minor wording fix
**Testing:**
N/A
None
=> T1551.001: minor wording fix

atomics/T1197/T1197.yaml
**Details:**
This test needed a cleanup command. Same one as test #1
**Testing:**
N/A
None
=> T1197: add cleanup command to test 3

atomics/T1547.001/T1547.001.yaml
**Details:**
Small spelling error
**Testing:**
None
None
**Potential regression:**
If people mentioned those tests using the current name with the mistake
=> T1547.001: small typo "supicious" -> "suspicious"

docs/testing.md
Due to 5d7ea5c11514b96804f7f1fe7825ccc04185686f
=> Fix broken link

atomics/T1110.003/T1110.003.yaml, atomics/T1110.003/src/parse_net_users.bat
Tested on a Windows domain, from Windows 10.
=> Add Password spray atomic to T1110.003

atomics/T1562.004/T1562.004.yaml
**Details:**
This test opens a port on the firewall 
**Testing:**
C:\windows\system32>netsh advfirewall firewall add rule name="atomic testing" action=allow dir=in  protocol=TCP localport=450
Ok.
=> added test for opening ports on firewall for proxy - T1562.004

atomics/Indexes/Indexes-CSV/index.csv, atomics/Indexes/Indexes-CSV/windows-index.csv, atomics/Indexes/Indexes-Markdown/index.md, atomics/Indexes/Indexes-Markdown/windows-index.md, atomics/Indexes/index.yaml, atomics/T1003.003/T1003.003.md, atomics/T1003.003/T1003.003.yaml
**Details:**
I closed my previous already approved PR because of merging problems and created the a clean new PR.
**Testing:**
testing was performed with the Attack Range
no
=> new atomics for T1003.003

.github/ISSUE_TEMPLATES/feature_request.md, .github/ISSUE_TEMPLATES/problem_report.md, .github/ISSUE_TEMPLATES/website_change.md
**Details:**
This implements simple issue templates for features, problems, and changes to the website. 
**Testing:**
I read them very carefully :)
Closes https://github.com/redcanaryco/atomic-red-team/issues/1111.
=> Create issue templates 

.github/ISSUE_TEMPLATE/idea.md, .github/ISSUE_TEMPLATE/problem_report.md, .github/ISSUE_TEMPLATE/website_change.md
**Details:**
Improves issue templates for ideas, problems, and the website by adding issue title prefixes.
**Testing:**
Basic testing via UI.
Makes progress on, but does not complete, https://github.com/redcanaryco/atomic-red-team/issues/1111.
=> Improve issue templates via title prefixes

atomics/T1021.001/T1021.001.yaml
**Details:**
Duplicate of PR #1106. I created a new one to solve the merging problems. Please close the PR #1106 after merging this one. based on our last discussions. I had to change a little bit the ENV variable code of the old version because it was not working.
**Testing:**
see PR #1106
-
=> Atomics change t1021 001 atc

atomics/T1218.010/T1218.010.yaml
**Details:**
Registers a dll that has been renamed to some alternate extension.
Observed in Gozi maldoc behavior
**Testing:**
Window 10
=> added T1218.010 test 4

atomics/T1040/T1040.yaml
Uses the built-in Windows packet capture
**Details:**
Using netsh
**Testing:**
Did it locally using start-atomicgui and Invoke-AtomicTest T1040 -ShowDetails 
NA
=> Update T1040.yaml Use Built-in Windows Packet capture

atomic_red_team/atomic_doc_template.md.erb
markdown fix to address issue #1177
=> fix markdown spacing after description

atomics/T1176/T1176.yaml, atomics/T1562.003/T1562.003.yaml
updated three atomics that had blank descriptions.
=> adding missing descriptions

atomics/T1071.001/T1071.001.yaml
**Details:**
Added prereq to test number 2
Install path is default to windows 10.
=> added prereq to test #2

atomics/Indexes/index.yaml, atomics/T1216/T1216.md, atomics/T1216/T1216.yaml
=> include full path to manage-bde.wsf

atomics/T1497.001/T1497.001.yaml
**Details:**
Added tests for T1497.001 - Virtualization/Sandbox Evasion: System Checks
**Testing:**
Done locally on Windows, CentOS, Ubuntu and MacOS machines. 
None
**References**
1. https://attack.mitre.org/techniques/T1497/001/
2. https://evasions.checkpoint.com/techniques/macos.html
3. https://unit42.paloaltonetworks.com/unit42-oilrig-targets-middle-eastern-government-adds-evasion-techniques-oopsie/
=> [OSCD] Tests added for T1497.001

atomics/T1222.001/T1222.001.yaml
Adding a new test that will invoke the command that Ryuk ransomware uses.
**Details:**
Creating a new test that will invoke the code that Ryuk ransomware is currently using.
**Testing:**
Testing is done when the Atomic Test 1222.001 #4 is invoked.
=> Adding New Test

atomics/T1202/T1202.yaml
**Details:**
conhost command line execution
**Testing:**
Works successfully in newer win10 versions
None observed
=> [OSCD]Indirect command execution - conhost

bin/generate-atomic-docs.rb
More descriptive Mitre ATT&CK Navigator names.
=> Update Layer Names

bin/generate-atomic-docs.rb
Adds technique highlighting when a sub-technique has an atomic written for it.
=> Fix Technique Highlighting

atomics/T1553.001/T1553.001.yaml, atomics/T1562.001/T1562.001.yaml
**Details:**
- add Gatekeeper disable test
- add cleanup for security tools disable test
- add another launchagent for carbon black defense
- remove Gatekeeper disable command from Gatekeeper bypass test
**Testing:**
Tested on local machine
None
=> [OSCD] updated a few tests

atomics/Indexes/Indexes-CSV/index.csv, atomics/Indexes/Indexes-CSV/windows-index.csv, atomics/Indexes/Indexes-Markdown/index.md, atomics/Indexes/Indexes-Markdown/windows-index.md, atomics/Indexes/index.yaml, atomics/T1112/T1112.md, atomics/T1112/T1112.yaml
**Details:**
New Atomic for T1112 which sets the default execution policy of powershell to Bypass
**Testing:**
Tested with Attack Range
-
=> new atomic T1112

atomics/T1016/T1016.yaml, atomics/T1016/src/qakbot.bat
**Details:**
Added an atomic to run recon commands believed to be associated with Qakbot reconnaissance techniques.
https://hybrid-analysis.com/sample/fcdfd33bebc7a7fe02854ecb60aa17bf0bd85d0b78cc5bc07ceb93a5116639cd/5f63d0b54f389a2d7573a8ce
https://www.virustotal.com/gui/file/fcdfd33bebc7a7fe02854ecb60aa17bf0bd85d0b78cc5bc07ceb93a5116639cd/detection
**Testing:**
Windows 10 1903
=> T1016 qakbot addition

atomics/T1222.001/T1222.001.yaml
**Details:**
New atomic for T1222.001. Hide files with attrib.exe
**Testing:**
Tested with Attack Range
-
=> New atomics t1222 001

atomics/T1548.002/T1548.002.yaml
**Details:**
new atomic for T1548.002 which disable UAC using its registry keys
**Testing:**
tested with Attack Range
-
=> atomic for disable UAC

atomics/T1546.008/T1546.008.yaml
**Details:**
new atomic for sticky key binary reaplacement with cmd.exe
**Testing:**
tested with attack range
-
=> new atomic for T1546.008

atomics/T1574.011/T1574.011.yaml
**Details:**
developed a new atomic for T1574.011
**Testing:**
-
=> New atomic t1574 011

atomics/T1204.002/T1204.002.yaml
=> fix display name

atomics/T1546.001/T1546.001.yaml
**Details:**
fixed cleanup command to use input arg intead of static value
**Testing:**
windows 10
none
=> T1546.001 update

atomics/T1574.002/T1574.002.yaml
=> update gup.exe download link

atomics/T1049/T1049.yaml
**Details:**
sharpview - https://github.com/tevora-threat/SharpView
**Testing:**
window 10
=> T1049 update

atomics/T1207/T1207.yaml
**Details:**
An automated test is better than manual steps :)
**Testing:**
None
=> T1207: automate test for DCShadow

atomics/T1055/T1055.yaml
**Details:**
New test variant for process injection. Injections in LSASS are very specific and might trigger specific detection use cases
**Testing:**
None
=> T1055: add new test "Remote Process Injection in LSASS via mimikatz"

atomics/T1003.006/T1003.006.yaml
**Details:**
Create test for DCSync technique
**Testing:**
None
=> T1003.006: add DCSync test

atomics/T1207/T1207.yaml
**Details:**
It gives more choice in what to change instead of fixed "badpwdcount" and "9999"
Also rename "user" to "object" as it is more generic than only user objects
Sorry for not thinking about this and including it directly in the prior recent PR :)
**Testing:**
Tested locally
None
=> Add DCShadow args for attribute and value

atomic_red_team/attack_api.rb
**Details:**
this improved some scripts by as much as  90% in performance
**Testing:**
data generated was the same.
none
=>  add caching of techniques. performance improvement. also add some spaces into curly brackets because rubocop

atomics/T1563.002/T1563.002.yaml
**Details:**
Quick link fix for T1563.002
**Associated PR:**
https://github.com/redcanaryco/atomic-red-team/pull/1390
(hopefully this was the most helpful way to submit this change, still getting used to contributing on GH)
=> Fix broken link in T1563.002

atomics/T1550.002/T1550.002.yaml
Thank you @aky1286 and Issue #1400
=> add quotes to fix command execution

atomics/T1564/T1564.yaml
**Details:**
create a user called "$"and create an "Administrator " user (with a space on the end)
**Testing:**
Windows 10
none
=> t1564-update

atomics/T1113/T1113.yaml
=> fix for install and check

atomics/T1562.001/T1562.001.yaml
**Details:**
Added cleanup commands to test 3. Added elevation required
**Testing:**
Fedora 34
=> Update T1562.001 Test 3

atomic_red_team/atomic_test_template.yaml
**Details:**
Updates copy for more consistency and improved capitalization and punctuation. 
For example, a lower-case `todo` is updated to a capitalized `TODO`. 
**Testing:**
This makes validation tests more accurate, since the validation [is looking for](https://github.com/redcanaryco/atomic-red-team/blob/master/atomic_red_team/atomic_red_team.rb#L237) capitalized `TODO` only. 
None.
=> Improve template for validation (and grammar)

atomics/T1548.002/T1548.002.yaml, atomics/T1548.002/src/T1548.002.bat
**Details:**
Bypass UAC using SilentCleanup taskon Windows 8-10 using bat file
**Testing:**
windows 10
=> T1548.002-Update

atomics/T1027/T1027.yaml
=> corrections as per  BoBoSiKi008

atomic_red_team/atomic_doc_template.md.erb, bin/generate-atomic-docs.rb
**Details:**
Modifies `atomic_doc_template.md.erb` to add auto generated guid to each test. 
**Testing:**
Ran `bin/generate-atomic-docs.rb` locally and verified that the guid was indeed placed correctly under the test name in the generated md files. 
https://github.com/redcanaryco/atomic-red-team/issues/1501
=> adding auto generated guids to the md files

atomics/T1486/T1486.yaml
**Details:**
Atomic for the PureLocker ransomware note IOC
**Testing:**
Windows 10
=> T1486-update

README.md
**Details:**
Added a link to request invite to make it more obvious.
**Testing:**
N/A
N/A
=> Add "Request Invite" next to Slack Link

atomics/T1056.001/T1056.001.yaml
**Details:**
Moved `prereq_command` and `get_prereq_command` under dependencies to conform to other tests
**Testing:**
=> T1056.001 - Updating dependencies

atomics/T1543.004/T1543.004.yaml
**Details:**
Fixed key name of `cleanup` to `cleanup_command`
**Testing:**
=> T1543.004 - Updated cleanup key

atomics/T1105/T1105.yaml
**Details:**
Use PowerShell to download and write an arbitrary file from the internet. 
**Testing:**
Tested with Windows 10, no escalation. (see attached)
N/A
=> Additional PowerShell Download in T1105

atomics/T1003.002/T1003.002.yaml
=> dump shadow hive w/ certutil

atomics/T1482/T1482.yaml
**Details:**
Two simple Atomic Tests for domain and forest trust information.
**Testing:**
Confirmed operational on Server 2016.
=> Trust Reconnaissance

atomics/T1219/T1219.yaml
**Details:**
ScreenConnect application 
**Testing:**
windows 10
=> Added ScreenConnect application

atomics/T1069.001/T1069.001.yaml
Added two new tests for localgroup discovery. 
Tested on server 2016 with success.
=> Local group discovery

atomics/T1548.002/T1548.002.yaml
**Details:**
Added (11) tests from UACMe to 1548.002 .yaml file
**Testing:**
Testing done in lab environment successfully.
=> Updated T1548.002.yaml file

atomics/T1016/T1016.yaml, atomics/T1018/T1018.yaml, atomics/T1040/T1040.yaml, atomics/T1046/T1046.yaml, atomics/T1070.003/T1070.003.yaml, atomics/T1135/T1135.yaml, atomics/T1486/T1486.yaml, atomics/T1560.001/T1560.001.yaml, atomics/T1562.001/T1562.001.yaml
**Details:**
Updates to prereq_command and get_prereq_command for multiple linux tests to improve automated use.
**Testing:**
Manual local testing.
N/A
=> Linux prereq updates

atomics/T1087.001/T1087.001.yaml
=> typo fixes per issue 1683

atomics/T1135/T1135.yaml
**Details:**
PowerView ShareFinder finds (non-standard) shares on hosts in the local domain. 
=> T1135 Powerview

atomics/T1048.002/T1048.002.yaml
**Details:**
get no test on windows
So make change (thanks to T1105.yml)
**Testing:**
Not test on linux or macos no change make
=> Fix T1048.002 windows test

atomics/T1547.002/T1547.002.yaml
**Details:**
before:
after:
ref: https://pentestlab.blog/2019/10/21/persistence-security-support-provider/
=> fix reg in T1547.002

atomics/T1588.002/T1588.002.yaml
Validated works on Server 2016.
=> NIRSoft AdvancedRun

atomics/T1047/T1047.yaml
=> Application uninstall using WMIC

atomics/T1555.003/T1555.003.yaml
**Details:**
Steal firefox user profile information
https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data
Add check x64 or x86 version.
use the en-US (Can put the French one 😄 )
**Testing:**
Windows 10 X64 
None
=> Add T1555.003 firefox profile

CODE_OF_CONDUCT.md
deleting a word from the title
**Details:**
**Testing:**
=> Taking out the work covenant

atomics/T1555.003/T1555.003.yaml
**Details:**
Just add Edge profile test
fix firefox missing `-Recurse` and `-ErrorAction Ignore`
**Testing:**
Edge is a part of windows so `-GetPrereqs` is not usefull
=> T1555.003 edge

atomics/T1003.006/T1003.006.yaml
Confirmed operational on Server 2016.
Two screenshots to show beginning and mid.
=> DSInternals - Get-ADReplAccount

atomics/T1059.004/T1059.004.yaml
revert uuid change from this PR : https://github.com/redcanaryco/atomic-red-team/pull/1766/files
=> reverting uuid

atomics/T1564.006/T1564.006.yaml
**Details:**
Add T1564.006 use ragnar commandline
[Sigma rule](https://github.com/SigmaHQ/sigma/blob/b1cd48c82883d13c42fb97025462dcc5a7ca5968/rules/windows/process_creation/win_run_virtualbox.yml)
**Testing:**
Virtualbox install in background but 1er time get `Failed to meet prereq: Old version of Virtualbox must be installe` anyway
If run many time get
```
Done executing test: T1564.006-1 Register Portable Virtualbox
[SC] CreateService ‚chec(s) 1073 :
Le service sp‚cifi‚ existe d‚j….
[SC] StartService ‚chec(s) 1056 :
Une instance du service s'ex‚cute d‚j….
```
Need a reboot after cleanup
=> Add T1564.006 Virtualbox

atomics/T1562.001/T1562.001.yaml
Atomic to disable Windows Defender Tamper Protection
=> Add Tamper Protection Atomic

atomics/T1003.002/T1003.002.yaml
**Details:**
Moved web request to pre req command , got rid of set-execution policy
**Testing:**
Windows 10
=> T1003.002 #4, Powerdump Improvement

atomics/T1562.001/T1562.001.yaml
Deleting test 'Disable Windows Defender Tamper Protection'
**Details:**
**Testing:**
=> Deleting test (TamperData)

atomics/T1014/T1014.yaml
Updated prereq commands update after a user raised this issue on slack
=> Update the prereq commands for T1014-1,2 tests

atomics/T1014/src/Linux/T1014.c
=> Added module license to the T1014.c

.github/workflows/validate-atomics.yml
fixes current failing errors
**Details:**
fixes a syntax error that caused failures like https://github.com/redcanaryco/atomic-red-team/actions/runs/2186722406
**Testing:**
current CI tests are running now: https://github.com/redcanaryco/atomic-red-team/actions
=> minor updates to ci

.github/workflows/generate-docs.yml
**Details:**
fixes this https://github.com/redcanaryco/atomic-red-team/actions/runs/2190470155
**Testing:**
=> minor_ci_fix

atomics/T1574.006/T1574.006.yaml
**Details:**
Fixed a missing brace in a variable usage
**Testing:**
None
None
=> a quick fix for a non-conformant variable

.github/workflows/generate-docs.yml
=> removing persistence of creds

.github/workflows/generate-docs.yml
**Details:**
enabling force push
**Testing:**
=> force push

.github/workflows/generate-docs.yml
=> updating to use secrets

README.md
=> updating the badge

.github/workflows/validate-atomics.yml
**Details:**
seeing if this fixes hung validate jobs
**Testing:**
=> minor adjustment to how workflows are triggered

atomics/T1218.011/T1218.011.yaml
Add Rundll32 with desk.cpl
**Details:**
Very simple LOLBAS: https://lolbas-project.github.io/lolbas/Libraries/Desk/
**Testing:**
Win 10 and 11
=> Add Rundll32 with desk.cpl

atomics/T1087.002/T1087.002.yaml
**Details:**
Replace invalid char
**Testing:**
close #1913
=> Fix all invalid char

atomics/T1204.002/T1204.002.yaml
**Details:**
This lnk files invokes powershell to download putty from the internet and opens the file.
=> Add LNK Atomic

atomics/T1552.001/T1552.001.yaml
**Details:**
https://github.com/S3cur3Th1sSh1t/WinPwn/
**Testing:**
Tested on Windows 10 VM
=> T1552.001 - Adding Credential Discovery Atomics sourced from WinPwn Script

atomics/T1046/T1046.yaml
Details:
https://github.com/S3cur3Th1sSh1t/WinPwn/
Testing:
Tested on Windows 10 VM
**Details:**
**Testing:**
=> T1046 - Added Service Scanning tests sourced from WinPwn script.

atomics/T1555.003/T1555.003.yaml
**Details**
https://github.com/S3cur3Th1sSh1t/WinPwn/
**Testing**
Tested on Windows 10 VM
=> T1555.003 - Added BrowserPwn test sourced from WinPwn script.

atomics/T1564.002/T1564.002.yaml
Confirmed operational on Server 2016
=> Use SpecialAccounts to Hide User on Windows

atomics/T1592.001/T1592.001.md, atomics/T1592.001/T1592.001.yml
**Details:**
enumerate camera mounted to the device
**Testing:**
tested manually
https://www.mandiant.com/resources/analyzing-dark-crystal-rat-backdoor
=> Windows camera info gathering

atomics/T1105/T1105.yaml, atomics/T1105/src/T1105-download-file.vbs
**Details:**
Added to test to T1105 based on open issue
**Testing:**
Tested on test environment on Windows 10
#1596
=> New T1105 test based on open issue

atomics/T1059.006/T1059.006.yaml
**Details:**
Update the description for this test to remote ATT&CK technique documentation. 
**Testing:**
None
N/A
=> Update t1059 006

atomics/T1530/T1530.yaml, atomics/T1530/src/policy.json
**Details:**
Added a test to scan for Anonymous Access to AWS S3 
**Testing:**
Tested in local machine(macOS)
=> T1530: Anonymous Access to AWS S3

atomics/T1053.005/T1053.005.yaml, atomics/T1082/T1082.yaml, atomics/T1105/T1105.yaml, atomics/T1105/src/atomic.sh, atomics/T1115/T1115.yaml
Some basic Atomics for Linux and a new Atomic that modifies a scheduled task action.
This is a cool atomic because the premise is, an adversary will modify an already scheduled task "action" to run something else. This generates a different eventcode in Microsoft-windows-taskscheduler/operational event log (2nd screenshot)
=> Linux and Windows

atomics/T1547.015/T1547.015.yaml, atomics/T1547.015/src/settings.json
**Details:**
Modify Windows Terminal settings.json file to gain persistence. [Twitter Post](https://twitter.com/nas_bench/status/1550836225652686848)
**Testing:**
Windows 10
=> T1547.015 Added

atomics/T1105/T1105.yaml
**Details:**
- Missing dependency_executor_name
- prereq_command was hardcoded
- Expand-Archive failed if folder exist
**Testing:**
Windows 10 x64
=> T1105Fix prereg test nimgrab

atomics/T1546.008/T1546.008.yaml
accidently deleted in pr #2134
=> restoring deleted file

atomics/T1219/T1219.yaml
doing this to avoid issues like #2101
=> Use IWR instead of bits transfer

atomics/T1016/T1016.yaml
**Details:**
Added T1016 Test 7 prereq
**Testing:**
Windows 10
=> T1016_Update

atomics/T1546.003/T1546.003.yaml
**Details:**
add prereq for Test 3
**Testing:**
=> T1546.003_Update

atomics/T1053.005/T1053.005.yaml
**Details:**
added input args and prereq to  test 6 and 8
**Testing:**
windows 10
=> T1053.005_update

atomics/T1055.004/T1055.004.yaml
**Details:**
T1055.004 Test 1 Prereq
**Testing:**
Windows 10
=> T1055.004_Update

atomics/T1082/T1082.yaml
**Details:**
Update test 9 with prereq commands
**Testing:**
windows 10
=> T1082_update

atomics/T1218.005/T1218.005.yaml
Details:
- Using sleep command to run the application for 15 seconds with start process
- The process has been terminated using stop process command
Testing:
-Test running successfully in the atomic environment
=> Mshta Executes Remote HTML Application (HTA)  - Process Termination

atomics/T1105/T1105.yaml
**Details:**
Create prereq for test 20, 23, and 26
**Testing:**
Windows 10
none
=> T1105_update

atomics/T1106/T1106.yaml
**Details:**
Create prereq for test 1 
**Testing:**
windows 10
none
=> T1106_update

atomics/T1491.001/T1491.001.yaml
**Details:**
Separated reference URLs in description section with commas ','
**Testing:**
Minor edits to description of atomic test 2, no need of testing.
=> Minor edits to test number 2

atomics/T1553.005/T1553.005.yaml
Updated testNumber 4. The LNK was not launching. 
Thank you @burning-pm for the assist!
=> Update T1553.005 - Runs lnk now

bin/generate-atomic-docs.rb
This should update the Navigator layers from ATT&CK 11 to 12 and from Navigator 4.5.5 to 4.7.1
**Details:**
**Testing:**
=> Updating ATT&CK and Navigator

atomics/T1505.004/T1505.004.yaml, atomics/T1562.002/T1562.002.yaml
The following two Atomics are related to IIS Components. The Atomics will install a IIS module either via AppCmd.exe or PowerShell Cmdlet `New-WebGlobalModule`.
-Testnumber 1
-Testnumber 2
Disable HTTP logging - PwSh
=> T1505.004 - IIS Components & T1562.002 - Disable HTTP logging

atomics/T1053.005/T1053.005.yaml
=> fix cleanup key

atomics/T1059.007/T1059.007.yml, atomics/T1059.007/src/sys_info.js
**Details:**
Adding tests for executing JScript via wscript and cscript
**Testing:**
Tested the script on Windows 10
=> T1059.007 JScript Tests

atomics/T1218.011/T1218.011.yaml
=> Fix sigma rule link

atomics/T1552.004/T1552.004.yaml
Added 3 new tests that export certificates using 
- certutil.exe -exportPFC
- PowerShell Export-PFXcertificate
- PowerShell Export-Certificate
=> Export Certificates

bin/generate-atomic-docs.rb
**Details:**
Fixing index file names by removing colon and replacing with underscore
**Testing:**
None.
None.
=> fix: Fixing index file names by removing colon and replacing with underscore

atomics/T1048/T1048.yaml, atomics/T1059.006/T1059.006.yaml
**Details:**
Updating format of T1059.006 and T1048
**Testing:**
Local validation but CI should verify
=> fix: Updating format of 2 yaml defintions for new schema

atomics/T1543.001/T1543.001.md, atomics/T1543.001/T1543.001.yaml
**Details:**
Test 2 referenced old technique number/path causing the test to fail
**Testing:**
Test failed with existing path. Test works with updated path.
=> Fix T1543.001 Test 2 Defaults

atomics/T1112/T1112.yaml
fix typo
**Details:**
T1112: fix typo
**Testing:**
N/A
=> T1112: fix typo

atomics/T1569.002/T1569.002.yaml
New atomic test for RemCom.exe
=> Added RemCom to execute a command on a remote host

atomics/T1112/T1112.yaml
**Details:**
Added new technique "Enabling Remote Desktop Protocol via Remote Registry". 
References : https://twitter.com/Alh4zr3d/status/1640369018061336577
**Testing:**
N/A
N/A
=> Added new test - Enabling Remote Desktop Protocol via Remote Registry (T1112)

atomics/T1562.001/T1562.001.yaml
=> correct registry value

bin/validate/validate.py
**Details:**
CI Validation shows only one of the errors right now on error. This bug fix would show all the possible errors on why a validation failed.
**Testing:**
Tested locally on my machine
=> (bugfix) CI validation fix

.github/workflows/assign-labels.yml, .github/workflows/validate-atomics.yml, bin/generate_labels.py, poetry.lock, pyproject.toml
**Details:**
This PR would auto assign labels and PR based on the atomics file being added.
**Testing:**
Tested on [cyberbuff/atomic-red-team](https://github.com/cyberbuff/atomic-red-team/pull/7)
None
=>  (enhancement) Auto assign labels and reviewers 

atomics/T1087.002/T1087.002.yaml
**Testing:**
Tested it on Windows VM
=> Adding atomics to emulate suspicious LAPS attribute queries

atomics/T1003.001/T1003.001.yaml, atomics/T1003.006/T1003.006.yaml, atomics/T1014/T1014.yaml, atomics/T1016/T1016.md, atomics/T1018/T1018.md, atomics/T1018/T1018.yaml, atomics/T1027.004/T1027.004.yaml, atomics/T1027.006/T1027.006.yaml, atomics/T1027/T1027.yaml, atomics/T1039/T1039.yaml, atomics/T1046/T1046.yaml, atomics/T1047/T1047.yaml, atomics/T1048.003/T1048.003.yaml, atomics/T1048/T1048.yaml
Looking over the YAMLs mostly, only changes for readability or accuracy
=> YAML spelling adjustments

atomics/T1021.001/T1021.001.yaml, atomics/T1059.001/T1059.001.yaml, atomics/T1112/T1112.yaml, atomics/T1547.010/T1547.010.yaml, atomics/T1574.011/T1574.011.yaml
**Details:**
When the value exist test with reg.exe failed
**Testing:**
ref: https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/reg-add
Find with 
`grep -ri reg --include="*.yaml" | grep add | grep -v "/f"` 
None
=> Add reg.exe force swith

atomics/T1562.006/T1562.006.yaml
**Details:**
Technique was not found and did not works
Correct one : 
- https://www.cisa.gov/news-events/cybersecurity-advisories/aa23-075a
- https://minerva-labs.com/blog/lockbit-3-0-aka-lockbit-black-is-here-with-a-new-icon-new-ransom-note-new-wallpaper-but-less-evasiveness/
**Testing:**
#2089 allready closed
=> T1562.006 Fix test 6 and 7

atomics/T1490/T1490.yaml
**Details:**
Adding new atomic Test for Windows - vssadmin Resize Shadowstorage Volume
**Testing:**
Performed the Testing Atomic Lab
=> Prakash22 k patch 1

atomics/T1572/T1572.yaml
Addresses issue #2487 Thank you @zaicurity
=> use start-job

atomics/T1560.001/T1560.001.yaml
**Details:**
for demo, edited description
=> Modified description for Test 4

README.md, atomics/T1112/T1112.yaml
**Details:**
a registry modification to allow simultaneous download in a targeted host. seen being used by Ave malware (WARZONE) RAT
**Testing:**
tested manually 
=> Tccontre max connection per server

atomics/T1218/T1218.yaml
=> Customshellhost

atomics/T1055/T1055.yaml
removing invalid guid. a new one will be automatically assigned by github actions
mpacts or fixes. -->
=> remove invalid guid

atomics/T1016/T1016.yaml
=> handle spaces in file path

atomics/T1003.001/T1003.001.yaml, atomics/T1083/T1083.yaml
=> fixed some path errors

atomics/T1112/T1112.yaml
**Details:**
Modify Internet Zone Protocol Defaults in Current User Registry through powershell
**Testing:**
Successfully compiled
=> Modify Internet Zone Protocol Defaults in Current User Registry - powershell

atomics/T1218/T1218.yaml
**Details:**
Provlaunch.exe Executes Arbitrary Command via Registry Key
**Testing:**
Compiled and executed successfully
=> Provlaunch.exe Executes Arbitrary Command via Registry Key

atomics/T1555.003/T1555.003.md, atomics/T1555.003/T1555.003.yaml
**Details:**
Removed extra quotes around normal commands
**Testing:**
=> Fix check dependency command

atomics/T1071.004/T1071.004.yaml
xip.io is no longer functional as a dns resolver
=> xip.io to nip.io

atomics/T1048.002/T1048.002.yaml
=> fix prereqs

atomics/T1562.010/T1562.010.yaml
Small change to remove an improperly formatted extra field
=> Remove improper extra field from T1562.010.yaml

atomics/T1218/T1218.yaml
**Details:**
Msedge proxy execution
**Testing:**
=> Msedge proxy execution

atomics/T1040/T1040.yaml
Powershell Cmdlets to capture network traffic.
=> Mikoyan dee patch 1

atomics/T1059.001/T1059.001.yaml
This URL has been blocked by Bitly's systems as potentially harmful.
=> remove atomic w/broken blocked link

atomics/T1110.001/T1110.001.yaml, atomics/T1560.001/T1560.001.yaml, atomics/T1562.004/T1562.004.yaml
**Details:**
The Github Actions pipeline fails because the GUID check fails for these 3 GUIDs. Removing them so they can be auto generated again
**Testing:**
Tested locally
=> Fix Github Actions

atomics/T1040/T1040.yaml
Link is broken Might be a typo :-https://1.eu.dl.wireshark.org/win64/Wireshark-win64-latest.exe
Correct Link :-https://1.eu.dl.wireshark.org/win64/Wireshark-latest-x64.exe
**Details:**
**Testing:**
=> Update T1040.yaml Link was broken

atomics/T1218.011/T1218.011.yaml
**Details:**
It just seems the YAML file schema is broken. I indented the last test.
**Testing:**
Did a local test with my parser.
None. Just [this](https://github.com/redcanaryco/atomic-red-team/commit/a5e3460d41ac6442a14f6745d33278207b2761b5) commit
=> Fix f3ad3c5b-1db1-45c1-81bf-d3370ebab6c8 schema in T1218.011.yaml

atomics/T1204.002/T1204.002.yaml
=> fix undefined filename

atomics/T1001.002/T1001.002.yaml, atomics/T1055.011/T1055.011.yaml, atomics/T1059.006/T1059.006.yaml, atomics/T1072/T1072.yaml, atomics/T1201/T1201.yaml, atomics/T1202/T1202.yaml, atomics/T1218.011/T1218.011.yaml, atomics/T1486/T1486.yaml, atomics/T1562.001/T1562.001.yaml, atomics/T1562.008/T1562.008.yaml, atomics/T1571/T1571.yaml, atomics/T1580/T1580.yaml, atomics/T1619/T1619.yaml, atomics/T1652/T1652.yaml
**Details:**
syntax cleanup - empty "dependencies:" entries seem to have been breaking downstream build processes.  reparented lists of dependencies while I was in there.
=> fix nesting and remove empty entries

atomics/T1486/T1486.yaml
**Details:**
Added an atomic for dropping 100 files with .akira ending and random content, as well dropping the akira ransomnote
**Testing:**
tested on win10 device, with local modified yaml file, including removing the artifacts
-
=> Update T1486.yaml - adding atomic for akira encrypted files and ransomnote

atomics/T1070.003/T1070.003.yaml
**Details:**
This PR includes a new test to simulate the `Clear-History` technique. The test shows how attackers erase command history to cover their tracks.
**Testing:**
Validated by running `Clear-History` in PowerShell. The command history was successfully erased, as verified by attempting to access it post-test.
=> New Atomic - Clear PowerShell Session History

atomics/T1003.002/T1003.002.yaml, atomics/T1046/T1046.yaml, atomics/T1078.003/T1078.003.yaml, atomics/T1082/T1082.yaml, atomics/T1087.002/T1087.002.yaml, atomics/T1110.003/T1110.003.yaml, atomics/T1120/T1120.yaml, atomics/T1135/T1135.yaml, atomics/T1518/T1518.yaml, atomics/T1548.002/T1548.002.yaml, atomics/T1552.001/T1552.001.yaml, atomics/T1555.003/T1555.003.yaml, atomics/T1555/T1555.yaml, atomics/T1558.003/T1558.003.yaml, atomics/T1562.001/T1562.001.yaml, atomics/T1615/T1615.yaml, atomics/T1620/T1620.yaml
**Details:**
The variable `$S3cur3Th1sSh1t_repo` is not used. Hence removing it from the tests.
=> Remove unused variable

atomics/T1553.005/T1553.005.yaml
these commands require elevated privs
=> add elevation required

atomics/T1564.004/T1564.004.yaml
**Details:**
Fixed grammar and spelling issues in T1564.004 and removed trailing whitespaces.
**Testing:**
=> Fix: small grammar/spelling errors in T1564.004
