redcanaryco/atomic-red-team

Mac/Persistence/Local_Job_Scheduling.md

emond is another method for scheduling tasks in macOS.
Example runs a 'say' command on startup but could be modified to do anything under various conditions.
requires root :)

Mac persistence -  emond

---

atomics/t1046/t1046.yaml
atomics/t1087/t1087.yaml
atomics/t1089/t1089.yaml
atomics/t1099/t1099.yaml
atomics/t1105/t1105.yaml
atomics/t1123/t1123.yaml
atomics/t1130/t1130.yaml
atomics/t1136/t1136.yaml
atomics/t1139/t1139.yaml
atomics/t1146/t1146.yaml
atomics/t1148/t1148.yaml
atomics/t1158/t1158.yaml
atomics/t1176/t1176.yaml
validate_atomics.rb

This PR brings all existing atomics in line with the updated spec that allows a single executor and renames `args` from the draft to `input_arguments`.
```
atomic-red-team bb$ ./validate_atomics.rb 
Validating ./atomics/t1046/t1046.yaml...OK
Validating ./atomics/t1087/t1087.yaml...OK
Validating ./atomics/t1089/t1089.yaml...OK
Validating ./atomics/t1099/t1099.yaml...OK
Validating ./atomics/t1105/t1105.yaml...OK
Validating ./atomics/t1123/t1123.yaml...OK
Validating ./atomics/t1130/t1130.yaml...OK
Validating ./atomics/t1136/t1136.yaml...OK
Validating ./atomics/t1139/t1139.yaml...OK
Validating ./atomics/t1146/t1146.yaml...OK
Validating ./atomics/t1148/t1148.yaml...OK
Validating ./atomics/t1158/t1158.yaml...OK
Validating ./atomics/t1176/t1176.yaml...OK
```

bring all existing atomics in line with spec

---

README.md

Just removed a "/" at the end of the link which was throwing a 404 upon clicking the link.

Readme - Contribution link fixed

---

atomics/RC13378/RC13378.yaml

Adding a test for a contribution submission to MITRE ATT&CK Framework, hopefully it gets added. Covers the creation of Linux Systemd service unit file creation for persistence.

Systemd Service Creation Test

---

atomics/T1165/T1165.yaml
atomics/T1165/T1165_emond.plist

Based on xorrior's research: https://posts.specterops.io/leveraging-emond-on-macos-for-persistence-a040a2785124
This test will use the macOS command `say` to speak a greeting from Atomic Red Team test T1165.

Added T1165 Startup Items emond rules test

---

README.md

Fix quick start link and add a link for Slack invitations

Fix Quick Start and add a Slack Invite link

---

atomics/T1191/T1191.yaml
atomics/T1191/T1191_uacbypass.inf

T1191.yaml fixed with correct content for UAC Bypass via invocation of command in RunPreSetupCommandsSection of INF.

T1191 uacbypass

---

execution-frameworks/ruby/.gitignore
execution-frameworks/ruby/go-atomic.rb

**Details:**
The original `go-atomic.rb` execution framework creates output filenames in the format:
`atomic-test-executor-execution-2018-08-29T20:55:26Z.yaml` 
While this format is valid on most POSIX systems, it's invalid to use a `:` in a filename on Windows. The `:` is used to denote an alternate data stream for NTFS in Windows (NT variants).
This change replaces `:` for `.` when we generate the filename in `go-atomic.rb`. Output files now take the form:
`atomic-test-executor-execution-2018-08-30T18.56.12Z.yaml`
**Testing:**
Changes were tested on macOS with JRuby 9 and system Ruby 2.4. On Windows, the changes were tested with MRI Ruby 2.4.4.
This addresses #313.

Fix filenames created by ruby execution framework (go-atomic.rb)

---

atomics/T1117/T1117.yaml

**Details:**
Fix path of `RegSvr32.sct` because `RegSvr32.sct` is not locate in the `T1117\bin` folder.
**Testing:**
local testing on win7. 
N/A

T1117: Fix path of RegSvr32.sct

---

atomics/T1127/T1127.md
atomics/T1127/T1127.yaml
atomics/T1127/src/msxsl-script.xsl
atomics/T1127/src/msxsl-xmlfile.xml
atomics/index.md
atomics/windows-index.md

**Details:**
Added MSXSL bypass test for existing Trusted Dev Utilities tests
**Testing:**
Manual testing on Win 7 performed. Validated via bin/validate-atomics.rb.
No associated issues (that I know of)

MSXSL Bypass Test (T1127 Trusted Dev Utilities)

---

docs/_layouts/default.html
docs/related.md

**Details:**
Adds a Related page to atomicredteam.io, so that we can maintain a list of projects that are directly related to Atomic Red Team but not housed here.
**Testing:**
No testing. YOLO.
N/A

Add a Related section to reference other works

---

atomics/T1036/T1036.yaml
atomics/T1306/T1306.yaml

**Details:**
Reopened PR because the first one bugged out. Tests for T1306 Masquerading as authorized processes.
**Testing:**
Tested on Fedora 28 and Windows 7
Resolves #312

T1036 Masquerading

---

atomics/T1063/T1063.yaml

**Details:**
Added test to discover Sysmon installation no matter the name using the altitude value of its filter driver (thanks to @darkoperator)
**Testing:**
Tested on Windows 7

T1063 Discovery of Sysmon using fltmc.exe

---

atomics/T1089/T1089.yaml

**Details:**
Added test to unload Sysmon filter driver without stopping Sysmon service (Thanks to @darkoperator)
**Testing:**
Tested on Windows 7

T1089 Added test to unload Sysmon filter driver

---

atomics/T1086/T1086.yaml

**Details:**
Added test to execute PowerShell payload from the Windows Registry in the same manner as a fileless malware execution.
**Testing:**
Tested on Windows 7 but seemed a little finicky. Wouldn't hurt to have an additional test if someone has a spare VM.

T1086 Fileless PowerShell from Registry

---

atomics/T1003/T1003.yaml

**Details:**
Added tests to:
- Demonstrate lsass.exe memory dumping via ProcDump and Task Manager
- Demonstrate offline credential theft using Mimikatz and a memory dump
- Demonstrate NTDS.dit dumping via NTDSUtil
**Testing:**
Tested on Windows 7 and Server 2012 R2 (domain controller)

T1003 Added credential dumping tests

---

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Get-AtomicTechnique.ps1
execution-frameworks/Invoke-AtomicRedTeam/README.md

This addresses issue 
[373](https://github.com/redcanaryco/atomic-red-team/issues/373)
Moved the Write-Debug Into the BEGIN{} block . By floating it was not properly interpreted.

Fixed Bug in Get-Atomic

---

atomics/T1145/T1145.yaml

**Details:**
Added tests to copy SSH private keys to staging area using cp and rsync for Linux/macOS
**Testing:**
Tested on Fedora 28

T1145 Copy SSH keys using cp/rsync

---

atomics/T1145/T1145.yaml

**Details:**
Added test to discover SSH private keys by common names
**Testing:**
Tested on Fedora 28

T1145 discover SSH keys

---

atomics/T1042/T1042.yaml

**Details:**
Added the missing `/c` flag from `cmd.exe`, which caused the `assoc` command to be skipped.
**Testing:**
As an additional sanity check, ran with `whoami` instead.
```console
C:\Users\vagrant>cmd whoami
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
C:\Users\vagrant>exit
C:\Users\vagrant>cmd /c whoami
endpoint-w-4-04\vagrant
```
None

Update T1042 with cmd /c argument

---

atomics/T1156/T1156.yaml

**Details:**
Reorg'd T1156 test into separate tests for .bash_profile and .bashrc each. Added documentation for clarity.
**Testing:**
No additional testing

T1156 .bash_profile .bashrc reorg into separate tests

---

atomics/T1007/T1007.yaml

**Details:**
Added test to enumerate system services started using net.exe start and writing to file (used by multiple threat actors).
**Testing:**
Tested on Windows 2012 R2

T1007 Service Discovery Net Start to File

---

atomics/T1166/T1166.yaml

**Details:**
Added SetUID and SetGID tests with variables for execution
**Testing:**
Tested on Fedora 29

T1166 SetUID SetGID add tests with variables

---

atomics/T1099/T1099.md
atomics/T1099/T1099.yaml

**Details:**
Added timestomp with `touch` test where a reference file is specified to source the timestamps. This technique was observed in use by the Rocke threat actor on Linux systems.
**Testing:**
Tested on CentOS 7.

T1099 Timestomp test with Rocke example

---

atomics/T1222/T1222.md
atomics/T1222/T1222.yaml

**Details:**
T1222 test using `chattr` to remove the immutable file attribute. This was used by the threat actor Rocke during the compromise of Linux web servers.
**Testing:**
Tested on CentOS 7

T1222 - chattr Remove Immutable Attribute

---

execution-frameworks/Invoke-AtomicRedTeam/README.md
execution-frameworks/Invoke-AtomicRedTeam/install-atomicredteam.ps1

**Details:**
This is a simple installation script to help teams get started with Atomic Red Team. 
* Downloads and extract AtomicRedTeam Repo
* Installs Dependencies (powershell-yaml)
* Set focus to execution path
Two input parameters:
* DownloadPath
* InstallPath
Feedback welcome
**Testing:**
Confirmed operational on Windows 10. 
None we are aware of.

Install-AtomicRedTeam Script

---

atomics/T1074/Discovery.sh
atomics/T1074/T1074.md
atomics/T1074/T1074.yaml
atomics/T1114/Get-Inbox.ps1
atomics/T1114/T1114.md
atomics/T1114/T1114.yaml

**Details:**
Added a basic discovery.sh script, to simulate gathering host information on an OSX or Linux system. Provided one method of downloading and executing a shell script from a remote server.
**Testing:**
This has been tested on OSX 10.13.6 and Ubuntu 18.04.1.
N/A

T1074 update for OSX and Linux

---

atomics/T1105/T1105.yaml
atomics/T1140/T1140.yaml

**Details:**
Syntax fix + adding `certutil` download tests.
**Testing:**
Tested commands on Windows 10 - certutil should be cross-compatable down to Win 7.
None known.

Certutil update

---

atomics/T1114/Get-Inbox.ps1
atomics/T1114/T1114.md
atomics/T1114/T1114.yaml

**Details:**
This test simulates an attacker extracting email data from the currently logged in user's Microsoft Outlook instance. This data can be displayed in the terminal, or extracted to a file for later exfiltration. In a real scenario, the script could be improved to include search functionality and attachment extraction.
**Testing:**
This has been tested on a Windows 10 installation with Microsoft Outlook installed and configured.
N/A

Add test for T1114 that extracts emails from Microsoft Outlook

---

atomics/T1086/T1086.md
atomics/T1086/T1086.yaml
atomics/index.yaml

Modified the URL to point to sharphound. 
The second url was a misplaced parameter. Removed.
Fixes issue #465

BloodHound URLs - T1086

---

execution-frameworks/contrib/python/requirements.txt

**Details:**
Update PyYAML to >= 4.2b1 due to security alert: https://nvd.nist.gov/vuln/detail/CVE-2017-18342.
This simply updates PyYAML to 4.2b1 or greater.
**Testing:**
Script was tested locally.
Fixes the CVE referenced her: https://github.com/redcanaryco/atomic-red-team/network/alert/execution-frameworks/contrib/python/requirements.txt/pyyaml/open

Update PyYAML to >= 4.2b1 due to security alert: https://nvd.nist.gov/vuln/detail/CVE-2017-18342

---

atomics/T1114/T1114.md

The Get-Inbox.ps1 is not in the ARTifacts directory, it is in the directory for this technique
**Details:**
**Testing:**

Correct URL for DownloadString

---

docs/contributing.md

I was looking at your contribution guide and found that the link to spec.yaml does not work. Fixed that.
It also appears that the link on https://atomicredteam.io/contributing -page does not work either.

Fix docs/contributing.md pointing to non-existent spec.yaml

---

docs/contributing.md

**Details:**
The contributing page contains URLs that references files in the repository, which are not parsed relative to /docs. These are currently broken, and have been for some time as reported in #484. 
**Testing:**
Not able to test locally. 
#484

Fix repository URLs

---

atomics/T1048/T1048.md
atomics/T1048/T1048.yaml

**Details:**
Add test to T1048 to exfiltrate data over ICMP. Implemented with powershell. By default sends C:\Windows\System32\notepad.exe to IP address 1.1.1.1 via ICMP.
**Testing:**
Tested with Windows 10 x64 (1809) and a destination was linux server. PCAP was captured on the windows host and sanitized (mac + ip(s)). After that the data was filtered to show only echo requests (icmp.type == 8) as otherwise you'd get duplicate data. Data field was extracted from ICMP request packets by using tshark and converted back to binary format.
Verified sha256sum of extracted and original file and they do indeed match.
Steps to reproduce:
1. Download attached pcap and extract it.
2. tshark -r T1048.pcap -T fields -e data | tr -d '\n' > notepad.data
3. xxd -r -p notepad.data notepad.exe
**Associated …

Add ICMP exfiltration test to T1048

---

atomics/T1127/T1127.csproj

**Details:**
Based on the details in the blog below on a non-working test.  Adjusted the location of T1127.csproj. Leaving in both places for now, in case teams have adapted tests to overcome the nuance.
**Testing:**
Windows 10 x64
This blog was a good reference.
https://bleepsec.com/2018/11/26/using-attack-atomic-red-team-part1.html

msbuild expects the csproj file in the same path

---

atomics/T1087/T1087.yaml

**Details:**
Fixed issue where a test was missing a `-name:` key, and was "piggybacking" off another test and causing a conflict of duplicate keys.

[FIX] T1087

---

atomics/T1105/T1105.yaml

**Details:**
Added T1105 Remote File Copy test using BITS via BITSAdmin.exe. This technique is used by Qbot malware during infection.
**Testing:**

T1105 Remote File Copy BITSAdmin

---

atomics/T1138/T1138.md
atomics/T1138/T1138.yaml
atomics/index.yaml

**Details:**
Updated relative path, to be a variable and default to the full path of base atomic install.
**Testing:**
Windows 10 x64

Fix t1138path

---

.gitignore
execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam.psm1
execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1
execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Write-ExecutionLog.ps1
execution-frameworks/Invoke-AtomicRedTeam/README.md

Each test that is executed is written to a log file by default as shown below. This is useful for comparing what tests where run to what tests were detected, in an automated fashion.
By default, test execution details are written to `Invoke-AtomicTest-ExecutionLog.csv` in the current directory. Use the `-ExecutionLogPath` parameter to write to a different file. Nothing is logged in the execution log when only running pre-requisite checks with `-CheckPrereqs` or cleanup commands with `-Cleanup`. Use the `-NoExecutionLog` switch to not write execution details to disk.

Write test execution details to log file

---

atomic_red_team/atomic_doc_template.md.erb

Step 1 was showing up on the header line in the markdown for manual tests

markdown fix for manual tests

---

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1
execution-frameworks/Invoke-AtomicRedTeam/README.md

If the user specifies the -CheckPrereqs switch from an un-elevated context and the test requires elevation (based on the elevation_required attribute in the yaml file) the Pre-req will be reported as not met.
You can still invoke the test regardless of whether it meets the pre-reqs but just be aware that the attack steps likely won't complete.

fail pre-req check if elevation required but not provided

---

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1

if statement was working wrong because it needed parenthesis. This resulted in a null references error when running prereq checks on a test with no prereqs defined.

bug fix for order of operations

---

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1

Execution of test wasn't being logged if the test was defined with input parameters. This fixes that.

fix bug where no log output for tests with input parameters

---

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1

Using the -Cleanup and -ShowDetails switches together resulted in a null reference error for tests that did not include cleanup commands in their definition.

fix null error when using -Cleanup and -ShowDetails

---

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1
execution-frameworks/Invoke-AtomicRedTeam/README.md

InputArgs more closely matches the yaml test definition name of input_arguments

rename InputParameters to InputArgs

---

atomics/T1038/T1038.yaml

Committing an AMSI bypass / DLL search order hijacking test.
**Details:**
A simple atomic test that allows a defender to build detections on a broad AMSI bypass that involves amsi.dll loading from a non-standard path. amsi.dll should only ever be loaded from System32, SysWow64, or winsxs.
**Testing:**
Ran this test via `Invoke-AtomicRedTeam` execution tool within the repo.
None

Create DLL Hijacking Test - amsi bypass

---

atomics/T1107/T1107.yaml

**Details:**  Adding a new atomic for support on 1107, Delete a single prefetch file.  Deletion of prefetch files is a known anti-forensic technique.  An earlier version of this was drafted by Carrie Roberts (@clr2of8 )
**Testing:**  Atomic was tested with success by another jb on Windows 10, powershell with elevated privileges.
**Associated Issues:**  No known issues

Added test for deletion of prefetch files (anti-forensic technique)

---

atomics/T1112/T1112.yaml

**Details:**
Added new atomic, 'Modify registry for password downgrade to plain text.'  An earlier version of this was drafted by Carrie Roberts (@clr2of8 ).  Test sets a registry key that will tell windows to store plaintext passwords (making the system vulnerable to clear text / cleartext password dumping) which are easily retrievable and usable by an adversary. 
**Testing:**
Original version was tested by Carrie and this atomic was tested by a different jb, and re-written and published by cherokeejb_
No known issues

Added new atomic, 'Modify registry for password downgrade to plain text'

---

atomics/T1089/T1089.yaml

Adding in a cleanup to set the amsiInitFails variable back to false
**Details:**
Cleanup the amsiInitFailed test
**Testing:**
Tested with Invoke-AtomicTest
None

Update T1089 - AMSI Bypass cleanup

---

atomics/T1069/T1069.yaml

sa`w**Details:**
Added a new atomic (test 4), and updated the test 2 name to more clearly reflect what it is doing versus the newly added atomic (which has commands more specific to high value, elevated groups, and as well simple obfuscation).  The new test mimics an adversary attempting to enumerate groups in Windows.  The attacker runs the 'net group' command (4 examples were included here to simulate enumeration/discovery of high value domain groups).  This test could be easily customized or added-to.  An earlier version of this test 4 was drafted by Carrie Roberts (@clr2of8 ).  @Andras32 helped review her test and a similar test for net user. 
**Testing:**
Carrie tested her original draft; this test 4 is simply the typing of the net user command; I've checked the syntax, and @Andras32 …

Added 'Elevated group enumeration using net group' + minor titles edit

---

atomics/T1089/T1089.yaml

With administrative rights, an adversary can remove the AMSI Provider registry key in HKLM\Software\Microsoft\AMSI to disable AMSI inspection.
This test removes the Windows Defender provider registry key.
**Details:**
Disable AMSI provider via reg key removal
**Testing:**
Ran with Invoke-AtomicTest
None

Update T1089 - AMSI Bypass

---

atomics/T1081/T1081.yaml
atomics/T1201/T1201.yaml

**Details:**
Fix a bug in T1081 where the macos version of grep is wrongly expected to accept the -P flag and fix a labeling bug in T1201 where a macOS command is wrongly described as a Windows command
**Testing:**
I made the changes locally and was still able to successfully use the YAML files in question
N/A

Fix a macOS vs Linux and fix a description bug

---

atomics/T1112/T1112.yaml

**Details:**
After further thought & discussion; suggesting a more precise name for atomic 4 (originally pulled here by me).  Changing to "Modify registry to store logon credentials," and removing the former word "downgrade."  The registry modification in this test does not actually enable a "downgrade," rather it allows the storage of auto-login credentials overall; they are resultingly stored as text, but that is not a downgrade
**Testing:**
no testing required (only name change)
**Associated Issues:** 
none

T1112 atomic 4 name clarification

---

atomics/T1018/T1018.yaml

**Details:**
Added test 6:  Powershell script that runs nslookup on cmd.exe against the local /24 network of the first network adaptor listed in ipconfig.  I also formatted the name of this atomic and numbers 1 and 2 to match the others e.g. ("Remote System Discovery - [tool]"). 
**Testing:**
I tested the script portion directly on powershell, as well as the .yaml called with Invoke-Atomic
There are no known issues.

Added new atomic 'Remote System Discovery - nslookup' + typo fixes

---

atomics/T1076/T1076.yaml
execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1

**Details:**
Added a Connect-RDP test to T1076. by default it attempts to RDP from the logged on user to %logonserver%. The Source User and Target can be changed via "logonserver" and "username input variables. Prereq check ensures the user is logged onto a domain.
**Testing:**
Windows 10. @clr2of8 wrote original version. Has been Reviewed by @cherokeejb. 
N/A

T1076 rdp to domain controller

---

atomics/T1215/T1215.yaml

**Details:**
Added test for loading kernel modules for Linux via insmod. Cleanup with rmmod.
**Testing:**
Tests against Ubuntu and CentOS

T1215 - Load LKM via insmod

---

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1

this code would split the default value on any space character for some reason. Making it so default args couldn't have a space

handle spaces in input argument defaults

---

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1

Many atomics have input parameters with default values like the following:
C:\AtomicRedTeam\atomics\T1121\src\T1121.cs
or
..\\..\atomics
But all of these are dependent on your atomic redteam install path or your current working directory. Since Invoke-AtomicTest already knows the path to the atomics folder, we should be able to specify we want to use that path when we specify input parameters. This code allows you to use either "$PathToAtomicsFolder" or "PathToAtomicsFolder" when specifying a path to refer to path that Invoke-AtomicTest already knows. So for example, you could specify your input args like the following and it will always work, regardless of install path or current working directory:
$PathToAtomicsFolder\T1121\src\T1121.cs
or
PathToAtomicsFolder
This works for both windows …

PathToAtomicsFolder Input Parameters auto-replaced with actual path

---

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1

Invoke-Atomic test will tell you that you don't pass the pre-requisite checks if you try to run a test defined with 'elevation_required: true' from a non-admin shell but it will not stop you from invoking the test. This commit will warn the user when they have run a test without admin that requires admin and suggest that they do it from an elevated context.

warn if running admin test without admin

---

atomics/T1055/T1055.yaml

**Details:**
svchost.exe writing a non microsoft office file to a file with a UNC path
This works by copying cmd.exe to a file and naming in svchost.exe, then copying a file to the localhost\c$ folder
**Testing:**
tested on windows 10 vm
no issues fixed

T1055 svchost writing a file to a unc path

---

atomics/T1010/T1010.yaml
atomics/T1050/T1050.yaml
atomics/T1055/T1055.yaml
atomics/T1100/T1100.yaml
atomics/T1117/T1117.yaml
atomics/T1118/T1118.yaml
atomics/T1121/T1121.yaml
atomics/T1138/T1138.yaml
atomics/T1174/T1174.yaml
atomics/T1218/T1218.yaml
atomics/T1220/T1220.yaml
atomics/T1222/T1222.yaml
atomics/T1223/T1223.yaml

make test defaults more robust by specifying path to files with the magic "PathToAtomicsFolder" variable

remove hard-coded path to atomics folder in tests

---

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1
execution-frameworks/Invoke-AtomicRedTeam/README.md

The default value that `Invoke-AtomicTest` used for `PathToAtomicsFolder` was "..\\..\atomics". I changed  this default to "C:\AtomicRedTeam\atomic-red-team-master\atomics" so that it will work by default for all the users that install atomic red team with the Install-AtomicRedTeam script.
However, if the user does not install to the default location they may be facing a lifetime of adding the `-PathToAtomicsFolder my\custom\path\to\atomics` to every `Invoke-AtomicTest` call. To
avoid this, users can take advantage of the `$PSDefaultParameterValues` preference variable. Tip: add your default value to your PowerShell profile for a set-and-forget solution. Example:
```
$PSDefaultParameterValues = @{"Invoke-AtomicTest:PathToAtomicsFolder"="C:\Users\myuser\Documents\code\atomic-red-team\atomic …
```

new default PathToAtomicsFolder value

---

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1

The code was referring to the magic $IsWindows variable but that only works in PS Core and PS v7 so we needed to change the code to still work in the case that we are using other PowerShell versions (not core)

fix bug:  $IsWindows returns null except on PS Core or PS v7

---

execution-frameworks/Invoke-AtomicRedTeam/README.md

Updated readme to clarify that you must use "Import-Module" to make the Invoke-AtomicTest function available for use.

Readme documents required Import-Module command

---

atomics/T1022/T1022.yaml

I am using the python executor provided with this distribution. T1022 fails  with:
```
Output: Microsoft Windows [Version 10.0.17134.1069]
(c) 2018 Microsoft Corporation. All rights reserved.mkdir ./tmp/victim-files
The syntax of the command is incorrect.
```
Windows mkdir command expects paths with other slash

T1022 parameters that can actually be parsed by windows command prompt

---

atomics/T1028/T1028.md
atomics/T1028/T1028.yaml

Currently executing the Invoke-Command variant generates this output
`PS  invoke-command -computer_name Test -scriptblock {ipconfig}
Invoke-Command : A parameter cannot be found that matches parameter name 'computer_name'.`
Setting correct parameter name based on this documentation https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/invoke-command?view=powershell-6

T1028 fixing parameter in powershell Invoke-Command

---

atomics/T1086/T1086.yaml

**Details:**
Updated executor to powershell and updated command syntax. This fixed an "access denied" error when running this test.

BugFix T1086 - PowerShell Fileless Script Execution

---

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1

**Details:**
moved $testCount++ so that -testnumbers option is not thrown off by is $targetPlatform check
**Testing:**
Tested on T1002 on powershell core Ubuntu
N/A

$testCount++ before  $targetPlatform check

---

atomics/T1089/T1089.md
atomics/T1089/T1089.yaml
atomics/index.md
atomics/index.yaml
atomics/windows-index.md

**Details:**
Stops and disables an arbitrary service (security related) like Ryuk does.
**Testing:**
Tested on Win10

T1089 Disable Arbitrary Security Service

---

atomics/T1485/T1485.md
atomics/T1485/T1485.yaml
atomics/index.md
atomics/index.yaml
atomics/windows-index.md

**Details:**
Uses `del` to delete backup files in a manner similar to Ryuk.
**Testing:**
Tested in Win10

T1485 Test to delete backup files similar to Ryuk

---

atomics/T1085/T1085.yaml

**Details:**
There are 5 quote symbols in a  single command. Executing the given command generates a JScript error "Unterminated string constant"
Deleting the extra quote causes the command to correctly open notepad.exe

T1085 deleting wrong "extra" quotation mark

---

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1

The -ShowDetails flag was throwing this error:
Write-Information : A positional parameter cannot be found that accepts argument ':'.
At \Documents\code\atomic-red-team\execution-frameworks\Invoke-AtomicRedTeam\Invoke-AtomicRedTeam\Public\Invoke-AtomicTest.ps1:237 char:29 
+ ...             Write-Information -MessageData "executor": $executor_name ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Write-Information], ParameterBindingException
+ FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.WriteInformationCommand

a little bug fix

---

docs/contributing.md

**Details:**
Documentation of directory structure proposed at Atomic Friday in July
/bin for executables
/src for source
**Testing:**
N/A
none

added documentation: all other files besides .yaml or .md in /bin or /src

---

execution-frameworks/contrib/python/runner.py

**Details:**
Parsing the command to replace PathToAtomicsFolder variable.
Can-t use environment variables as some Powershell based tests use "$PathToAtomicsFolder".
I admit that it-s a bit hackish but I think it-s the most straightforward way to handle this without going through a major refactor of this framework

Leverage PathToAtomicsFolder in Python framework

---

atomics/T1016/T1016.md
atomics/T1016/T1016.yaml
atomics/index.md
atomics/index.yaml
atomics/linux-index.md
atomics/macos-index.md
atomics/windows-index.md

**Details:**
Added test for firewall rule enumeration. This was spotted in a red team/pentest engagement.
**Testing:**
Tested in Win2012r2

T1016 Firewall Rule Enumeration with Netsh

---

atomics/T1082/T1082.md
atomics/T1082/T1082.yaml
atomics/index.md
atomics/index.yaml
atomics/linux-index.md
atomics/macos-index.md
atomics/windows-index.md

**Details:**
Added tests for hostname (cross platform) and getting MachineGUID in Windows.
**Testing:**
Tested in Win2012r2, Fedora 29, macOS something
None

T1082 Add Hostname and MachineGUID tests

---

atomics/T1077/T1077.md
atomics/T1077/T1077.yaml
atomics/index.md
atomics/index.yaml
atomics/windows-index.md

**Details:**
Test to redirect command output to admin share
**Testing:**
Tested on Win2012r2
none

T1077 Redirect output to Admin Share

---

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1
execution-frameworks/Invoke-AtomicRedTeam/README.md
execution-frameworks/Invoke-AtomicRedTeam/install-atomicredteam.ps1

this was extra, unnecessary folder depth to the install due to the unzipping process

remove atomic-red-team-master folder from install

---

README.md

Removed links that didn't go anywhere and also made the execution frameworks more prominent (I missed the fact that these frameworks existing when I started with atomic red team)

removing dead links

---

atomics/T1027/T1027.md
atomics/T1027/T1027.yaml
atomics/index.md
atomics/index.yaml
atomics/windows-index.md

**Details:**
Tests for executing base64-encoded PowerShell code via CLI and via deobfuscation from the Windows Registry. 
**Testing:**
Tested in WIn2012r2
none

T1027 Execution of base64 PowerShell

---

atomics/T1089/T1089.md
atomics/T1089/T1089.yaml
atomics/index.md
atomics/index.yaml
atomics/windows-index.md

**Details:**
Tests to disable AMSI and Script Block Logging via PowerShell.
**Testing:**
Tested in Win2012r2
none

T1089 Disable AMSI & Script Block Logging

---

atomics/T1088/T1088.yaml

**Details:**
This atomic is designed to create a fake "trusted directory" and copies a binary to bypass UAC. The UAC bypass may not work on fully patched systems, however the directory structure will be created allowing for detection testing.
**Testing:**
Tested manually on Windows 10 VM. No issues noted other than this "exploit" does not successfully bypass UAC on a fully patched system. This was not deemed required for the purpose of testing detections however.

T1088 mocking trusted directories - New Atomic

---

atomics/T1053/T1053.yaml

New atomic test to include Register-ScheduledTask:
https://docs.microsoft.com/en-us/powershell/module/scheduledtasks/register-scheduledtask?view=win10-ps
**Details:**
Add a new atomic test to the existing scheduled task atomic test to include the native powershell commandlets including New-ScheduledTask and Register-Scheduled task. 
**Testing:**
Ran this via the Invoke-AtomicTest framework successfully on a Windows 10 RS4 VM 64 bit. The cleanup was also run via the Invoke-AtomicTest
None

Update to T1053 to add Register-ScheduledTask

---

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1

My last commit accidentally brought back the "atomic-red-team-master" to the default PathToAtomicsFolder parameter. Removing it again so that the default path works for a standard install

fix default PathToAtomicsFolder

---

atomics/T1007/T1007.md
atomics/T1007/T1007.yaml

**Details:**
T1007:  removed service start/stop from Atomic Test #1 as well as its input arguments.
Service start/stop is covered in T1489.
**Testing:**
1.  Reproduced bug reported in #499 in commit f51c26a.
2.  Verified no errors with fix in T1007.yaml during execution of "Invoke-AtomicTest T1007."
Fixes #499.

Fix issue #499 for T1007

---

atomics/T1003/T1003.yaml

Pointing to Invoke-Mimikatz with mimikatz 2.2 latest (31 oct 2019) embeded so with works on latest win10 versions.

using updated version of mimikatz that works on latest win10 versions

---

atomics/T1127/T1127.yaml

**Details:**
because of recent upgrades to the invoke-atomic framework; the duplicate csproj file is no longer needed by directing yaml to correct path (in src, where it should be).  able also to remove duplicate csproj file
**Testing:**
ran T1127 (msbuild) before and after change on a test box, test still.  adding @clr2of8 to review
n/a

added path to src directory

---

atomics/T1003/T1003.yaml

**Details:**
Fix test 4 output folder for T1003 that performs Credential Dumping
**Testing:**
Tested on Windows 10 (10.0.14393)
None

Fix test 4 output folder for T1003 that performs Credential Dumping

---

atomics/T1003/T1003.yaml

**Details:**
- Add cleanup command for test 5
- Add path where procdump binary should be placed
**Testing:**
Tested on Windows 10 (10.0.14393)
None

Improve test 5 (ProcDump) for T1003 that performs Credential Dumping

---

atomics/T1170/T1170.yaml

**Details:**
Replaced the ${atomics_path} input variable with the $PathToAtomicsFolder global variable. Removed the input variable block
for simplicity.
**Testing:**
Tested atomic on Windows 10 VM Version 10.0.18362 Build 18362 with no issues.

Update to T1170: Mshta executes VBScript to execute malicious command

---

atomics/T1037/T1037.yaml

**Details:**
The Atomic tests "Logon Scripts" and Startup Folder Script" were updated with additional input arguments. The first test required a fix to the string type for the registry entry to allow it to function correctly. Added a log file write command for each test to record if the commands ran at startup correctly. Other minor syntax and description updates.
**Testing:**
Tested successfully on Windows 10 VM Version 10.0.18362 Build 18362

Update T1037: Atomics "Logon Scripts" and "Startup Folder Script"

---

atomics/T1015/T1015.yaml

**Details:**
After the latest change to these tests, they are now failing with the following error:
```
New-ItemProperty : Cannot convert value "C:\windows\system32\cmd.exe" to type "System.UInt32". Error: "Input string
was not in a correct format."
At line:7 char:9
+         New-ItemProperty -Path $registryPath -Name $name -Value $Valu ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : WriteError: (HKEY_LOCAL_MACH...Options\osk.exe:String) [New-ItemProperty], PSInvalidCast
Exception
+ FullyQualifiedErrorId : System.Management.Automation.PSInvalidCastException,Microsoft.PowerShell.Commands.NewIte
mPropertyCommand
```
This is due to incorrect reg value type DWORD being used where it should be STRING.
**Testing:**
Tested with new STRING …

T1015: Fix incorrect reg value type

---

atomic_red_team/spec.yaml

**Details:**
Just removed prereq_command field from executors tree
**Testing:**

Removed prereq command from execution tree in spec.yaml

---

atomics/T1015/T1015.md
atomics/T1015/T1015.yaml
atomics/index.md
atomics/index.yaml
atomics/windows-index.md

Reverts redcanaryco/atomic-red-team#808
When running this new test, it causes "The process tried to write to a nonexistent pipe" error
I can fix the immediate issue by putting quotes around the parent_list, but this won't work when more than one item is passed in the list. Also, it results in the following additional error.

Revert "T1015 collapsed technique into one atomic with additional inputargs"

---

execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Private/Invoke-CheckPrereqs.ps1
execution-frameworks/Invoke-AtomicRedTeam/Invoke-AtomicRedTeam/Public/Invoke-AtomicTest.ps1

When the dependencies included a multi-line powershell script, Invoke-AtomicTest was giving an error. This fixes it.

fix prereq bug for multi-line powershell

---

atomics/T1107/T1107.yaml

**Details:**
Adversaries may delete TeamViewer log files to hide activity. This should provide a high true-positive alert ration. This test just places the files in a non-TeamViewer folder, a detection would just check for a deletion event matching the TeamViewer log file format of TeamViewerXX_Logfile.log
https://twitter.com/SBousseaden/status/1197524463304290305?s=20
**Testing:**
Windows 10, Mac

Delete TeamViewer Log Files

---

atomics/T1015/T1015.yaml

T1015, set default input args to be a list of executables
This matches what this T# was doing previously using multiple individual tests. Users can specify a subset of the list or just one executable if they desire.

T1015, set default input args to be a list of executables

---

atomics/T1071/T1071.yaml

Adjusted the default domain from "example.com" to "127.0.0.1.xip.io" to allow the "Resolve-DnsName" cmdlet to work as expected. Should prevent extended runtime issues associated with NXDOMAIN.

T1071 - Updated "example.com" default domain with resolvable domain name.

---

atomics/T1037/T1037.yaml

**Details:**
Trickbot uses this flag in scripts
**Testing:**
Windows 10 VM

Add /E:Jscript flag to script

---

atomics/T1105/T1105.yaml

**Details:**
OSTap copies itself in a specific way to shares and secondary drives. This emulates the activity. By default it will simulate connections to a network share by connecting to the local admin share so local admin rights are needed. 
**Testing:**
Tested on Windows 10. 

Added Test for OSTAP Worming Activity to T1105

---

atomic_red_team/atomic_doc_template.md.erb

**Details:**
Fixed an issue in the markdown documentation files where the first step is merged in with the section header. 
**Testing:**
I ran `bin/generate-atomic-docs.rb` and verified that the markdown files had the expected carriage return.
https://github.com/redcanaryco/atomic-red-team/pull/835 is related. I created a separate PR for this issue and I'll let that other PR focus on the issue of the XML file not getting rendered properly.

Fix docs template carriage return issue

---

atomics/T1071/T1071.yaml

**Details:**
Added T1071-8 OSTap Payload Download
uses cscript //E:jscript to download and write a file to disk
**Testing:**
Windows 10

T1071-8 OSTap Payload Download

---

atomic_red_team/atomic_doc_template.md.erb

**Details:**
this will fix an error in markdown generation for multi line and Unicode errors in Input Argument values.
**Testing:**
running .\bin\generate-atomic-docs.rb makes changes to T1158-8 (to_s fixed Unicode character) , T1015-1 (removes newline in arg description), T1204 (removes newline in arg description).

generat-atomic-docs.rb Cast to to_s.strip

---

atomics/T1089/T1089.yaml

**Details:**
Gorgon group may disable Office security features so that their code can run
https://unit42.paloaltonetworks.com/unit42-gorgon-group-slithering-nation-state-cybercrime/
**Testing:**
Windows 10 VM

Disable Office Security Settings, Delete Windows Defender Definition Files

---

atomics/T1214/T1214.md
atomics/T1214/T1214.yaml

…ckbot
**Details:**
TrickBot queries the registry for PuTTY session information to steal private keys.  This adds enumeration of these registry keys to T1214.
References:
[TrendMicro](https://blog.trendmicro.com/trendlabs-security-intelligence/trickbot-adds-remote-application-credential-grabbing-capabilities-to-its-repertoire/)
[MITRE](https://attack.mitre.org/software/S0266/)
**Testing:**
Tested on Win10 machines. If key does not exist, will produce an error, similar to other checks.
None

Modifying T1214 to include TrickBot PuTTY Session enumeration

---

atomics/T1003/T1003.yaml

Importing the Invoke-WebRequestVerifyHash function from its online source to ensure that it available for use in newly spawned PowerShell processes such as those that are created during Invoke-AtomicTest. 
Previous to this change, if you didn't have the Invoke-AtomicRedTeam module as an import statement in your PowerShell profile you would receive and error that "The term 'Invoke-WebRequestVerifyHash' is not recognized as the name of a cmdlet, function, script file, or operable program."

make verifyhash function available to prereq

---

execution-frameworks/contrib/python/runner.py

https://github.com/redcanaryco/atomic-red-team/issues/873
**Details:**
When running the python execution framework in non interactive mode (with python code) the executors doesn't get filtered by the platform and that makes some inconsistencies between the executor numbers for a same technique.
More info in this issue:
https://github.com/redcanaryco/atomic-red-team/issues/873
**Testing:**
Tested manually.
https://github.com/redcanaryco/atomic-red-team/issues/873

Fixes #873

---

atomics/T1118/T1118.yaml

**Details:**
In order to better support testing over remote sessions, I need to ensure that dependencies can be resolved rather than assuming that the dependency exists in the atomics folder. This PR adds dependencies to the T1118 tests.
**Testing:**
Tested both locally and remotely.

Adding dependencies to T1118 to ensure support for remote testing

---

atomics/T1121/T1121.yaml

Neither test was generating the output file specified by the #{output_file} input arg.
Test number 2 requires admin to run successfully, so indicated that admin was required in the yaml.

fixes for both T1121 tests

---

atomics/T1047/T1047.yaml

**Details:**
Added documentation to specify what to look for when a test is successful. 
Added clean up commands for Tests 5,6.
Replaced default ip-> localhost, default process-> notepad.exe , default service:->spooler to use items available by default in the windows environment.
**Testing:**
Invoke-AtomicTest T1047 -TestNumbers  1  # works up to test 6
Invoke-AtomicTest T1047 -TestNumbers  5 -cleanup #works on test 6 as well.

T1047 documentation

---

atomics/T1099/T1099.yaml

**Details:** Changed the executor for all windows test to powershell. Modified windows test to actually create  file to modify permissions as it otherwise just fails unless input arguments are specified. Also added cleanup commands to the windows tests.**
**Testing:** Windows 10 VM; Version:	10.0.18362 Build 18362**

T1099 updates to windows tests 

---

atomics/T1087/T1087.md
atomics/T1087/T1087.yaml

**Details:**
lastlog is not supported in 10.14.6, I don't have access to older OSX versions to test those. I will test if I can dig up some older versions
**Testing:**
made changes to atomic test 5, ran through the ART runner
validated using bin/validate-atomics.rb

lastlog is not supported in OSX, at least not in 10.14.6

---

atomics/T1035/T1035.yaml

Typo in prereq_command

---

atomics/T1086/T1086.yaml

T1086 - Added cleanup command for BloodHound Test

---

atomics/T1059/T1059.yaml

**Details:**
The wget command tries to download the file from a URL that is not correct and the server response is `404 not found` instead of the bash script.  GitHub paths are case sensitive and the `echo-art-fish.sh` sits within the `atomics` path not `Atomics`.
**Testing:**
Run interactive test
None

Fixing a typo in the wget URL for T1059

---

atomics/T1154/T1154.yaml

**Details:**
The `echo-art-fish.sh` file has to be marked as executable before it can be run when the signal is trapped. A user would normally clone the repository and then run the tests without manually changing the permissions of the files. Since the executable flag is not set when the test runs it fails with the following error:  `failed to run command '/home/user/src/atomic-red-team/atomics/T1154/../T1154/src/echo-art-fish.sh': Permission denied`. Running the script with `sh`  fixes the issue and doesn't require to manually set the flag before running the test.
**Testing:**
Run the test in interactive mode and non interactive mode with the python interpreter on linux (Ubuntu 19.10) and MacOS (Catalina 10.15.4).
None

Fix issue with non-executable bash file

---

atomics/T1166/T1166.yaml

**Details:**
The command `copy` is used on Windows systems. Running the test on macOS and Linux will cause an error because `copy` doesn't exist.
**Testing:**
Run the test in interactive mode.
None

Fix command used to copy files in linux and macOS

---

atomics/T1166/T1166.yaml
atomics/T1166/src/hello.c
atomics/T1215/T1215.yaml
atomics/T1215/src/Makefile
atomics/T1215/src/hello.c

**Details:**
- Replacing relative paths with absolute paths to avoid losing context when there is a direcotry change. The Python runner runs each command in a different sub-process and therefore `cd` command does not work. Another solution was to fix the `runner.py` to run all commands in a single `sh` session, like the Ruby runner, but it might break other stuff.
- hello.c uses `import` pre-processor statement which has been deprecated since gcc 3.4 and generates warning message during compilation:`#import is a deprecated GCC extension`. Replaced `import` with `include`. Another change was to modify the sleep command from 60 seconds to 5 seconds.
**Testing:**
Linux and MacOS
None

T1166 - Fix absolute path, C code optimizations

---

atomics/Indexes/Indexes-CSV/index.csv
atomics/Indexes/Indexes-CSV/windows-index.csv
atomics/Indexes/Indexes-Markdown/index.md
atomics/Indexes/Indexes-Markdown/windows-index.md
atomics/Indexes/index.yaml
atomics/T1099/T1099.md
atomics/T1099/T1099.yaml

**Details:**
This is the Timestomp test used during recent [MITRE evals](https://attackevals.mitre.org/APT29/) - https://github.com/mitre-attack/attack-arsenal/blob/master/adversary_emulation/APT29/CALDERA_DIY/evals/data/abilities/defensive-evasion/4a2ad84e-a93a-4b2e-b1f0-c354d6a41278.yml
**Testing:**
Confirmed operation on Windows 10.

Update T1099.yaml - Timestomp

---

atomics/T1122/T1122.yaml

**Details:**
Add two new cor_profiler tests leveraging system and user scope environment variables.
**Testing:**
Tested all three tests locally with invoke-atomictest. Cleanup works for all three tests. yaml passes CircleCi.
none

[UPDATE] T1122 - Add two more COR_PROFILER tests

---

atomic_red_team/atomic_red_team.rb
bin/generate-atomic-docs.rb

For OS specific indexes, only include link to markdown file if that technique contains tests for the given OS.

Update links on Indexes

---

atomics/T1036/T1036.yaml
atomics/T1036/src/T1036_masquerading.ps1
atomics/T1036/src/T1036_masquerading.vbs

**Details:**
Change the the executer to command prompt. this made it easier to filter out false positives without filtering out the Atomic itself
**Testing:**
Windows 10 VM

T1036 file extension masquerading fix

---

.gitignore

Accidentally pushed a change to gitignore markdown files which causes the md files not to be generated by Circle CI

remove markdown files from gitignore

---

atomics/T1053.005/T1053.005.yaml

**Details:**
This test creates remotely a scheduled task, so if we want to delete it during cleanup, then we have to do it remotely too :)
**Testing:**
I didn't test it but I just copied the code from the execution command above
Didn't create one

T1053.005: execute remotely the cleanup command, after remote creation of scheduled task

---

atomics/T1569.002/T1569.002.yaml

**Details:**
Add cleanup command. Actually the best would be to transform 'c:\art-marker.txt' into an input itself and re-use it in the command, but I think this is still a step forward :)
**Testing:**
N/A
Didn't create one

T1569.002-1: add cleanup

---

atomics/T1105/T1105.yaml

**Details:**
Current code fails with this error:
```powershell
Invoke-AtomicTest T1105 -TestNumbers 9
PathToAtomicsFolder = C:\AtomicRedTeam\atomics
Executing test: T1105-9 Windows - BITSAdmin BITS Download
BITSADMIN version 3.0
BITS administration utility.
(C) Copyright Microsoft Corp.
Unable to add file - 0x80070057
The parameter is incorrect.
```
This is due to the fact that an absolute path is needed for the target local file.
See the difference:
```console
c:\>C:\Windows\System32\bitsadmin.exe /transfer qcxjb7 /Priority HIGH "https://raw.githubusercontent.com/redcanaryco/atomic-red-team/master/LICENSE.txt" "Atomic-license.txt"
BITSADMIN version 3.0
BITS administration utility.
(C) Copyright Microsoft Corp.
Unable to add file - 0x80070057
The parameter is incorrect. …
```

T1105: fix bitsadmin local_path

---

atomics/T1197/T1197.yaml

**Details:**
If we run all 3 tests at once we get errors due to the fact that the local file remains and has the same name. So I suggest using a different name for each.
**Testing:**
N/A
But it will conflict with this change in PR #1048 
https://github.com/redcanaryco/atomic-red-team/pull/1048/files#diff-2174818575ed3638cc543db3ec8fd54dL79-L82
None

T1197: use different names for local files of different tests

---

atomics/T1105/T1105.yaml

**Details:**
T1105 tests 7 and 8 lack a cleanup command and I suggest to add it.
Note that the cleanup for `certutil -urlcache -split -f ...` is still incomplete because it creates a `<hash>.key` file. I could remove all `*.key` files but that could have undesired impact. I don't know if we could also hardcode the `<hash>` value...
For the PowerShell version, I chose to remove the hour and minute from the folder name to ensure we correctly delete the folder if the minute value changes between run and cleanup (the day could also change but that's less likely).
Another option would be to use a more static folder name, or to pass the generated folder name between execution and cleanup (I don't know if that's supported by ART)
**Testing:**
* Execution:
```powershell
PS C:\> Invoke-AtomicTest …
```

T1105: add cleanup to tests 7 & 8

---

atomics/T1140/T1140.yaml

**Details:**
We get an error if execute the two tests at once because they use the same name for files (notice "The file exists" errors):
```powershell
Invoke-AtomicTest T1140
PathToAtomicsFolder = C:\AtomicRedTeam\atomics
Executing test: T1140-1 Deobfuscate/Decode Files Or Information
Input Length = 38072
Output Length = 27648
CertUtil: -decode command completed successfully.
Done executing test: T1140-1 Deobfuscate/Decode Files Or Information
Executing test: T1140-2 Certutil Rename and Decode
1 file(s) copied.
(null)
error The file exists. 0x80070050 (WIN32: 80 ERROR_FILE_EXISTS)
(null)
CertUtil: The file exists.
(null)
error The file exists. 0x80070050 (WIN32: 80 ERROR_FILE_EXISTS)
(null)
CertUtil: The file exists.
Done executing test: T1140-2 Certutil Rename and Decode
```
I suggest …

T1140: use different name for 2nd test to allow executing both in sequence

---

atomics/T1053.005/T1053.005.yaml

**Details:**
Creation of a scheduled task running "once" doesn't require admin according to my tests (contrary to "onlogon" tasks for example)
**Testing:**
I tested locally on a Win10 with a normal user
None

T1053.005: scheduled task creation doesn't require admin

---

atomics/T1543.003/T1543.003.yaml

**Details:**
If we want to run both T1050 tests 1 and 2, one after the other without any cleanup between we get an error:
```powershell
PS C:\Windows\system32> Invoke-AtomicTest T1050
PathToAtomicsFolder = C:\AtomicRedTeam\atomics
Executing test: T1050-1 Service Installation CMD
[SC] CreateService SUCCESS
SERVICE_NAME: AtomicTestService
TYPE               : 10  WIN32_OWN_PROCESS
STATE              : 2  START_PENDING
(NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
WIN32_EXIT_CODE    : 0  (0x0)
SERVICE_EXIT_CODE  : 0  (0x0)
CHECKPOINT         : 0x0
WAIT_HINT          : 0x7d0
PID                : 4572
FLAGS              :
Done executing test: T1050-1 Service Installation CMD
Executing test: T1050-2 Service Installation PowerShell
New-Service : Service ' (AtomicTestService)' cannot be created …
```

T1543.003: use different service name depending if cmd or psh is used to prevent name conflict

---

atomics/T1074.001/src/Discovery.bat

**Details:**
Current code fails due to presence of space in unquoted path, ex. (on a French system, error is "syntax error"):
```
c:\>reg query HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\Notify
ERREUR : syntaxe incorrecte.
Entrez "REG QUERY /?" pour afficher la syntaxe.
```
**Testing:**
After it works (except that this key doesn't exist, but the error is normal this time):
```
c:\>reg query "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon\Notify"
Erreur : Erreur : le système n’a pas trouvé la clé ou la valeur de Registre spécifiée.
```
Didn't find nor create one

T1074: add missing quote around path containing a space character

---

atomics/T1482/T1482.yaml

It doesn't change the result of the test and it prevents displaying an ugly error message when it's not found

T1482: hide error in check prereq command

---

atomics/T1546.008/T1546.008.yaml

I discovered by luck that the cleanup command was lost in transition to sub technique:
https://github.com/redcanaryco/atomic-red-team/commit/24549e3866407c3080b95b6afebf78e8acd23352#diff-11963178672457b3aab959974d0dff71L46-L52
I also added `2>&1` at its end because we prefer to hide error messages (based on what I see in other tests) when it tries to cleanup a key that doesn't exist.
I suggest checking if nothing else wasn't lost ;)

T1546.008: re-add cleanup command lost during transition to subtechnique

---

atomics/T1003.003/T1003.003.yaml

**Details:**
target folder must be empty for ntdsutil export, which is unlikely the case for c:\windows\temp and then we get this error:
```
PS C:\Users\myadmin> Invoke-AtomicTest T1003 -TestNumbers 3
PathToAtomicsFolder = C:\AtomicRedTeam\atomics
Executing test: T1003-3 Windows Credential Editor
Done executing test: T1003-3 Windows Credential Editor
PS C:\Users\myadmin> Invoke-AtomicTest T1003 -TestNumbers 10
PathToAtomicsFolder = C:\AtomicRedTeam\atomics
Executing test: T1003-10 Dump Active Directory Database with NTDSUtil
ntdsutil: ac i ntds
Active instance set to "ntds".
ntdsutil: ifm
ifm: create full C:\Windows\Temp
*** Error: target folder C:\Windows\Temp is not empty.
ifm: q
ntdsutil: q
Done executing test: T1003-10 Dump Active Directory Database with NTDSUtil
```
I also added a …

T1003.003: create empty folder for ntdsutil output and add cleanup command

---

atomics/T1053.005/T1053.005.yaml

**Details:**
/RU and /RP are credentials for "runas" when running the task, not for remote auth when creating it
**Testing:**
Before I used "user_name" and "password" to specify a user with remote admin rights. However it failed and I didn't understand why... It was because it used my current user auth, instead of the specified credentials, for remote auth.
After it works fine and the task runs as the same user as used to authenticate
Didn't create one

T1053.005: in remote schtasks, we need username and password for authentication

---

atomics/T1059.004/T1059.004.yaml
atomics/T1059.004/echo-art-fish.sh
atomics/T1059.004/src/echo-art-fish.sh

**Details:**
1)- moved shell script to /src on test 2 [https://github.com/redcanaryco/atomic-red-team/tree/master/atomics/T1059.004]
- confirmed bash syntax worked w/o quotes
- confirmed /tmp (test 1) still a valid simlink to /var/tmp
2)- grepped current atomics folder for any other similar errors
3)- verified other folders previously noted to have clean-up issues are fixed or no-longer exist:
(  no longer exists  ) T1086
( also no longer exists   )  T1103
( fixed already   ) T1114
( no longer exists   ) T1117
(  no longer exists  ) T1166
**Testing:**
tested as mentioned above, otherwise only moved the 1 file and fixed references
n/a

Directory clean-up (per spec.yaml) pass

---

atomics/T1046/T1046.yaml

Fix the prereq check which was broken and made the host to scan configurable. Remove the cleanup command that was uninstalling the prereq because the general rule of thumb is the cleanup does not remove prereqs, only removes temp files, restarts services, resets registry keys, etc.

configurable host to scan

---

atomics/T1053.005/T1053.005.yaml

**Details:**
The atomics Scheduled task Remote in T1053.005 was not working for Windows Server 2016. The error was:
The fix is to change parameter /U to /RU and /P to /RP:
**Testing:**
-
-

bug fix atomics in T1053.005

---

atomic_red_team/atomic_red_team.rb

Remove a circular argument reference of only_platform, which causes scripts in ./bin/ to fail when using Ruby version 2.7.
**Details:**
A circular argument reference prevents scripts in ./bin/ from running successfully on Ruby 2.7.
```
[billy@art atomic-red-team]$ ruby --version
ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux]
[billy@art atomic-red-team]$ ./bin/validate-atomics.rb 
Traceback (most recent call last):
2: from ./bin/validate-atomics.rb:4:in `<main>'
1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': /home/billy/Projects/atomic-red-team/atomic_red_team/atomic_red_team.rb:52: circular argument reference - only_platform (SyntaxError)
```
**Testing:**
Fixed version …

Fix: only_platform circular argument reference

---

atomics/T1070.003/T1070.003.yaml

**Details:**
Using Space Before Command Avoid Logging to History
**Testing:**
Linux

T1070.003-Update

---

atomics/T1546.010/src/T1546.010.reg

Details:
Changed reg file AppInit_DLLs path from C:\Tools\T1103.dll + T1103x86.dll to C:\Tools\T1546.010 + T1546.010x86.dll
This Atomic Use Case was broken after sub-technique conformity.
Testing:
Validated the T1546.010 use-case worked locally after modifying.
Cleanup task wipes the AppInit_DLLs and LoadAppInit_DLLs after usage.
Associated Issues:
N/A

Update RegKey AppInit_DLLs Path

---

atomic_red_team/atomic_doc_template.md.erb

In some cases the Mark Down generator wasn't properly reading the prereqs out of the yaml files. This fixes it.

fix for printing prereqs in md

---

atomics/T1078.001/T1078.001.yaml

Creating Folder for sub technique and yaml for .001
**Details:**
Adding Folder for subtechnique Default Accounts under Valid Accounts, under Persistence Tactic
This is enabling (activate) the default Guest account and adding it to administrators group
**Testing:**
Used my own (new) repo first and then used start-atomicGUI and ran PS C:\Tools\AtomicRedTeam> Invoke-AtomicTest T1078.001 -PathToAtomicsFolder C:\Users\jesse\Documents\GitHub\atomic-red-team\atomics\ -ShowDetailsBrief
Add sub technique where there wasn't any before

Create T1078.001 and yaml

---

atomics/T1531/T1531.yaml

Removed the need for dependencies on "Change User Password - Windows" and "Delete User - Windows" by adding the account creation command to the executor. Tested successfully.

T1531 - Removed the need for dependencies on tests 1 and 2 

---

atomics/T1021.001/T1021.001.yaml
atomics/T1563.002/T1563.002.yaml

**Details:**
Moved atomic for RDP Hijacking from T1021.001 to T11563.002. T1021.001 is for an already owned account, whereas T1563.002 is directly for Hijacking. 
**Testing:**
None needed. 
None.

Moved Atomic for RDP Hijacking

---

atomics/T1098/T1098.yaml

**Details:**
Added the capability to create domain account and add it to a given group. This enables to detect changes on sensitive groups.
**Testing:**
Checked and installed prereqs on a fresh Win 10 machine
Ran the test against a DC with `-Session` parameter
Ran the cleanup
Ran the cleanup after several tests without cleanup to make sure it cleans all previously created accounts too
Ran for Domain Admins
Ran for DNSAdmins
Ran with invalid `create_args` input to confirm the PS failure of the remote session is visble from Invoke-AtomicTest console
N/A

T1098 - Implemented domain account manipulation

---

atomics/T1040/T1040.yaml

Removed windump from the executor commands as it is not necessary to get a successful end result from this test.
Added dependencies to check for Tshark in correct path, and to download and install Wireshark/Tshark if it is not already present.
Edited description to match the changes made.
Changed the default interface to "ethernet" in order to test.
Tested successfully.

Update to T1040.yaml test 3 "Packet capture windows command prompt"

---

atomics/T1562.002/T1562.002.yaml

Update T1562.002.yaml with Invoke-Phant0m to Kill Windows Event Log Services Threads.
**Details:**
Kills Windows Log Services Threads
**Testing:**
local test
Add an additional atomic-test

Update T1562.002.yaml - Invoke-Phant0m

---

atomics/T1098/T1098.yaml

**Details:**
Added -Cleanup feature for T1098 as suggested in PR #1201 . It required to rewrite the test.
Also removed the CIM query for a native PS command to speed-up the test.
Shrank the size of the new name, as Win 10 was rejecting lenghty names.
**Testing:**
Tested modification and cleanup with the built-in Administrator account on a domain joined computer
PR #1201

T1098 - Added cleanup capability

---

atomics/T1021.006/T1021.006.yaml

**Details:**
The remote execution through MMC (which btw should probably not be in this technique, as suggested in #1042 ) has a default value of `computer1` for the execution target. Defaulting to `localhost` so it may run without additional argument. The detection is likely based upon the process tree anyway.
**Testing:**
Ran locally and remotely, comparing artefacts in Sysmon and Security event logs to see what may be missed be running it locally (4624/3, that's all)

T1021.006 - Change default target for MMC remote exec to localhost

---

atomic_red_team/atomic_doc_template.md.erb

**Details:**
Fixed a URL formatting issue where all links to MITRE ATT&CK descriptions were broken (returned 404).
**Testing:**
Ran `bin/generate-atomic-docs.rb` and verified that the URLs are correctly linked to the corresponding techniques.
None

Fix broken MITRE ATT&CK URLs

---

atomics/T1134.001/T1134.001.yaml

**Details:**
These tests have been written as part of the OSCD Initiative sprint (#1220).
The inital goal was to have a test for these two sigma rules (task 8 in the sprint backlog):
- [win_meterpreter_or_cobaltstrike_getsystem_service_start.yml](https://github.com/Neo23x0/sigma/blob/master/rules/windows/process_creation/win_meterpreter_or_cobaltstrike_getsystem_service_start.yml)
- [win_meterpreter_or_cobaltstrike_getsystem_service_installation.yml](https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_meterpreter_or_cobaltstrike_getsystem_service_installation.yml)
These rules are covered by the first atomic test (named pipe client impersonation).
However, the PowerShell module that I used for the test also offers an other technique (token duplication via …

Add tests for T1134.001 Access Token Impersonation/Theft

---

execution-frameworks/contrib/python/runner.py

**Details:**
An off-by-one issue exists in the python execution framework when comparing the number of executors that exist for the technique with the executor position that was requested. This validation causes issues downstream, specifically with the `--dependency` flag which throws an `IndexError` when invoking the runner with an invalid executor index. This PR fixes the validation step so that invalid executors are served an error message.
**Testing:**
Prior to the PR, executing `runner.py` with an executor position larger than the number of available executors will throw an  `IndexError` exception in `check_dependencies()`
`python3.7 runner.py run T1053.003 7 --dependencies --cleanup`
Following the PR, this command will produce an error message:
```
The position '7' couldn't be …
```

Fix off-by-one and misspelling

---

atomics/T1006/T1006.yaml

**Details:**
This test has been written as part of the OSCD Initiative sprint (#1220).
The goal was to have a test for this sigma rule (task 1 in the sprint backlog):
- [sysmon_raw_disk_access_using_illegitimate_tools.yml](https://github.com/Neo23x0/sigma/blob/master/rules/windows/sysmon/sysmon_raw_disk_access_using_illegitimate_tools.yml)
**Testing:**
Manually tested on Windows 10 by running the tests then inspecting the Sysmon event log.

[OSCD] Add test for T1006 Direct Volume Access

---

atomics/T1036.004/T1036.004.yaml

**Details:**
These tests have been written as part of the OSCD Initiative sprint (#1220).
The initial goal was to have a test for this sigma rule (task 2 in the sprint backlog):
* https://github.com/Neo23x0/sigma/blob/master/rules/windows/process_creation/win_apt_wocao.yml
But it only mentions `sc` used to create a service (`create win32times binPath=`). I have also found in the [FoxIt report](https://resources.fox-it.com/rs/170-CAK-271/images/201912_Report_Operation_Wocao.pdf) that this threat actor also uses `schtasks` to create a service so I also implemented a test about that.
**Testing:**
I have launched both tests using ART invoke framework on my local AD lab. Both work as expected including cleanup commands when launched with administrator privs. `elevated_required` is set to …

[OSCD] T1036.004: Masquerade Task or Service - 2 tests

---

atomics/T1136.002/T1136.002.yaml

**Details:**
These tests have been written as part of the OSCD Initiative sprint (#1220).
The initial goal was to have a test for this sigma rule (task 10 in the sprint backlog):
* https://github.com/Neo23x0/sigma/blob/master/rules/windows/builtin/win_susp_local_anon_logon_created.yml
But I also have adopted the test from .001 subtechnique related to adding local (domain in .002 subtechnique) admin account
**Testing:**
I have launched both tests using ART invoke framework on my local AD lab. Both work as expected including cleanup commands.

[OSCD] T1136.002: Domain Account - 2 tests

---

atomics/T1113/T1113.yaml

Details:
These tests have been written as part of the OSCD Initiative sprint (#1220).
The initial goal was to have a test for this sigma rule (task 7 in the sprint backlog):
https://github.com/Neo23x0/sigma/blob/master/rules/windows/process_creation/win_susp_psr_capture_screenshots.yml
Testing:
Tested on local machine
Associated Issues:
#1220

[OSCD] Create atomic test for T1113 for Windows

---

bin/generate-atomic-docs.rb

The navigator layer coloring was showing an under-representation of which techniques had at least one atomic test. The navigator layer will now be generated such that any parent technique with one or more atomics in one of its sub-techniques will also be colored.
Old view
New view

add nav score for parent technique

---

atomics/T1137.002/T1137.002.yaml

**Details:**
office persistence test registry. Opening MS office after setting this registry would load the Arbitrary DLL
**Testing:**
Works successfully
None observed

[OSCD] Office persiststence :  Office test

---

atomics/T1564.002/T1564.002.yaml

**Details:**
Added another option to the T1564.002 test.
**Testing:**
Tested locally.
Here is a relevant [detection rule](https://github.com/Neo23x0/sigma/pull/1131) and the other analytics in the Sigma repository.

[OSCD] Update T1564.002: Hidden User Creation test for macOS

---

atomics/T1562.006/T1562.006.yaml

This test covers one of the possible scenarios for implementing an attack on security systems, namely, the use of the [Indicator Blocking sub-technique](https://attack.mitre.org/techniques/T1562/006)
**Details:**
This test emulates the actions of attackers who make malicious changes to the audit and logging configuration files. Any unauthorized modification of these files requires investigation.
Explanations of the commands being executed:
- command `sed -i '$ a sometext'` adds a line with the text "sometext" to the end of the file;
- command `sed -i '$ d'` removes the last line from the file.
**Testing:**
Tested locally on Ubuntu 18.04.5 LTS system
OSCD second sprint task: https://github.com/redcanaryco/atomic-red-team/issues/1219

[OSCD] Added T1562.006 tests to emulate indicator blocking on Linux

---

atomics/Indexes/index.yaml
atomics/T1113/T1113.md
atomics/T1113/T1113.yaml

**Details:**
Adding `-y` to `apt-get install` to enable unattended installs.
**Testing:**
Tested by running and observing successful install of Imagemagic via a remote invocation.
Issue raised https://github.com/redcanaryco/atomic-red-team/issues/1279

Assume Yes for pre-req installation via aptitude

---

atomics/T1087.002/T1087.002.yaml

Quick test for default domain administrator account enumeration
**Details:**
In recent Ryuk campaigns this discovery method has been documented as being used.
**Testing:**
Invoke-AtomicTest T1087.002 -TestNumbers 9

New test for domain admin account enumeration

---

atomics/T1518.001/T1518.001.yaml

**Details:**
- split macOS and Linux tests for T1518.001
- update processes lists
**Testing:**
Tested on a local machine
Here are the relevant Sigma rules:
- https://github.com/Neo23x0/sigma/blob/6f3ac02cb363b0fc68ebe3f762b3b6e6385fa568/rules/linux/lnx_security_software_discovery.yml
- https://github.com/Neo23x0/sigma/blob/5a8c7cd3f9291ac010f2f0e94037b0304d5cf458/rules/linux/macos_security_software_discovery.yml

[OSCD] split Linux and macOS tests for T1518.001; update processes list

---

atomics/T1218/T1218.yaml

**Details:**
default path contains a space and the command needs to be surrounded by quotes.
**Testing:**
Windows 10 1903

Update T1218 Test 5

---

atomics/T1204.002/T1204.002.yaml
atomics/T1566.001/T1566.001.yaml

Taking advantage of the new functionality added to invoke-maldoc to simplify these atomics. For example:
1) Don't need to specify office version manually now
2) Don't need to ensure that office has been run once first in the dependencies
3) Don't need to cleanup the registry keys in cleanup commands because Invoke-Maldoc does it now

simplify maldoc atomics

---

atomics/T1218/T1218.yaml
atomics/T1218/src/T1218.xml
atomics/T1218/src/T1218.xoml

**Details:**
This MR adds support for 2 LOLBin tests related to Microsoft.Workflow.Compiler.exe. 
For more details on the threats surrounding Microsoft.Workflow.Compiler.exe please read Matt's write-up [here](https://posts.specterops.io/arbitrary-unsigned-code-execution-vector-in-microsoft-workflow-compiler-exe-3d9294bc5efb)
The 2 tests included are:
1. Generic execution of Microsoft.Workflow.Compiler passing in a pre-built .Net assembly that will spawn calc.exe
2. The second test will run the same payload as above but it will do it through a renamed version of the workflow compiler. 
**Testing:**
```
>Invoke-AtomicTest T1218 -TestNumbers 6 -CheckPrereqs
PathToAtomicsFolder = C:\AtomicRedTeam\atomic-red-team-master\atomics
CheckPrereq's for: T1218-6 Microsoft.Workflow.Compiler.exe Payload …
```

Workflow compiler tests

---

.circleci/config.yml

Moves the GUID and doc generation and commit CI steps to the master branch, leaving only test validation on the PR branch.
As specified by https://github.com/redcanaryco/atomic-red-team/issues/1336

Move CI generation of GUIDs and docs to master branch only

---

atomics/T1218.011/T1218.011.yaml
atomics/T1218.011/src/akteullen.vbs
atomics/T1218.011/src/index.hta

Execution of HTA and VBS Files using Rundll32 and URL.dll
IcedID uses this TTP as follows:
rundll32.exe url.dll,OpenURL %PUBLIC%\index.hta
Trickbot uses this TTP as follows:
rundll32.exe URL.dll,FileProtocolHandler C:\\..\\Detail\\akteullen.vbs
In this atomic, the sample hta file opens the calculator and the vbs file shows a message dialog with "rundll32 spawned wscript"

rundll32 spawning mshta and wscript

---

atomics/T1218/T1218.yaml

Adding RemoteFXvGPUDisablement.exe LOLBIN coverage via AtomicTestHarnesses to T1218. Thanks for writing up this atomic test, @MHaggis!
**Details:**
RemoteFXvGPUDisablement.exe is an abusable built-in, signed PowerShell host binary. This test implements the `Invoke-ATHRemoteFXvGPUDisablementCommand` in `AtomicTestHarnesses` to supply coverage.
**Testing:**
Atomic test was tested locally. [Corresponding AtomicTestHarnesses tests](https://github.com/redcanaryco/AtomicTestHarnesses/blob/master/TestHarnesses/T1218_SignedBinaryProxyExecution/InvokeRemoteFXvGPUDisablementCommand.Tests.ps1) also ran without issue.
N/A

Adding RemoteFXvGPUDisablement.exe LOLBin coverage

---

atomics/T1558.001/T1558.001.yaml

**Details:**
Create test for Golden Ticket attack.
It supports a default domain SID (one less parameter to specify)
**Testing:**
With default SID (implict):
```
invoke-atomictest T1558.001 -InputArgs @{ "domain" = "lab.lan" ; "krbtgt_aes256_key"="xxxxx" }
[...]
mimikatz(commandline) # kerberos::golden /domain:lab.lan /sid:S-1-5-21-1891480667-311803191-3341389180 /aes256:xxxxx /user:goldenticketfakeuser /ptt
```
With specific SID ("toto"):
```
invoke-atomictest T1558.001 -InputArgs @{ "domain" = "lab.lan" ; "krbtgt_aes256_key"="xxxxx" ; …
```

T1558.001: add test "Golden ticket"

---

atomics/T1110.003/T1110.003.yaml

**Details:**
Add a new password spraying test. This variant uses builtin API against LDAP and allows to choose between NTLM and Kerberos
Similar to #1354
**Testing:**
None

T1110.003: add test "Password spray all domain users with a single password via LDAP against domain controller (NTLM or Kerberos)"

---

atomics/T1110.001/T1110.001.yaml

**Details:**
Add a new bruteforce test. This variant uses builtin API against LDAP and allows to choose between NTLM and Kerberos
Similar to #1349
**Testing:**
None

T1110.001: add test "Brute Force Credentials of single domain user via LDAP against domain controller (NTLM or Kerberos)"

---

atomics/T1047/T1047.yaml

Solarigate persistence is achieved via backdoors deployed via various techniques including using PowerShell with an EncodedCommand
Powershell -nop -exec bypass -EncodedCommand <encoded command>
Where the –EncodedCommand, once decoded, would resemble:
Invoke-WMIMethod win32_process -name create -argumentlist ‘rundll32 c:\windows\idmu\common\ypprop.dll _XInitImageFuncPtrs’ -ComputerName WORKSTATION
The EncodedCommand in this atomic is the following: Invoke-WmiMethod -Path win32_process -Name create -ArgumentList notepad.exe
You should expect to see notepad.exe running after execution of this test.
[Solarigate Analysis from Microsoft](https://www.microsoft.com/security/blog/2020/12/18/analyzing-solorigate-the-compromised-dll-file-that-started-a-sophisticated-cyberattack-and-how-microsoft-defe …

new atomic: Create a Process using WMI Query and an Encoded Command

---

atomics/T1003.001/T1003.001.yaml

Adding in a credential dumping test that leverages Out-Minidump.ps1 to dump the contents of lsass to disk for offline extraction
**Details:**
Adversaries can leverage Out-Minidump.ps1 to dump the contents of any processes memory to disk. In this test we are specifically targeting lsass to demonstrate how an attacker could use this script.
**Testing:**
```
PS C:\AtomicRedTeam> Invoke-AtomicTest T1003.001 -TestNumbers 8                                                         PathToAtomicsFolder = C:\AtomicRedTeam\atomic-red-team\atomics
Executing test: T1003.001-8 Dump LSASS.exe Memory using Out-Minidump.ps1
Done executing test: T1003.001-8 Dump LSASS.exe Memory using Out-Minidump.ps1
Directory: C:\Users\Tom Brady\AppData\Local\Temp
Mode                 LastWriteTime         Length Name …
```

Out minidump

---

atomics/T1127.001/T1127.001.yaml
atomics/T1127.001/src/vb.xml

Adding an msbuld inline task that uses Visual Basic in addition to the already existing atomic test using C#. The telemetry you see here will be MSBuild.exe spawning vbc.exe (VB compiler), whereas if the inline task uses C#, you would see MSBuild.exe spawning csc.exe (C# compiler).

MSbuild inline task using Visual Basic

---

atomics/T1003.002/T1003.002.yaml

The cleanup command was missing the pipe symbol so part of the command was being treated as a comment.

Fix to Cleanup Command for T1003.002 Test Number 3

---

atomics/T1490/T1490.yaml

- Modified Windows Backup Admin tests. 
- Added new test for `WBadmin.exe wbadmin delete systemstatebackup -keepVersions:0`
Confirmed operational on server 2016 with Windows backup installed. I also found that wbadmin may not work unless the feature is installed. I didn't dig in much further, but I may modify this in the future with a pre-req to install it.
`Install-WindowsFeature -Name Windows-Server-Backup`

T1490 - WBAdmin

---

atomics/T1003.001/T1003.001.yaml

Added test for procdump using -mm (instead of -ma). This method is similar to -ma, but will produce a mini dump file of lsass. 
Tested on Win10/server 2016. Confirmed Good.

T1003.001 - procdump mini dump

---

atomics/T1485/T1485.yaml

Instead of needing to rerun prereqs before each execution, prereq is now part of attack commands

Create file to delete as part of attack cmds

---

atomics/T1562.002/T1562.002.yaml

Included remove and clear switches for auditpol based logging impairment.
**Details:**
Threat actor can clear the Windows audit policy configuration using remove or clear switches in the auditpo utility.
**Testing:**
Locally tested.

Added auditpol based config clear atomics

---

atomics/T1087.001/T1087.001.md
atomics/T1087.001/T1087.001.yaml

macOS has an /etc/passwd file, but it doesn't actually use it (with a rare exception) and user accounts are not listed there. It's just a standard default file that never changes.
As the header for the file states: 
```
```
**Details:**
just removing macOS from the list of supported OS's for getting a list of users via cat /etc/passwd
**Testing:**
none except for cat'ing my own /etc/passwd to confirm
not aware of any

remove macOS from /etc/passwd test

---

atomics/T1055/T1055.yaml

**Details:**
Since the user is admin the debug privilege is automatically obtained when necessary for the injection
The TTP is also clearer because mimikatz runs as the current user (used for psexec) and not as SYSTEM
**Testing:**
Tested locally, still works.
* before:
* after:
None

T1055: psexec "-s" is not required

---

README.md

**Details:**
The web app for requesting a Slack invite no longer works due to a deprecated Slack API call. Moving requests to a (Red Canary provided) Google Form.
**Testing:**
N/A
N/A

Update the Slack Invite Request URL

---

atomics/T1003.001/T1003.001.yaml
atomics/T1003/T1003.yaml

**Details:**
Based on a discussion with Jannik in the Atomic Red Team Slack, we determined that the Invoke-Mimikatz test that was in [`T1003`](https://attack.mitre.org/techniques/T1003/) belongs in [`T1003.001 - OS Credential Dumping: LSASS Memory`](https://attack.mitre.org/techniques/T1003/001/). I confirmed in the Mimikatz source code that `Invoke-Mimikatz -DumpCreds` calls [`SEKURLSA::LogonPasswords`](https://adsecurity.org/?page_id=1821#SEKURLSALogonPasswords) in Mimikatz which [performs operations specifically on LSASS](https://github.com/gentilkiwi/mimikatz/blob/fe4e98405589e96ed6de5e05ce3c872f8108c0a0/mimikatz/modules/sekurlsa/kuhl_m_sekurlsa.c#L290-L378).
**Testing:**
This test has no external dependencies so no testing was performed.
None

Moving Invoke-Mimikatz test to T1003.001

---

bin/generate-atomic-docs.rb

I'v updated the version number listed in the navigator layer json files to avoid a version mismatch warning when loading the layer on the Mitre ATT&CK Navigator.

update nav layer version

---

atomics/T1003.001/T1003.001.yaml
atomics/T1033/T1033.yaml
atomics/T1053.005/T1053.005.yaml
atomics/T1055.012/T1055.012.yaml
atomics/T1055/T1055.yaml
atomics/T1059.005/T1059.005.yaml
atomics/T1069.002/T1069.002.yaml
atomics/T1070.001/T1070.001.yaml
atomics/T1110.003/T1110.003.yaml
atomics/T1115/T1115.yaml
atomics/T1134.001/T1134.001.yaml
atomics/T1135/T1135.yaml
atomics/T1204.002/T1204.002.yaml
atomics/T1555/T1555.yaml
atomics/T1558.003/T1558.003.yaml
atomics/T1564/T1564.yaml
atomics/T1566.001/T1566.001.yaml

Add the `-UseBasicParsing` flag for web requests for test systems where Internet Explorer has not been configured for first time use. This avoid an error like the following that prevents the code from executing correctly:
`iwr : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try again`

add usebasicparsing flag

---

atomics/T1027/T1027.yaml

PR #1418 made a change to an input arg so that it would work with the powershell prereq commands but since the attack command executor is "command_prompt" and not "powershell" the change broke the attack command. There are multiple ways to address this mismatch in executors and still use environment variable but in this case I didn't see a great value in having the exe defined in an input arg and there were pieces of that path hard coded in the prereq and cleanup commands already so I removed the input arg altogether and use hard coded values which makes it easy to use $env:Temp for the PowerShell parts and %temp% for the command_prompt.

small correction to handle cmd/ps executors

---

atomics/T1218/T1218.yaml

This atomic was expecting to find protocolhandler.exe in the "program files" directirt but in my case it is found in "program files (x86)" and which directory it is in is related to whether 32 bit or 64 bit office is installed. This modification determines the path programatically so it will work from either directory.

programatically determine location of protocolhandler

---

atomics/T1003.001/T1003.001.yaml

This way the test will be valid for future release of .NET. 
It has already jump from 5.0.3 to 5.0.5 while I was building this test.
**Details:**
**Testing:**

Use wildcard '*' for .NET path

---

atomics/T1030/T1030.yaml

**Details:**
Fixes the error: `/usr/bin/sh: 1: Syntax error: ";" unexpected` 
when running `Invoke-AtomicTest T1030 -GetPrereqs`
**Testing:**
Invoke-AtomicTest T1030 -GetPrereqs

Fixed an issue where -CheckPrereqs could not create the required files.

---

atomics/T1021.002/T1021.002.yaml

**Details:**
PSExec was required but not a defined dependency. This adds psexec as a configurable dependency.
**Testing:**
`bin/validate-atomics.rb` showed no errors. Tested and works fine in Windows Sandbox with Windows 10 2004.

Take 2 on making psexec a configurable dependency.

---

atomics/T1003.002/T1003.002.yaml

**Details:**
seemed to download the module to `$Env:Temp` then run from `.\`, so I changed both to `$Env:Temp`
**Testing:**
Ran in Win 10, successfully got usernames & hashes!
n/a

Fix file path for PowerDump Import

---

atomics/T1003.001/T1003.001.yaml

**Details:**
In some cases, lsass.exe minidump files are signatured by AV and deleted. It's not unusual for the binary that initiated the lsass dump to be left on disk and not treated as malicious.
The dll loaded into this bin for minidumping (dgbhelp) writes the minidump to disk, but before this binary closes the file handle to the minidump, it re-reads the contents into memory. It then closes the file handle and immediately deletes the minidump.
There may exist a race between the binary deleting the minidump file after a `close(handle)` and with AV detecting and deleting the minidump. In either case, the output is safe in memory and passed to a xor function which then re-writes the xor'd data to disk, where it can be safely copied off.
**Testing:**
This tests for both the use of …

adds additional lsass dump test

---

atomics/T1518/T1518.yaml
atomics/T1553.004/T1553.004.yaml

**Details:**
- test 53bcf8a0-1549-4b85-b919-010c56d724ff in T1553.004 had 'command_prompt' as its dependency_executor_name, but its dependency commands are written in sh.
- test cc4a0b8c-426f-40ff-9426-4e10e5bf4c49 in T1553.004 had 'command_prompt' as its dependency_executor_name and executor name, but its commands are written in sh.
- test c49978f6-bd6e-4221-ad2c-9e3e30cc1e3b in T1518 had 'command_prompt' as its executor name, but its commands are written in sh.
**Testing:**
None.
None.

Fix platform incompatible executors in T1553.004 and T1518

---

atomics/T1087.002/T1087.002.yaml

**Details:**
Attackers will attempt to enumerate AD objects with unconstrained delegation in order to attempt to ultimately escalate privileges in a domain. AD can be queried for the following UserAccountControl attribute: `TRUSTED_FOR_DELEGATION | 0x80000 | 524288`
**Testing:**
Tested on Win10 attached to a domain w/ DFL 2016
N/A

adds test for enumerating unconstrained delegation

---

atomics/T1082/T1082.yaml

**Details:**
The path was referring to T1595.002 instead of T1082, where the script resides. Due to the moved requested in #1320 and missed.
**Testing:**
Working with the new path.
#1320

Fixed bug in script path

---

atomics/T1562.004/T1562.004.yaml

**Details:**
Added Disable Microsoft Defender Firewall via Registry as Windows firewall can be disabled via a registry key. This demonstrates disabling the public profile.
**Testing:**
Local Atomic testing 
N/A

Added Disabling Firewall via Registry

---

atomics/T1566.001/T1566.001.yaml

**Details:**
#bugfix: downloaded html page instead of file previously
$url = 'https://github.com/redcanaryco/atomic-red-team/raw/master/atomics/T1566.001/bin/PhishingAttachment.xlsm'
#bugfix: downloaded file was corrupted and had bigger size
Invoke-WebRequest -Uri $url -OutFile $fileName
found a bug, other than specified in the yaml: For Some Reason Powershell uses %temp% folder instead of the current directory (of powershell).
**Testing:**

T1566.001-1 download bugfixes

---

atomics/T1505.003/T1505.003.yaml

Cleanup now just deletes the 3 webshell files instead of the whole web directory. Fixed mispelled file name. Add xcopy arguments so users not prompted about destination location.

safer cleanup, correct filename

---

bin/generate-atomic-docs.rb

**Details:**
Modifies the attack navigator generated layer json files and adds a comment technique in each layer that links back to the atomic md file for that technique. 
**Testing:**
ran `bin/generate-atomic-docs.rb` then used the generated layers (all and linux) and uploaded into https://mitre-attack.github.io/attack-navigator/. Test URLs worked as expected. Please see screenshot below for details:
closes issue # 1175 https://github.com/redcanaryco/atomic-red-team/issues/1175

adding url md file for each atomic as a comment

---

atomics/T1053.005/T1053.005.yaml
atomics/T1055.012/T1055.012.yaml
atomics/T1055/T1055.yaml
atomics/T1059.005/T1059.005.yaml
atomics/T1070.001/T1070.001.yaml
atomics/T1115/T1115.yaml
atomics/T1204.002/T1204.002.yaml
atomics/T1204.002/src/Invoke-MalDoc.ps1
atomics/T1555/T1555.yaml
atomics/T1564/T1564.yaml
atomics/T1566.001/T1566.001.yaml

The Invoke-Maldoc.ps1 script used by many atomics is being moved into this repo from the Invoke-AtomicRedTeam repo (the PowerShell Execution Framework) because it is a more fitting home for it.
This was also done in preparation for the Invoke-AtomicRedTeam tool being added to the PowerShell Gallery for easy install.
For now, there is still a copy of Invoke-Madoc in the Invoke-AtomicRedTeam repo but when that is removed, users whose atomic definition files still point to the old location will need to update their files in order for the Maldoc atomics to continue to work.

moving invoke-maldoc into art repo

---

atomics/T1132.001/T1132.001.yaml

Added a new test - XOR Encoded data to T1132.001 'Data Encoding: Standard Encoding
**Details:**
The new test added is for windows powershell. It uses the XOR encoding technique which is a standard encoding technique found in few C2 frameworks. The test is configurable with three parameters - Destination URL, XOR key, Plain text. The XOR logic has been referenced from https://gist.github.com/loadenmb/8254cee0f0287b896a05dcdc8a30042f
**Testing:**
Tested on Powershell version 5.1.19041.610

Added a new test - XOR Encoded data to T1132.001 'Data Encoding: Standard Encoding

---

atomics/T1003.006/T1003.006.yaml
atomics/T1055/T1055.yaml
atomics/T1110.001/T1110.001.yaml
atomics/T1110.003/T1110.003.yaml
atomics/T1207/T1207.yaml
atomics/T1558.001/T1558.001.yaml

**Details:**
Sprinkle some "Active Directory" string here and there to ensure people who search for AD tests find them easily using a text search in the repo. Why be subtle? :)
**Testing:**
None, but the CI will say if there is no syntax issue
As [discussed on Slack](https://atomicredteam.slack.com/archives/CB5DLF002/p1625657404218100), thanks to @amashinchi-rc for the idea!

Improve discoverability of "Active Directory" attacks

---

atomics/T1003/T1003.yaml

Implemented test to emulate credential steal from RDP.
https://www.n00py.io/2021/05/dumping-plaintext-rdp-credentials-from-svchost-exe/

Dump svchost.exe to gather RDP plaintext credential

---

atomics/T1135/T1135.yaml

**Details:**
Fixed key name of `elevation_require` to `elevation_required`
**Testing:**

T1135 - Fixed key name in executor test

---

atomics/T1105/T1105.yaml

Tested on Windows 10. Referred to https://www.exploit-db.com/exploits/48815

Update T1105 to include file download using finger

---

atomics/T1572/T1572.yaml
atomics/T1572/src/T1572-doh-beacon.ps1
atomics/T1572/src/T1572-doh-domain-length.ps1

**Details:**
Adds three tests for DNS over HTTPS utilizing the DNS tests from T1071.004, but tunneled over DoH.
This does not include the dnscat C2 in test 4.
**Testing:**
```
PS D:\Projects\atomic-red-team> Invoke-AtomicTest T1572
PathToAtomicsFolder = D:\Projects\atomic-red-team\atomics
Executing test: T1572-1 DNS over HTTPS Large Query Volume
Done executing test: T1572-1 DNS over HTTPS Large Query Volume
{"Status":2,"TC":false,"RD":true,"RA":true,"AD":false,"CD":false,"Question":[{"name":"atomicredteam.673087.127.0.0.1.xip.io.","type":16}],"Comment":"Name servers did not respond [166.78.161.251, 192.237.180.202]."}
{"Status":2,"TC":false,"RD":true,"RA":true,"AD":false,"CD":false,"Question":[{"name":"atomicredteam.543150.127.0.0.1.xip.io.","type":16}],"Comment":"All …
```

T1572 Protocol Tunneling (DNS over HTTPS)

---

bin/generate-atomic-docs.rb

To avoid a version number mismatch warning when using the Mitre Att&ck Navigator layer, I've bumped the json layer version.

bump layer version

---

atomics/T1113/T1113.yaml

**Details:**
Add a test for [T1113: Screen Capture](https://attack.mitre.org/techniques/T1113/) that uses the `CopyFromScreen` .NET API ([docs.microsoft.com](https://docs.microsoft.com/en-us/dotnet/api/system.drawing.graphics.copyfromscreen)).
Similar implementations have been used both in the APT29 (2019) and Carbanak+FIN7 (2020) ATT&CK Evaluations ([center-for-threat-informed-defense/adversary_emulation_library](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/search?q=CopyFromScreen)).
**Testing:**
Tested locally via `Invoke-AtomicTest`.
N/A

Add T1113 test for CopyFromScreen API

---

atomics/T1485/T1485.yaml

**Details:**
`dd of=#{file_to_overwrite} if=#{overwrite_source}` has neither timeout nor size limit, and will fill the disk (T1499) vs just wiping the file, preventing automation or further testing.
**Testing:**
Local on ubuntu
N/A

T1485 - constrains dd to write the original file size when overwriting

---

atomics/T1550.003/T1550.003.md
atomics/T1550.003/T1550.003.yaml

Hello team,
**Details:**
The previous command fails to execute this mimikatz module.
_#{mimikatz_exe} # kerberos::ptt #{user_name}@#{domain}_
This separates the command like 
$#{mimikatz_exe} -> launch mimikatz console
mimikatz $ #                                                -> error
mimikatz $ kerberos::ptt                            -> error by no argument
mimikatz $ #{user_name}@#{domain}     -> error by no such module
In addition, this techniques is about Pass the Ticket , thus I modified the argument description to understand more easily.
**Testing:**
I have done the test on my local Lab built with DetectionLab (https://github.com/clong/DetectionLab)
I didn't find the associated issue related to this at the present.
Thank you.
Best regards

T1550.003 pass the ticket by mimikatz patch

---

atomics/T1003.004/T1003.004.yaml

this avoids the test from hanging when running twice in a row

overwrite existing output without prompt

---

atomics/T1558.003/T1558.003.yaml

**Details:**
If we want to detect the service ticket request (sign of the kerberoasting attack) server-side we need to ensure it's actually requested.
The TGT is purged too but given that the long term session keys are in LSASS it will be re-fetched too silently
**Testing:**
* Proof of the issue: it's the 2nd kerberoasting I'm doing here and since all services tickets are already obtained there's no request:
* Adding a "klist purge" beforehand. Notice that the TGT is re-obtained, and also the service ticket:
None

Kerberoasting: purge tickets before launching attack to ensure cached ones aren't used

---

atomics/T1555.003/T1555.003.yaml

Adding a 5th test that simulates access to Opera Login Data within Windows.
**Testing:**
Tested on Windows 10. If using the Get-PreReqs parameter to install Opera automatically, I would recommend changing the timeout seconds to 900 (append -TimeoutSeconds 900 after -GetPreReqs) to ensure that there is enough time to download Opera before the GetPreReqs command times out, as it is a fairly large download.

Adding T1555.003 Test 5 - Simulating Access to Opera Login Data

---

atomics/T1497.001/T1497.001.yaml

This test is a second method of detecting virtualization within Windows by querying the WMI manufacturer/model.
**Testing:**
Tested with physical Windows 10 machine, VMware Windows 10 instance, VirtualBox Windows 10 instance, and Hyper-V Windows 10 instance, all of which had the expected result.

Adding T1497.001 Test 4

---

atomics/T1550.003/T1550.003.yaml

Hi,
**Details:**
This PR extends the T1550.003 atomic by adding a use case where a stolen TGT is reused on another system to request a TGS.
The ticket crafting/request is performed via Rubeus, while the initial TGT is crafted via PsExec on a remote host.
**Testing:**
Local testing

Extend T1550.003 with new PTT attack

---

atomics/T1098.001/T1098.001.yaml
atomics/T1110.001/T1110.001.yaml
atomics/T1110.003/T1110.003.yaml

**Details:**
AzureAD allways install when check prereq
I use `-ErrorAction SilentlyContinue` to not display error on screen when missing.
Now install only 1 time

Fix prereq_command Get-Module AzureAD

---

atomics/T1027/T1027.yaml

As noted in issue #1696 this atomic was not running correctly using the execution framework. I tried to move the command to a batch file but found the same issue. I moved this test to a "manual" test since for the time being, this is the only way I know to make it work.

making test manual to avoid execution errors

---

atomics/T1036.003/T1036.003.yaml

**Details:**
sh with no args doesn't exit until the timeout, feeding it a command to prompt it to exit achieves the MITRE behavior without relying on the external ART timeout. Also on some of my VMs the ART enforced default timeout didn't exit properly, hanging the test.
**Testing:**
local `Invoke-AtomicTest -AtomicTechnique T1036.003 -TestNumbers 2`
N/A

T1036.003-2 let sh exit vs forcing hard-timeout

---

atomics/T1053.006/T1053.006.yaml

**Details:**
Fixes a typo preventing `systemd-run` with `--on-calendar` from working.
ref: https://man7.org/linux/man-pages/man1/systemd-run.1.html
**Testing:**
local/manual `Invoke-AtomicTest -AtomicTechnique T1053.006`
N/A

fix systemd-run tests

---

atomics/T1219/T1219.yaml

Fix errors when try t1219
- add `-Wait` otherwise try to launch exe before installation is finish
- msi use `/quiet` not "/S"
- Fix the path of LMIIgnition.exe
For ScreenConnect did not find the way to start it like the other

T1219 fix errors

---

atomics/T1083/T1083.md
atomics/T1083/T1083.yaml

**Details:**
This pull request changes the `Atomic Test #3 - Nix File and Diectory Discovery` to `Atomic Test #3 - Nix File and Directory Discovery`, fixing the spelling mistake in the title and also in the hyperlink.

Fix spelling mistake 'diectory' to 'directory'

---

bin/generate-atomic-docs.rb

Bumping the navigator json version avoids a warning when importing the layer to the MITRE ATT&CK Navigator

bump navigator layer version

---

atomics/T1550.002/T1550.002.yaml

**Details:**
Fix : 
- prereq_command (correct ouptut exit)
- executor
**Testing:**
test run even if I have #crackmapexec internal error 😄 
None

T1550.002 fix test 2

---

atomics/T1087.001/T1087.001.yaml

Updating T1087.001 Test 5 to automatically install the login package that contains lastlog, as well as resolving an issue with its prereqs that results in an unexpected eof error.
**Testing:**
Tested with Ubuntu and Kali

Automating getprereqs and fixing prereq errors for T1087.001 Test 5

---

atomics/T1218.011/T1218.011.yaml

**Details:**
Execution of non-dll using rundll32.exe
**Testing:**
Windows10

T1218.011_update

---

atomics/T1003.003/T1003.003.yaml

**Details:**
Alternative to the recently added "Create Volume Shadow Copy remotely with WMI" https://github.com/redcanaryco/atomic-red-team/pull/1640
This version uses WMIC for remote execution, and launches esentutl to create the shadow copy itself
**Testing:**
Tested locally
None

New technique "Create Volume Shadow Copy remotely (WMI) with esentutl"

---

atomics/T1046/T1046.yaml

**Details:**
Testing the T1046-2 I appreciate that the prerequisites were incomplete, since after installed all of them, the test still fails because some depencies that were not installed:
- nc
- telnet
Moreover, nmap displays an error message requiring administrator privileges.
Here are the commands:
```
PS /home/admin> Invoke-AtomicTest T1046 -TestNumbers 2 -CheckPrereqs                                    
PathToAtomicsFolder = /home/admin/AtomicRedTeam/atomics
CheckPrereq's for: T1046-2 Port Scan Nmap                                                               
Prerequisites met: T1046-2 Port Scan Nmap                                                               
PS /home/admin> Invoke-AtomicTest T1046 -TestNumbers 2 -GetPrereqs …
```

T1046 2 fix prerequisites

---

atomics/T1059.006/T1059.006.yaml

Old link gave 404. Also new link uses permalink instead of pointing to "master" which can change over time.

update script link

---

atomics/T1123/T1123.yaml
atomics/T1125/T1125.yaml

**Details:**
Add test from SigmaHQ sysmon_susp_mic_cam_access.yml
leaves the normal traces of an application in the registry...
**Testing:**
None

Sigma sysmon_susp_mic_cam_access

---

atomics/T1090.003/T1090.003.yaml

Adding T1090.003 Test 3, which will launch the tor proxy service on Debian distros and Ubuntu. 
**Testing:**
Tested on Ubuntu, Kali, and Parrot OS.

Adding T1090.003 Test 3 - Tor Usage on Debian/Ubuntu

---

atomics/T1112/T1112.yaml

**Details:**
This atomic tests for registry changes made by BlackByte ransomware that allows for elevated remote access privileges and long file names which are required before encrypting.
**Testing:**
Windows 10.

Initial creation of BlackByte Ransomware Registry Changes atomic

---

atomics/T1090.003/T1090.003.yaml

This test is designed to launch the Tor proxy service on MacOS.
**Testing:**
Tested on MacOS Mojave and Catalina. When getting prereqs, my testing found that in Mojave, it can take longer than the 120 second default to finish the prereq install, so it might be best to append "-timeoutseconds 300" or greater to the end of the getprereq command if it fails the first time.

Adding T1090.003 Test 4 - Tor Proxy Usage on MacOS

---

atomics/T1217/T1217.yaml

Adding T1217 Test 8 - List Safari Bookmarks for MacOS. This test locates any Safari bookmarks files and outputs the file paths to a text document.
**Testing:**
Tested on MacOS Mojave and Catalina. Please note that depending on the size of the drive it is being ran on, this test might take longer than the default 120 seconds. When testing on a 30 GB Mojave VM, the test only took about 20 seconds, but on a 1 TB Catalina physical machine, it took closer to 3.5 minutes.

Adding T1217 Test 8 - List Safari Bookmarks

---

atomics/T1059.005/T1059.005.yaml

**Details:**
Fixed the prereq command so that the New-Item came before Invoke-WebRequest and got rid of the Copy. The Invoke -OutFile changed to the vbscript path. On the cleanup command, I got rid of it deleting the vbscript so that the prereq only needs to be run once.
**Testing:**
Tested on Windows10 to make sure that it functioned as expected.

T1059.005 Fix Cleanup and Prereq

---

atomics/T1112/T1112.yaml

**Details:**
Per request from Carrie Roberts: "...be able to run the cleanup commands without generating errors if files or keys to be deleted are already deleted...". Fixed cmd and pwsh cleanup commands per Carrie's suggestions.
**Testing:**
Windows 10.  Tested via Invoke-AtomicTest.  Ran individual test, followed by cleanup command, followed by cleanup command again.  Did this process for both Cmd and Pwsh

Fixing Blackbyte Cleanup Commands

---

atomics/T1003.007/T1003.007.yaml

**Details:**
Adding T1003.007 Test 3 - Capture Passwords with MimiPenguin. This test is designed to run the MimiPenguin script, which takes advantage of a vulnerability in Ubuntu-based distros, as well as certain versions of GNOME Keyring, in order to capture passwords in cleartext. Upon successful execution, user passwords will be exported to a file and displayed on-screen.
**Testing:**
Tested on Ubuntu 20.04.3, Linux Mint 23.0, and Zorin OS 16, and the atomic was able to retrieve the logged-in user's password. Also tested on Kali build 2021.4a, but no passwords were retrieved due to the vulnerability not existing in that version of Kali.

Adding T1003.007 Test 3 - MimiPenguin Usage

---

atomics/T1083/T1083.yaml

Adding T1083 Test 5 - Simulating MAZE Directory Enumeration. This test is designed to simulate the directory enumeration function used by MAZE ransomware (Windows).
**Testing:**
Tested on 3 Windows 10 machines with no issues.

Adding T1083 Test 5 - Simulating MAZE Directory Enumeration

---

atomics/T1112/T1112.yaml

**Details:**
Fix the cleanup option.
As the test deactivates the reg tools, it goes through a powershell command
**Testing:**
None

Fix reg cleanup T1112 Test 9

---

atomics/T1003.001/T1003.001.yaml

wce executable only displays a message about how to show the help but doesn't do the intended credential dumping.

delete broken wce test

---

atomics/T1112/T1112.yaml

**Details:**
As cmd is disable `cleanup_command` failed
So change to powershell executor
**Testing:**
Cmd is disable and open with a message like  "your administrator have..." (My is in French :wink:) 
after Cleanup cmd is back
close #1817

Fix test 10

---

atomics/T1112/T1112.yaml

**Details:**
fix bad `“Service”` to `"Service"`
PS the `"` can be remove as the string to put in Default have no space .
**Testing:**
Windows 10x64 + Sysnon + Aurora (Sigma rule)
None

Fix T1112 test 33-34

---

atomics/T1082/T1082.yaml

**Details:**
csrutil is commonly used by malware and post-exploitation tools to determine whether certain files and directories on the system are writable or not. This command checks and displays System Integrity Protection status.
**Testing:**
Copy pasted commands into terminal window to confirm. tested on Monterey 12.3.1

Update T1082.yaml - Add System Integrity Protection status (MacOS)

---

atomics/T1053.005/T1053.005.yaml

The time in the YAML file should be wrapped in single quotes due to the colon being interpreted to have special meaning.
**Details:**
The colon in the time value is interpreted to have a special meaning, so it should be wrapped by single quotes to ensure the time value inserted is recognized by schtasks
**Testing:**
The current MD generated by the YAML shows the time as 27900 likely due to the missing quotes in the time variable within the YAML code.

Surround time variable in single quotes

---

atomics/T1036/T1036.yaml

**Details:**
Rewriting T1036 test 1 in Powershell. With the way the test was written in command prompt previously, it would cause automatic execution to halt due to the fact that copying cmd.exe to another location using command prompt creates a lock on the process, preventing it from being successfully copied. Additionally, added commands to kill the new command prompt window after 5 seconds so that there is not a spare command prompt window left open. 
**Testing:**
Tested on 2 Windows 10 machines. 
See details. I don't believe there are any open issues for this in Github.

Rewriting T1036 Test 1 in Powershell

---

atomics/T1564.006/T1564.006.yaml

**Details:**
`prereq_command` did not work.
**Testing:**
Windows 10 x64 without virtualbox
Can not find a way to fix cleanup (need to be run twice)

Fix prereq_command test 2

---

atomics/T1573/T1573.yaml

**Details:**
Replacing `.domain` with `.example` in observation of RFC 2606, to avoid future potential complications if and when the `.domain` namespace becomes available like `.domains` is.
https://en.wikipedia.org/wiki/.example
https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains#D
**Testing:**
N/A

Update T1573.yaml - RFC 2606 compliant TLD.

---

atomics/T1197/T1197.yaml

**Details:**
The "timeout" command doesn't work in batch scripts or otherwise background-ed command prompts. If you run the T1197-3 command using "Invoke-Atomic" then you will see the following error and the technique will fail.
```
ERROR: Input redirection is not supported, exiting the process immediately.
```
As an alternative we can use the `ping` utility and just specify that it should only send 5 packets (1 second / packet = 5 seconds).
**Testing:**
Works on my machine 😄 In all seriousness though this is a minor change that just uses the `ping` utility.
See details

T1197-3: Update timeout command to ping

---

atomics/T1105/src/T1105.bat

**Details:**
Hey folks, I submitted a PR request yesterday for the same thing I found again today in a different technique (https://github.com/redcanaryco/atomic-red-team/pull/1865). 
The "timeout" command doesn't work in batch scripts or otherwise background-ed command prompts. If you run the T1105-20 command using "Invoke-Atomic" then you will see the following error and the technique will fail.
```
ERROR: Input redirection is not supported, exiting the process immediately.
```
As an alternative we can use the ping utility and just specify that it should only send 10 packets (1 second / packet = 10 seconds).
**Testing:**
Minor change that uses `ping`.
See details

T1105: Update timeout to ping

---

atomics/T1039/T1039.yaml

**Details:**
Very simple tests to copy over admin share
match sigma [proc_creation_win_susp_copy_lateral_movement.yml](https://github.com/SigmaHQ/sigma/blob/f4a696471f2d8868a1a730213354736cd2d59933/rules/windows/process_creation/proc_creation_win_susp_copy_lateral_movement.yml)
**Testing:**
windows 10
English spelling mistakes

Add simple T1039 tests

---

atomics/T1546.012/T1546.012.yaml

**Details:**
In current version of code target_binary: default: creating following registry keys: "C:", "Windows", "System32" and then "notepad.exe" or "calc.exe" which is incorrect and we should create key with filename only how its done in other registry keys
**Testing:**
Tested on Windows 10 x64
None

T1546.012: change target_binary path

---

atomics/T1219/T1219.yaml

**Details:**
This test launches RemotePC, which is an application that can be utilized by threat actors for remote access to a host. 
**Testing:**
Tested on 3 WIndows 10 machines.

Adding T1219 Test 7 - RemotePC Executable Ran

---

atomics/T1562.006/T1562.006.yaml

Adding test #3 to simulate the removal of the Powershell provider ETW telemetry source.
Details:
This test installs PSExec to open a command prompt with SYSTEM privileges to allow the command line tool "logman.exe" to disable the Powershell ETW provider. This provider is used as a common source of telemetry for AV/EDR solutions. 
Testing:
Testing for this request was done on two, separate Windows 10 machines. 
Associated Issues:

Adding T1562.006 Test Number 3

---

atomics/T1555.003/T1555.003.yaml

**Details:**
(For Challenge that ends May 18th 2022) and using Lazagne.py to dump Firefox creds
Using SH instead of BASH
Utilized PromptForInputArgs to change it from just Browser firefox to other modules such as "all"
**Testing:**
Credential Dump on Ubuntu 20.04.4 (Desktop) LTS Focal Fossa Firefox Browser.
Cleanup works, PromptForInputArgs works
umm, maybe the GetPreReqs for finding git, python3, and pip things could be better.

Challenge bounty-T1555.003 Linux Dump Creds Browser

---

atomics/T1555.003/T1555.003.yaml

**Details:**
This test copies Chrome's "Login Data" and "Login Data For Account" files to the tmp directory, simulating the tactics that an adversary might use to exfiltrate credentials to later be harvested offline with malware/tools like CookieMiner. 
**Testing:**
Tested on MacOS Catalina.

Adding T1555.003 Test 14  - Chrome Login Data Access (MacOS)

---

atomics/T1110.003/T1110.003.yaml

Perform a domain password spray using the same core method of the [DomainPasswordSpray tool](https://github.com/dafthack/DomainPasswordSpray) but without all the extra code that makes the script get blocked by many AVs. 
This atomic test will attempt a single password against all users in a password list at $env:Temp\usersdpsLight.txt. You can create this file manually or with the automated prereq_command. The prereq_command will limit the user list to 200 users by default to help you avoid massive account lockout.

add a lightweight password spray test

---

atomics/T1546.003/T1546.003.yaml

**Details:**
- Additional WMI Persistence test using `ActiveScriptEventConsumer`. This is often overlooked in detection rules. The test does the same thing as the `CommandLineEventConsumer` test, executes `notepad.exe` 4 minutes after the endpoint is rebooted (using vbscript).
- The new test also uses the older `Set-WmiInstance` that has different arguments than `New-CimInstance`, this is often overlooked in detection rules
- The slash in `root\subscription` can be both `\` and `/` it is still valid. Again often overlooked in detection rules. Now the tests use both combinations.
- Renamed the original test so that they are distinguishable and the PowerShell objects don't clash.
**Testing:**
Windows 10

WMI Persistence using ActiveScriptEventConsumer

---

atomics/T1547.003/T1547.003.yaml

**Details:**
I just tested on a domain joined machine and the w32time service was starting by default, so I'm adding the `net stop w32time` to first stop the service. If it's not running, it won't be an issue, the rest of the commands will execute successfully. Also it seems that in most cases, this service is enabled by default (it wasn't on my test VMs for some reason), so I'm re-enabling it at the end of the clean up commands.
**Testing:**
On domain-join host
N/A

Updating T1547.003 to stop w32time first

---

atomics/T1543.004/T1543.004.yaml

**Details:**
The launch daemon does `touch /tmp/T1543_004_atomicredteam.txt`.  This changes adds that file to the cleanup.
**Testing:**
local
none

T1543.004 cleanup file created by launch daemon

---

atomics/T1219/T1219.yaml

**Details:**
This test is designed to install and execute the NetSupport tool that is capable of RAT execution. A recent trend by threat actors, once a foothold is established, maintain long term persistence using third party remote services such as NetSupport to provide the operator with access to the network using legitimate services.
**Testing:**
Testing for this atomic test was done/verified on a Windows 10 machine over the course of two weeks. 
NA

Adding T1219-8 | NetSupport - RAT Execution

---

atomics/T1046/T1046.yaml

Updates to T1046 Test 1 and 2
**Details:**
For Test 1:
- Added ability to pass in `host` as an argument instead of having hard coded IP address
- Changed the shell executor from `sh` to `bash`.  Using `sh`, an error was occurring in the execution causing all ports to report as closed.  
- Made the script one line.  The new line replacement that occurs in the `Invoke-ExecuteCommand` causes a semicolon to be added after the `do`.  This caused a syntax error during execution.  
- Redirect any errors to `/dev/null` to cleanup the output
For Test 2:
- Add `sudo` to nmap command
**Testing:**
Tested locally on Linux host

Updates to T1046-1,2

---

atomics/T1059.003/T1059.003.yaml
atomics/T1059.003/src/t1059.003_cmd.cmd

**Details:**
Simulate Raspberry Robin using the "standard-in" command prompt feature cmd `/R <` to read and execute a file via cmd.exe
This will execute calc.exe by reading contents of the CMD file.
**Testing:**
Local testing

T1059.003 Read CMD from file and execute

---

atomics/T1056.001/T1056.001.yaml

**Details:**
This change corrects the `echo` command in the execution of `T1056.001 - SSHD PAM keylogger`. The previous command did not update the file.
**Testing:**
Run the commands in the test and verify the line was added to `/etc/pam.d/sshd`
None

T1056.001 - fix SSHD PAM keylogger command

---

atomics/T1112/T1112.yaml

**Details:**
Reg.exe need to use `"` when key path have a space
**Testing:**
None

T1112 Fix space in registry key name

---

atomics/T1546.015/T1546.015.yaml

just fix the path of the dll
No need to escape '\\' in cmd Otherwise the key created  with '\\\\'

T1546.015 Fix windows path

---

atomics/T1529/T1529.yaml

**Details:**
Test T1529 windows logoff fail 
`/t` can not be use with `/l`  -> https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/shutdown
<html><body>
/l | Logs off the current user immediately, with no time-out period. You cannot use /l with /m or /t.
-- | --
</body>
</html>

T1529 Fix windows Logoff

---

atomics/T1070.006/T1070.006.yaml

leave the prereq files there so only have to "get prereqs" once and then can run test over and over again

leave prereqs

---

atomics/T1218/T1218.yaml

The same test was also found [here](https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1216/T1216.md#atomic-test-1---syncappvpublishingserver-signed-script-powershell-command-execution) and it is a better fit in T1216, so removing from T1218

remove duplicate test

---

atomics/T1105/T1105.yaml

iwr or Invoke Web-Request download. Use 'iwr' or "Invoke-WebRequest" -URI argument to download a file from the web. Note: without -URI also works in some versions.
Details:
The iwr inbuilt powershell cmdlet utility can be used to to download any http/https file and can be leveraged further to invoke many further such web requests. There was no dedicated atomic in place for the same functionality hence raised new.
Testing:
Testing done successfully under ART environment and lab.

New Atomic test 29 - iwr download

---

atomics/T1548.002/T1548.002.yaml

Proposing a new atomic test "Disable UAC admin consent prompt". The existing atomic test with guid 9e8af564-53ec-407e-aaa8-3cb20c3af7f9) disables UAC by setting "EnableLUA" registry value to 0. UAC can also be disabled by setting "ConsentPromptBehaviorAdmin" registry value to 0 (https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-gpsb/341747f5-6b5d-4d30-85fc-fa1cc04038d4). This registry value has been altered by several malwares in the past (https://cloudsek.com/technical-analysis-of-medusalocker-ransomware/, https://blogs.blackberry.com/en/2022/01/threat-thursday-purple-fox-rootkit, https://blogs.blackberry.com/en/2021/06/threat-thursday-avaddon-ransomware-uses-ddos-attacks-as-triple-threat). Hence, proposing a new atomic test with guid 251c5936-569f-42f4-9ac2-87a173b9e9b8 …

New Atomic-Test

---

atomics/T1548.002/T1548.002.yaml

Changing the description of atomic test 251c5936-569f-42f4-9ac2-87a173b9e9b8 from "modifying the registry key" to "setting the registry key".  In this context, the word "setting" sounds more appropriate than "modifying".

Modify description of "Disable UAC admin consent prompt"

---

atomics/T1491.001/T1491.001.yaml

**Details:**
After encrypting files, ransomwares modify the Windows LegalNoticeCaption and LegalNoticeText registry keys to display a ransom message to victim at logon. We have added a new atomic test with guid ffcbfaab-c9ff-470b-928c-f086b326089b that sets two registry keys HKLM\SOFTWARE\Micosoft\Windows\CurrentVersion\Policies\System\LegalNoticeCaption and HKLM\SOFTWARE\Micosoft\Windows\CurrentVersion\Policies\System\LegalNoticeText to display a ransom message. While executing this atomic test, the value for these registries can be configured using the switch -PromptForInputArgs. This technique has been used by many ransomwares in the past including SynAck, Grief, Maze, Pysa, Spook, DopplePaymer, Reedemer and Kangaroo.  
**Testing:**
For testing, we added the proposed atomic test to our …

Added a new atomic test

---

atomics/T1505.003/T1505.003.yaml

**Details:**
xcopy doesn't work when there is a trailing \ in a path.  default: PathToAtomicsFolder\T1505.003\src\ caused the "Invalid path" error Removing the trailing \ fixes the issue
**Testing:**
Tested locally via remote execution of the test

Remove trailing \ from web_shells default path

---

atomics/T1027.006/T1027.006.yaml
atomics/T1027.006/bin/T1027_006_Remote.html

Add Atomic for HTML smuggling
**Details:**
HTML file that will download an ISO to the current user's Downloads folder.
**Testing:**

t1027-006-html-smuggling

---

atomics/T1003.002/T1003.002.yaml

the previous way of listing shadow copies didn't work from an unelevated context and since being unelevated is the key to this exploit it was important to change this.

HiveNightmare simplifications

---

atomics/T1098.001/T1098.001.yaml

**Details:**
The issue was that "Get-AzureADServicePrincipal" and "Get-AzureADApplication" may return several results matching the provided name which is not handled properly by the code which will crash. The solution is to select only the first object.
I took the opportunity for a couple minor improvements in the code of those two tests.
**Testing:**
Before:
```terminal
> Invoke-AtomicTest T1098.001 -TestGuids "b8e747c3-bdf7-4d71-bce2-f1df2a057406" -InputArgs @{"username"="redacted" ; "password"="redacted" ; "service_principal_name"="Yammer" }
[...]
New-AzureADServicePrincipalKeyCredential : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'ObjectId'. Specified method is not supported.
[...]
Connect-AzureAD : Cannot convert 'System.Object[]' to the type …
```

Fix bug where the search returns multiple objects by selecting only the first

---

atomics/T1484.002/T1484.002.yaml

**Details:**
Azure AD has two kinds of federated domains. The one that can be used to authenticate on AAD, as an AAD user, and the one that can be used to authenticate as a guest user (also called external identity).
The current implementation of the attack seems to work but actually it uses the cmdlets to create a federated domain for external identities which is not the thing we want to showcase this ATT&CK technique. Since such a federated domain does not allow to authenticate as an AAD user. Sorry for missing this when I supervised the initial work on this ART test (#1607).
This new implementation uses AADInternals which is a popular attack framework for AAD and which offers exactly the cmdlet we need: `ConvertTo-AADIntBackdoor`
**Testing:**
```console
Invoke-AtomicTest T1484.002 …
```

Use AADInternals for AAD federation attack

---

atomics/T1119/T1119.yaml
atomics/T1564.004/T1564.004.yaml

**Details:**
While using the commands from a batch file the old code wont work because of the way the variable is being called. The addition of '%' fixed the issue.
**Testing:**
Tested manually
None

Fixed Automated Collection Command Prompt variable call

---

atomics/T1112/T1112.yaml

Modify test to actually block a few example programs. Removed link to azorult malware because I couldn't find this technique being used there.

block regedit and cmd.exe

---

atomics/T1114.003/T1114.003.yaml

**Details:**
Generated new ART test for email forwarding in O365 via the PowerShell cmdlet `New-InboxRule`. Authentication is handle the same as other O365 tests (T1562.008).
**Testing:**
Ran tests via Invoke-AtomicTest, inbox rules is created and verified via `Get-InboxRule`. Cleanup also will remove all the email rules created as long as they match the optional "rule_name" input argument. 

Created email forwarding T1114.003

---

atomics/T1562.004/T1562.004.yaml

**Details:**
Adding T1562.004 Test 18 - Blackbit - Disable Windows Firewall using netsh firewall. Within BlackBit ransomware, one of the commands ran is "netsh firewall set opmode mode=disable". While "netsh firewall" has been deprecated and replaced with "netsh advfirewall", the old command still does work, leading to a vector that adversaries can use for firewall disablement.
**Testing:**
Tested on Windows 10.

Adding T1562.004 Test 18 - Blackbit - Disable Windows Firewall using netsh firewall

---

.github/workflows/stale.yml

**Details:**
Based on discussion during our most recent maintainers meeting, we'll begin to warn and then close stale issues and PRs. This change implements the default "Configure different stale timeouts" configuration, letting PRs go a little longer than issues, from https://github.com/actions/stale. 
**Testing:**
No testing has been performed. 
N/A

Create stale.yml to close stale issues and PRs

---

atomic_red_team/atomic_doc_template.md.erb

**Details:**
When generating markdown documents, certain commands were not being parsed correctly when rendering strings from Mitre ATT&CK JSON objects. This PR fixes that issue by replacing double backslash with null strings in the technique['description'] portion of the ERB template.
**Testing:**
Generated docs and the only document/technique effected by this change is T1546.008. I know it's small but it helps.
fixed #1539

fix: Fix unescaped backslash in description

---

atomics/T1098/T1098.yaml

**Details:**
- Make it clearer that this test will create an app, instead of using an existing one
- If the user ignored this, a second app with the same name as the one they wanted to use will be created. So when using the -Cleanup feature it cannot know which one to delete. Shows a warning then (instead of crashing)
- Some minor English fixes
**Testing:**
I tested all cases in a lab AAD env
Some modifications are also present in https://github.com/redcanaryco/atomic-red-team/pull/2340 and https://github.com/redcanaryco/atomic-red-team/pull/2339

Improvements to "Azure AD - adding permission to application"

---

atomics/T1140/T1140.yaml

**Details:**
Using Linux Base64 Encoded shell scripts that have Shebang in them. This is commonly how attackers obfuscate passing and executing a shell script. Seen [here](https://www.trendmicro.com/pl_pl/research/20/i/the-evolution-of-malicious-shell-scripts.html) by TrendMicro, as well as [LinPEAS](https://github.com/carlospolop/PEASS-ng/tree/master/linPEAS). Also, there is a great Sigma rule [here](https://github.com/SigmaHQ/sigma/blob/master/rules/linux/process_creation/proc_creation_lnx_base64_shebang_cli.yml) for it.  The tests work very simply by passing in encoded shells as input args that can be easily changed by anyone. 
**Testing:**

added a new test for base64 encoded shebang shells

---

atomics/T1136.003/T1136.003.yaml

**Details:**
Added a create user atomic test which uses the Azure CLI. It initially provides pre-requisites and a script to install the azure CLI if not already in place. It then prompts the user running the test to authenticate securely via MFA (if enabled) to azure ad and runs the azure cli command to create a user and then run a check to list whether it was created. There is a clean-up command to delete the user afterwards. I will make this into another atomic for account manipulation / account deletion.
**Testing:**
tested using Invoke-AtomicTest
User created
Cleanup command removes user:
None

Gk atomic red team t1136.003 azure cli

---

atomics/T1559/T1559.yaml

Uses the [Named Pipes Micro Emulation](https://github.com/center-for-threat-informed-defense/adversary_emulation_library/tree/master/micro_emulation_plans/src/named_pipes) executable from the Center for Threat Informed Defense to create a named pipe for inter-process communication.

add Cobalt Strike named pipe atomics

---

atomics/T1070.006/T1070.006.yaml

**Details:**
T1070.006 (Indicator Removal on Host: Timestomp) was missing prereqs to create files to timestomp. Also, `date` command in test 3 will now work on Mac. 
**Testing:**
All relevant test numbers (1,2,3,4) were tested on Mac, and test 3 was additionally tested on Ubuntu.
None

T1070.006 create prereqs for mac/linux timestomp

---

atomics/T1562.001/T1562.001.yaml

Added test for disabling HVCI related to https://www.microsoft.com/en-us/security/blog/2023/04/11/guidance-for-investigating-attacks-using-cve-2022-21894-the-blacklotus-campaign/

Disable HVCI

---

atomics/T1056.001/T1056.001.yaml
atomics/T1082/T1082.yaml
atomics/T1552.001/T1552.001.yaml
atomics/T1552.004/T1552.004.yaml
atomics/T1560.001/T1560.001.yaml
atomics/T1560.002/T1560.002.yaml
atomics/T1562.001/T1562.001.yaml
atomics/T1571/T1571.yaml

**Details:**
This is a collection of small fixes to input args, dependencies and exit codes.  They are needed to reliably run these tests in automation.
- dependency step should create file or dir if needed
- executor scripts should return 0 success if it ran.  The runner needs to know if the commands were executed, doesn't care about status of grep (pattern not found, etc).
**Testing:**
tested on Ubuntu 20.04
none that I am aware of.

minor cleanup to dependencies and exit codes

---

atomics/T1176/T1176.yaml

**Details:**
This test simulates an attack similar to what the Grandoreiro malware did by loading an unpacked extension in Google Chrome with the --load-extension argument.
Reference: https://securityintelligence.com/posts/grandoreiro-malware-now-targeting-banks-in-spain/
**Testing:**
Windows 10 22H2 with Google Chrome and Chromium
N/A

adding new test in T1176 - Load unpacked extension with command line

---

.gitignore
atomics/ExternalPayloads/README.md
atomics/T1003/T1003.yaml

This will address the issue described in issue #2350 
This updates only one atomic, however, after approval of this PR we will continue making the updates to the other atomic tests.

Add ExternalPayloads folder for downloaded prerequisites

---

atomics/T1562.001/T1562.001.yaml

The defender control download results in an invalid zip file so I'm removing this test until a working version can be created.

removing: Disable Defender with Defender Control

---

atomics/T1553.005/T1553.005.yaml

ISO would mount but was not able to run the .exe. I fixed it. Now it works!
Before:
After:

Update T1553.005.yaml ISO MOTW

---

atomics/T1572/T1572.md
atomics/T1572/T1572.yaml

Adding Atomic Test #4 - RDP tunneling over Ngrok Cloud to T1572
**Details:**
Adding an additional test to the technique T1572 to test for the use of Ngrok. Ngrok is a reverse proxy service that can be used to tunnel RDP, potentially concealing malicious traffic. https://attack.mitre.org/software/S0508/
**Testing:**
Tested execution of yaml file with the invoke-atomictest command.
N/A

Atomic Test #4 - RDP tunneling over Ngrok Cloud

---

.github/workflows/generate-counter.yml
.github/workflows/generate-docs.yml

**Details:**
This PR fixes GitHub workflows for GUIDs generation
**Testing:**
Tested on `cyberbuff/atomic-red-team` with the same protected branch rules as `redcanaryco/atomic-red-team`
Should fix #2496

Fix Github Workflow tokens

---

atomic_red_team/atomic_red_team.rb
atomic_red_team/attack_api.rb
bin/new-atomic.rb

**Details:**
After upgrading to Ruby 3.2.0, it appears that `File.exists?` is no longer supported. Since this is the only issue I've noticed and I believe `File.exist?` works with older versions of Ruby, this would be a subtle change.
```
root@b1a1bd803e42:/$ ruby --version
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
root@b1a1bd803e42:/$ irb
irb(main):001:0> File.exists?
(irb):1:in `<main>': undefined method `exists?' for File:Class (NoMethodError)
Did you mean?  exist?
from /usr/local/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
from /usr/local/bin/irb:25:in `load'
from /usr/local/bin/irb:25:in `<main>'
irb(main):002:0>
```
**Testing:**
I have confirmed that using `File.exist?` instead of `File.exists?` does not break anything. It appears that …

Replacing File.exists? with File.exist? for Ruby 3.2.2 support

---

atomics/T1564.003/T1564.003.yaml

**Details:**
This PR adds a test to T1564.003 for headless browsers accessing Mockbin. The Mockbin id and browser name are changeable.
Credit @MHaggis for the idea and code via Twitter [here](https://twitter.com/M_haggis/status/1701986822145056816).
This is my first contribution to ART!
**Testing:**
N/A

T1564.003 - Headless Browser Mockbin

---

atomics/T1087.002/T1087.002.yaml
atomics/T1090.003/T1090.003.yaml
atomics/T1559/T1559.yaml

**Details:**
I added the Powershell command for creating the ExternalPayloads directory for both get_prereq_commands for procedure f450461c-18d1-4452-9f0d-2c42c3f08624
**Testing:**
I tested locally and the directory is successfully created and the files successfully download to the created directory.
N/A

Added ExternalPayloads dir creation

---

atomics/T1069.002/T1069.002.yaml

not all domains have enterprise admin group, but we still want a successful exit code returned
Also, default to current user for domain group membership check

rearrange to have success exit code

---

atomics/T1218/T1218.yaml

Dependency Executor Needs to be explicitly defined
**Details:**
Apologies. The prereqs also require "powershell" to be explicitly defined as the executor.
**Testing:**
This was already tested before. I just forgot to copy the line defining the executor for the prereqs as "powershell" in my previous commit  #2596

Incorrect  Dependency Executor on T1218,12.yaml

---

atomics/T1059.004/T1059.004.yaml

It looks like this change was made erroneously since these commits don't fit the description for the atomic and there is no remote_url defined for the test

revert changes kernel info

---

atomics/T1003.007/T1003.007.yaml
atomics/T1003.008/T1003.008.yaml
atomics/T1007/T1007.yaml
atomics/T1016/T1016.yaml
atomics/T1027/T1027.yaml
atomics/T1036.006/T1036.006.yaml
atomics/T1037.004/T1037.004.yaml
atomics/T1046/T1046.yaml
atomics/T1048.003/T1048.003.yaml
atomics/T1053.002/T1053.002.yaml
bin/generate_labels.py

**Details:**
Combining FreeBSD tests into existing Linux tests. 
**Testing:**
Tested on Ubuntu 22.04

FreeBSD Cleanup

---

atomics/T1505.005/T1505.005.yaml

remove duplicate "elevation required" element

---

atomics/T1555.001/T1555.001.yaml

**Details:**
When executed with sufficient privileges, command dumps credential info from keychain.
**Testing:**
Tested successfully on OSX 14.1.1 (Sonoma).
I also plan to submit a separate pull request to rework/organize this Atomic's (T1555.001) related certificate tests.

Add test for keychain dump

---

atomics/T1112/T1112.yaml

**Details:**
These Technique was seen during analysis of DarkGate Malware that steal information and setup proxy server in the compromised host.
**Testing:**
tested manually

T1112 - DarkGate Registry Modification

---

atomics/T1047/T1047.yaml

**Details:**
- T1047-10 (c510d25b-1667-467d-8331-a56d3e9bc4ff): Fix path when downloading TightVNC and installing it. 
**Testing:**
- `Invoke-AtomicTest T1047-10 -GetPrereqs`
- `Invoke-AtomicTest T1047-10`

[FIX] T1047 - fix tightvnc path

---

atomics/T1555.003/T1555.003.yaml

**Details:**
Typo fixes in test 16. One of the `get_prereq_command` items had an incorrect URL in the `Invoke-WebRequest` command.
Old: `https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T155.003/src/LoginData?raw=true`
New: `https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1555.003/src/Login%20Data?raw=true`

Update T1555.003.yaml - typo fix

---

.devcontainer/devcontainer.json
.devcontainer/setup.ps1
README.md

**Details:**
Added Github Codespace environment files to quickly test existing atomics and also develop new atomics. Added wiki docs [here](https://github.com/redcanaryco/atomic-red-team/wiki/Github-Codespaces). Click this [link](https://github.com/codespaces/new/redcanaryco/atomic-red-team?branch=devcontainers&skip_quickstart=false&machine=basicLinux32gb&repo=106586124&ref=devcontainer&devcontainer_path=.devcontainer%2Fdevcontainer.json&geo=UsEast) if you would like to try now.

Github Codespace added

---

atomics/T1016/T1016.yaml
atomics/T1018/T1018.yaml
atomics/T1069.002/T1069.002.yaml
atomics/T1087.002/T1087.002.yaml
atomics/T1482/T1482.yaml

**Details:**
Added the "-c" option to adfind commands. This will cause it to print a count of the returned objects instead of the actual objects. This is very useful for large environments and allows it run quicker without actually exposing any sensitive information.
**Testing:**
Tested on Windows 10 VM

Added the "-c" option to adfind commands.

---

atomics/T1543.003/T1543.003.yaml

**Details:**
This test uses Powershell to modify an existing service to run an arbitrary binary, and upon cleanup, will revert the service back to its original state. By default, this test will modify the fax service to launch Notepad. This technique has previously been observed by SnapMC in its ransomware campaigns, through use of Powersploit's invoke-serviceabuse function.
Reference: hxxps://blog[.]fox-it[.]com/2021/10/11/snapmc-skips-ransomware-steals-data/
**Testing:**
Tested on Windows 10.

Adding T1543.006 Test 6 - Modify Service to Run Arbitrary Binary (Powershell)

---

atomics/T1020/T1020.yaml

Atomic Test #2 - Add New Atomic Test for T1020 - Exfiltration via Encrypted FTP
Simulates encrypted file transfer to an FTP server, representing stealthy data exfiltration methods.
**Details:**
This pull request introduces a new atomic test, "Exfiltration via Encrypted FTP," under T1020 - Automated Exfiltration. This test simulates the encrypted transfer of a file to an FTP server, a method often used by advanced threats for stealthy data exfiltration. The test is designed to help organizations improve their detection capabilities against such exfiltration techniques.
**Testing:**
The test was developed and validated in a controlled lab environment. It was executed on a Windows platform, ensuring the successful creation of a sample file, its encrypted transfer to a specified FTP server, …

Update T1020.yaml -Add New Atomic Test for T1020 - Exfiltration via Encrypted FTP

---

atomics/T1020/T1020.yaml
atomics/T1033/T1033.yaml
bin/validate/atomic-red-team.schema.yaml

**Details:**
Right now our schema validation doesnt check whether there are any additional properties that's specified in an atomic. If atomics are malformed, say cleanup_command is moved to the root path instead of `executor`, it allows the validation checks to pass. Setting `additionalProperties` to `false` in the YAML schema to fix this issue, 
**Testing:**
Tested on Github Codespaces

Fix schema validation to disable additional properties

---

atomics/T1654/T1654.yaml

**Details:**
The original PowerShell command for T1654 makes use of a script block and must use braces ({}). Without the braces this caused the script to misunderstand `$_.message` as not part of the output from `get-eventlog`. This PR fixes that issue.
**Testing:**
Local testing of the atomic has been conducted successfully. 
None - but can add an issue if required.

T1654 - Fix to PowerShell Command

---

atomics/T1204.002/src/Invoke-MalDoc.ps1

**Details:**
There was a typo in the spelling of "Excel" in the Invoke-MalDoc.ps1 inside the atomic test T1204.002 folder where it was spelled as "Exel". My assumption is that it means Excel.
**Testing:**
NA
Fixes spelling issue of Excel

Excel spelling typo

---

atomics/T1112/T1112.yaml

**Details:**
During an execution run I noticed that atomics were failing due to PowerShell scripts not being enabled on the host system. I traced the issue back to `T1112:95b25212-91a7-42ff-9613-124aca6845a8` and specifically the `REM` command that is used in place of a comment. I don't know the specifics as to why this command stops execution but it results in the subsequent deletion command not being executed. 
This screenshot shows execution of the atomic with the REM command in place, note the EnableScripts registry value remains 
This screenshot shows execution of the same atomic with the REM command removed, note the removal of the registry value.
**Testing:**
Tested on W10
None

Removing REM from T1112 - causing incorrect execution

---

atomics/T1654/T1654.yaml

…Util
Adding new test for T1654 for Enumerate Windows Security Log via WevtUtil
**Details:**
**Testing:**

Adding new test for T1654 for Enumerate Windows Security Log

---

atomics/T1219/T1219.yaml

Update RustDesk T1219
**Details:**
Addition to Remote Access Software tests (RustDesk - An adversary may attempt to trick the user into downloading RustDesk and use this to maintain access to the machine. Download of RustDesk installer will be at the destination location when successfully executed.)
**Testing:**

Update RustDesk T1219.yaml

---

atomics/T1071.001/T1071.001.md
atomics/T1071.001/T1071.001.yaml

Test 2 for T1071.001 is currently not working properly, since the pre-requisite command is incorrect. This change is to fix the .md and .yaml file to update the URL for curl.
Details: 
The URL existing in the test files currently is: :"https://curl.haxx.se/windows/dl-7.71.1/curl-7.71.1-win32-mingw.zip"
This returns a 404 error.
Replacing this URL with: "https://curl.se/windows/dl-8.6.0_2/curl-8.6.0_2-win32-mingw.zip" works.

Fix T1071.001 Test #2

---

atomics/T1542.001/T1542.001.yaml

**Details:**
Created an atomic for adding wpbbin.exe in %systemroot%\System32\. This technique can be used for UEFI-based pre-OS boot persistence. Note that the command presently only creates an empty file.
- https://grzegorztworek.medium.com/using-uefi-to-inject-executable-files-into-bitlocker-protected-drives-8ff4ca59c94c
- http://download.microsoft.com/download/8/a/2/8a2fb72d-9b96-4e2d-a559-4a27cf905a80/windows-platform-binary-table.docx
- https://github.com/tandasat/WPBT-Builder
**Testing:**
Tested the command and cleanup locally on Windows Server 2022. 

New test: T1542.001 - 'UEFI Persistence via Wpbbin.exe File Creation'

---

atomics/T1071/T1071.yaml

**Details:**
All other "type" fields use `type: integer`, however this field was `type: Integer`. This fix is extremely minor, but good for the sake of consistency. Looking through the rest of the project, this appear to be the only place where nonstandard field value capitalization occurs.
**Testing:**
I have my own validation framework which parses and validates all Atomic YMLs into [Pydantic](https://docs.pydantic.dev/latest/) Objects (making them easier to use in the context of a larger project). Rather than just treating them as dictionaries, they are real Python classes.  That is how this issue was identified.  
If there is interest, I am happy to share that code back to the project as well!
None
**Additional Comments:**
I'm not entirely sure how this schema …

Fix nonstandard capitalization in "type" field

---

atomics/T1001.002/T1001.002.yaml

**Details:**
This pull request adds a new atomic test for T1001.002 for Linux. This atomic test demonstrates the execution of an embedded script in an image file using steganography techniques. The script is first encoded in base64 and then embedded within the pixels of the image. The modified image is created, and the script is extracted and executed on the target system.
**Testing:**
In this example, script `mal.sh`  is embedded in image `8bit.jpg`. The new malicious image file `evil_image.jpg` can be used to run the script.
The Evil image can be used to execute the embedded script:
Both images are identical to a normal user:

Added new atomic test: Update T1001.002.yaml

---

atomics/T1490/T1490.yaml

**Details:**
Added a new atomic test for T1490 (Inhibit System Recovery) to disable Time Machine on macOS using `tmutil`. Attackers can use this to prevent backups from occurring and hinder the victim's ability to recover from any damage.
**Testing:**

Added new atomic test: Update T1490.yaml

---

atomics/T1082/T1082.yaml

**Details:**
The T1082 atomic `WinPwn - PowerSharpPack - Seatbelt` leverages the below command in its execution:
```
Invoke-Seatbelt -Command "-group=all"; pause
```
By default this `pause` function waits for user input (presumably so the user can see the results) and when run with `Invoke-AtomicRedTeam` causes the test to timeout.
This PR removes the `pause` command, with other options available (such as `Invoke-AtomicRedTeam`'s logging modules) to log the output of Seatbelt if this is the purpose of running the test.

Bug fix: Removed 'pause' from T1082 Seatbelt atomic that causes timeout

---

atomics/T1135/T1135.yaml

**Details:**
SharpShares is a command line tool that can be integrated with Cobalt Strike's execute-assembly module, allowing for the enumeration of network shares. This enumeration technique has been utilized by various ransomware groups, including BianLian. Upon successful execution of this test, a list of accessible network shares, along with their permissions, will be output to a specified file. 
Reference: https://www.cisa.gov/news-events/cybersecurity-advisories/aa23-136a
**Testing:**
Tested on Windows 10.

Adding T1135 Test 11 - Enumerate All Network Shares with SharpShares

---

.github/workflows/generate-counter.yml

**Details:**
There's a handful of atomics that currently don't have GUIDs (see #2753). After GUID generation got moved to `generate-counter.yml`, the commit-back phase at the end was not adjusted to capture changes to the `atomics/` folder
**Testing:**
https://github.com/redcanaryco/atomic-red-team/issues/2753

Add atomics to PR

---

atomics/T1070.004/T1070.004.yaml

**Details:**
Since the command "(Get-ChildItem -Path "$Env:SystemRoot\prefetch*.pf" | Measure-Object).Count" is not in a codebox, the '*' character is being escaped by Markdown.
Resubmitting as suggested on https://github.com/redcanaryco/atomic-red-team/pull/2581

Adding codebox so '\' characters shows up well in Markdown

---

atomics/T1135/T1135.yaml

**Details:**
Snaffler is an open source tool that has previously been used by threat groups, including Scattered Spider, to enumerate network shares, as well as search for files that potentially contain credentials/other secrets. Upon successful execution of this test, Snaffler will enumerate accessible network shares and output it to a text file.
Reference: https://unit42.paloaltonetworks.com/muddled-libra/
**Testing:**

Adding T1135 Test - Enumerate All Network Shares with Snaffler

---

atomics/T1219/T1219.yaml

**Details:**
There is a AWS secret in the T1219 test which causes the pipelines to fail. Making this an argument and removing the S3 URL to fix this issue.

Fix T1219 test

---

atomics/T1219/T1219.yaml

**Details:**
An adversary may attempt to use Splashtop Streamer to gain unattended remote interactive access. Upon successful execution, Splashtop streamer will be executed.
**Testing:**
Successfully tested

Added Splashstop streamer to T1219

---

atomics/T1562.001/T1562.001.yaml

**Details:**
1. Modified the Prereq_command on the test "Unload Sysmon Filter Driver", It was not downloading sysmon even when sysmon was not present.  Because the prereq command was returning 0 when sysmon was not there. So corrected that by removing the "-not" from the prereq command.
2. Also addded "/i" flag to findStr to make it case insensitive 
**Testing:**
1. Tested and its working

Modified the Prereq_command of Test Unload Sysmon Filter Driver

---

atomics/T1070.006/T1070.006.yaml

Remove dependencies from T1070.006's `Modify file timestamps using reference file`
**Details:**
Instead of having the file to be target file as a dependency, I think it's better to create it in test directly. As there is a -c command, we need to modify the file anyway. If people are automatically creating tests from this repo, the approach where the file is created as part of the script is better
**Testing:**
Local testing was done and the command is working

Remove dependencies from one of T1070.006 tests

---

atomics/T1016.001/T1016.001
atomics/T1614/T1614.yaml

**Details:**
Following the template of T1048.002.yaml, I created T1614.yaml focusing only on getting geolocation info through IP-Lookup services using curl to ipinfo.io (windows, linux, macos).
- Test 1: curl to ipinfo.io for windows (ipinfo.io is a parameter)
- Test 2: curl to ipinfo.io for linux, macos, freebsd (ipinfo.io is a parameter)
ATT&CK reference: https://attack.mitre.org/techniques/T1614/
On top of that, I created T1016.001.yaml slightly changing the yaml of T1614. It has 4 tests:
- Test 1: curl to ipinfo.io for windows (same as T1614, ipinfo.io is a parameter)
- Test 2: curl to ipinfo.io for linux, macos, freebsd (same as T1614, ipinfo.io is a parameter)
- Test 3: ping to 8.8.8.8 for windows (8.8.8.8 is a parameter)
- Test 4: ping to 8.8.8.8 for linux, macos, freebsd (8.8.8.8 …

Creation of T1614.yaml and T1016.001.yaml 

---

.github/workflows/generate-docs.yml

Looks like we ran into a [dependency](https://github.com/redcanaryco/atomic-red-team/actions/runs/10361863419/job/28682903316#step:9:51) error with Ruby because our CI job is using a older version. I bumped it to 3.0 and tested our doc generation scripts. They seem to be working still under the updated version. 
```
jhernandez in ~/splunk/atomic-red-teamwith 3.0.7 on fix_ruby_deps ● ● λ ruby bin/generate-atomic-docs.rb
Generating docs for /Users/jhernandez/splunk/atomic-red-team/atomics/T1654/T1654.yaml => /Users/jhernandez/splunk/atomic-red-team/atomics/T1654/T1654.md => OK
Generated docs for 313 techniques, 0 failures
Generated ATT&CK matrix at ./atomics/Indexes/Matrices/matrix.md
Generated ATT&CK matrix at ./atomics/Indexes/Matrices/windows-matrix.md
Generated ATT&CK matrix at …
```

bumped ruby to 3.0

---

atomics/T1071/T1071.yaml

**Details:**
I found a typo in in T1071, _**cam** be established_ so I fixed that. I reformulated the test description, changed a couple of uppercase and lowercase letters and added some articles that were missing here and there. I changed also a comment in the input argument (C2 server IP or URL) default to match the actual value. See the Files changed tab for the full details

Update typo and small grammar details in T1071.yaml

---

atomics/T1056.001/T1056.001.yaml

**Details:**
Replacing the date format in the `ausearch` command. This command depends on the date format, which may depend on your locale. To make it more generic, we can replace the current date and time command with `now`, which is documented in the official docs.
Here is the current execution result, that prints out `<no matches>` because of the not supported date format:
Here, instead, is the fixed version result using `now`:
**Testing:**
Tested on Ubuntu

Fix `T1056.001.yaml`

---

atomics/T1082/T1082.yaml

**Details:**
`/sys/class/dmi/id/product_name` is being compared twice instead of using `/sys/class/dmi/id/chassis_vendor`
**Testing:**
The new command works on an ec2 instance:
```
[ec2-user@ip-x-x-x-x ~]$ if [ -f /sys/class/dmi/id/chassis_vendor ]; then cat /sys/class/dmi/id/chassis_vendor | grep -i "Xen\|Bochs\|QEMU"; fi
Xen
```

Fix a typo in T1082 - Linux VM Check via Hardware

---

atomics/T1562.003/T1562.003.yaml

Details:
This test doesn't work as expected due to the comments added in the code, basically they comment out the subsequent commands. Furthermore, they are not useful since the code already prints the value of the HISTIGNORE env variable.
Testing: 
Tested on Ubuntu.

Fix T1562.003.yaml

---

atomics/T1518.001/T1518.001.yaml

**Details:**
This update adds a new atomic test to execute a WMIC command that retrieves Windows Defender exclusion settings. It helps simulate how attackers might identify configurations that disable real-time monitoring or specify excluded paths, file types, and processes.
**Testing:**
Tested on a local windows machine, confirming that the WMIC command correctly retrieves the desired configuration details without errors. Screenshot below.

Add new atomic - T1518.001.yaml

---

atomics/T1120/T1120.yaml

**Details:**
Using PowerShell to gather printer information on Windows systems. The test checks for connected printers, providing insight into potential peripheral device discovery tactics.
**Testing:**
Confirmed that the Get-Printer command accurately lists all connected printers across tested Windows environments.

Get Printer Device List via PowerShell Command

---

atomics/T1611/T1611.yaml

**Details:**
This atomic test demonstrates a privilege escalation attack leveraging Docker's volume mapping feature. By mounting the root directory of the host into a Docker container, the attacker can use the `chroot `command to access the host system as root. The test highlights the risks associated with granting excessive permissions to Docker users. It includes commands for setting up and cleaning up the environment, ensuring accurate execution and proper cleanup.
**Testing:**
- Verified that the Docker installation is detected as a prerequisite.
- Confirmed that the user running the test has the required NOPASSWD permissions for Docker.
- Successfully executed the command to mount the host root directory and escalate privileges using chroot.
- Ensured the cleanup command removes any …

New Atomic - Privilege Escalation via Docker Volume Mapping

---

atomics/T1048/T1048.yaml

**Details:**
This pull request provides an atomic test focusing on DNS-based data exfiltration techniques via the `dig` command. The test encodes input data in base64 format and sends it as a subdomain within a DNS query to a configurable attacker's DNS server. Input arguments allow for specifying the DNS server's address and port as well as the sensitive information to be encoded. The `dig` command is validated and installed dynamically using multiple package managers to ensure broad platform compatibility.
**Testing:**
The attack scenario was successfully executed, during which the secret data was encoded, sent as part of a DNS query, and subsequently captured by a DNS server hosted on a Docker container. This setup highlights the ability to simulate data exfiltration via DNS and verify …

New Atomic - Exfiltrate Data using DNS Queries via dig

---

atomics/T1552.001/T1552.001.yaml

Adding support for Azure, GCP, and OCI
Also fixed AWS check
**Details:**
Added file system searches for Azure, GCP, and OCI credentials:
- Azure: `#{file_path}/.azure` with files named either `msal_token_cache.json` or `accessTokens.json`
- GCP: `#{file_path}/.config/gcloud` with files named either `credentials.db` or `access_tokens.json`
- OCI: `#{file_path}/.oci/sessions` with files named `token`
Also adjusted the `find` command for the AWS credential search as it would look outside of expected locations
**Testing:**
Here is the output of me performing all four searches on my local system (macOS):
- AWS
```powershell
Invoke-AtomicTest T1552.001 -TestNames "Find AWS credentials" -InputArgs @{"file_path" = "/Users/nicholsr"}
```
```text
PathToAtomicsFolder = …
```

feat: more cloud credential discovery

---

atomics/T1539/T1539.yaml

**Details:**
Created T1539 test to extract Chrome cookies via Remote Debugging in PowerShell. No dependencies or cleanup items needed.
**Testing:**
Tested on Windows Server 2019 with latest Chrome installed
No issues

New T1539 Test for Chrome ABE Bypass via Remote Debugging

---

atomics/T1497.001/T1497.001.yaml

**Details:**
Added 3 tests for T1497.001
**Testing:**
Tested locally on Macbook Air.

Added additional tests for Virtualization/Sandbox Evasion: System Checks

---

atomics/T1046/T1046.yaml

**Details:**
Modified test GUID 05df2a79-dba6-4088-a804-9ca0802ca8e4 - name: "Port-Scanning /24 Subnet with PowerShell"
to add an option to pass a CSV list of IP addresses to the ip_address parameter in order to support simulating a wider scan, by scanning specific hosts e.g., honeypots, and avoid a noisier scan to the full subnet. 
**Testing:**
Tested with a IP list, port list, and without any parameters. all tests completed successfully 
n/a

T1046 - added csv option to ip_address parameter to test number 10

---

atomics/T1555.001/T1555.001.yaml

**Details:**
Adding test for T1555.001 keychain copying that has been seen with Atomic Stealer
**Testing:**
Tested on macOS 14.6.1

T1555.001 Copy Keychain via cat

---

atomic_red_team/atomic_doc_template.md.erb

Simple fix to correct html rendering of markdown content such as links. See description paragraph here: <img width="1512" alt="396270449-22374f00-48d3-4d50-bdf6-7f9fee5832e4" src="https://github.com/user-attachments/assets/f0e95b6f-65ad-4fe3-a01d-c465fd374d38" />
Thanks to @cyberbuff for the confirmation of a viable fix!!
**Details:**
Whitespace around the `<blockquote>` and `</blockquote>` tags seems to cause unpredictable behavior when converting a test's markdown file to html.  This should address that error.
**Testing:**
Tested with manually-edited html in a sandbox.
Should fix this: https://github.com/redcanaryco/atomicredteam.io/issues/230 (only visible to .io site folks)

fix MD->HTML render for .io site

---

atomics/T1219/T1219.yaml

Added a test for quick assist microsoft app
**Details:**
The test simply uses powershell to run the default installed quick assist application which permits users to grant access to anyone to remote into the device
**Testing:**
Local testing done 
unknown. I had some time to contribute again.

Update T1219.yaml with Quick assist

---

atomics/T1562.004/T1562.004.yaml

**Details:**
Added get prereq command to install iptables for T1562.004
**Testing:**
Tested on Ubuntu machine

Fix: Get prereq T1562.004

---

atomics/T1046/T1046.yaml

**Details:**
Added one more atomic test similar to test number 2, but scans a range of ports on a remote host.
**Testing:**
Executed with the command `Invoke-AtomicTest T1046-12 -PathToAtomicsFolder ./atomics -InputArgs @{"host" = "IP_REDACTED"; "port_range" = "0-1024,54122"}` from a macOS system. Results shown below.
No issues corrected with this PR.

feat: Add T1046-12

---

atomics/T1546.008/T1546.008.yaml

This is a proposal for a new atomic test for T1546.008. This test builds off of Atomic Test 2. 
**Details:**
In this test, utilman.exe is replaced with cmd.exe in order to launch an elevated command prompt by clicking the Ease of Access button on the login screen.
**Testing:**
Both the attack commands and cleanup command have been successfully tested in a Windows 11 VM.
No issues to report.

Update T1546.008.yaml - New Atomic Test

---

atomics/T1027.013/T1027.013.yaml

Added an atomic to decrypt an encrypted eicar value to file.
**Details:**
**Testing:**

Add atomic test "Decrypt to file" to T1027.013.yaml
